### ISSUE TITLE
General organization

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#1]
The general vision would be to have a number of different _modules_ (or some other name if you'd prefer) that can be applied to decorate the current data structure. For example, the `frequencies` module could decorate nodes with frequency trajectories given a tree with dated tips. The `ancestral` module could decorate nodes with sequence states given a tree with sequences at the tips. We want modules that can be included or not in a pipeline without messing up downstream modules. I could even imagine explicit _build_ requirements, where the `frequencies` module requires that the `tree` module have ran. These modules could live in the `modules/` directory.

There would then be a separate set of _pipelines_ (or some other name if you'd prefer) that load these modules. These would live in a `pipelines/` directory, within which would be things like `pipelines/zika/` and `pipelines/flu`. I actually think that `titers` would be a general module rather than living in the `flu/` directory as the `titers` module may work well for dengue or B cells. I'm calling these _pipelines_ rather than _viruses_ because we could well end up with Salmonella or whatever as entries.

I _think_ it makes the most sense for metadata to live alongside pipelines, like `pipelines/zika/zika.py` and `pipelines/zika/metadata/`, but I'm not sure.

**Comment by rneher** [comment]
I think this is settled

**Comment by trvrb** [comment]
Agreed. Thank you.
