### ISSUE TITLE
ENH(filter): Add post-include exclude, e.g `--must-exclude`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1038]
### Context
I have a list of strains that I would like filter include, but not if they are in an exclude list.

Right now, it doesn't seem possible to do this easily in one stop - since include comes after the standard exclude.

It would be nice if we could add an extra arg `--never-include` or `--definitely-exclude` that comes right at the end.

This shouldn't be too hard to do and would save me from needing to do stuff like this as a workaround:

```bash
        # Remove excluded strains - this is the unnecessary step that this feature request would remove
        augur filter \
            --sequences {input.sequences} \
            --metadata {input.metadata} \
            --exclude {input.exclude} \
            --min-date {params.min_date} \
            --min-length {params.min_length} \
            --output-metadata {output.tmp_metadata} \
            --output-log {output.log1}

        # Add strains from include_strains.txt
        augur filter \
            --sequences {input.sequences} \
            --metadata {output.tmp_metadata} \
            --exclude-all \
            --include {input.include_strains} \
            --output-sequences {output.sequences}\
            --output-metadata {output.metadata} \
            --output-log {output.log2}
```

**Comment by victorlin** [comment]
Another workaround with less computational overhead would be to use an external tool to first filter the `--include` file, like so:

```sh
cat > metadata.tsv << ~~
strain	col
SEQ1	a
SEQ2	b
SEQ3	c
SEQ4	d
~~

cat > include.txt << ~~
SEQ1
SEQ2
SEQ3
~~

cat > exclude.txt << ~~
SEQ3
SEQ4
~~

# source: https://stackoverflow.com/a/32267899
grep -Fvxf exclude.txt include.txt > include-minus-exclude.txt

augur filter \
--metadata metadata.tsv \
--exclude-all \
--include include-minus-exclude.txt \
--output-strains out.txt
```

**Comment by corneliusroemer** [comment]
Good idea @victorlin but I don't think that cuts it because the include will overwrite exclusion due to minimum sequence length, for example.

**Comment by victorlin** [comment]
The feature request here is an additional exclusion file that contains a list of sequences right?

If you want to force exclusion by minimum sequence length, then that would be something else (e.g. `--must-min-length`). Then that would extrapolate to having "post-include" counterparts to every existing exclude (e.g. `--must-min-date`, `--must-pass-query`, ...).

**Comment by corneliusroemer** [comment]
True!

I think it would help to write out the various steps and see where we're
missing something.

Your workaround works in the situation of wanting an exclude that comes
after include.

But it's annoying to need an extra grep ;)

Something else that's missing is more flexible metadata querying. I should
open another issue for that.

**Comment by tsibley** [comment]
Ha, I came here to note the same solution @victorlin did. FWIW, you can you inline the extra grep so it's not so extra:

```bash
augur filter \
  --metadata metadata.tsv \
  --exclude-all \
  --include <(grep -Fvxf exclude.txt include.txt) \
  --output-strains out.txt
```

**Comment by corneliusroemer** [comment]
After some more thought - what I may really be after is an `--include` that does not overwrite exclusion due to: `exclude`, `min-date`, `min-length`, basically:

1. Exclude based on --exclude
1. Exclude based on `min-date` `min-length`...
1. Subsample whatever survives
1. Add includes, but only if they passed steps 1-2
1. Add must-includes even if they didn't pass 1-2

Right now we seem to treat `--include` as a `--must-include` not as a `--include-despite-sampling`

Does that make sense? See for the use case here: https://github.com/nextstrain/monkeypox/pull/121

**Comment by emmahodcroft** [comment]
I'm hesitant to overload `augur filter` so that everything is possible in one call. It seems to me like doing two filters and then combining the results would be the solution here, and would be much more clear logically. In general `include` is there to override the other filter options - if you're trying to do more complex sampling, like treating one group differently from another, I think it's ok if this takes two or more steps.

**Comment by joverlee521** [comment]
I agree with @emmahodcroft. I think `augur filter` is already pretty overloaded and it's hard to understand how all of the options interact with each other. 

The two step filter + subsample implemented in  https://github.com/nextstrain/monkeypox/pull/121 is straightforward and easy to understand.
