### ISSUE TITLE
Breaking changes in pandas 1.5.0

### ISSUE THREAD

**Issue by tsibley** [nextstrain/augur#1049]
[Augur CI failures just now](https://github.com/nextstrain/augur/actions/runs/3084758508/jobs/4987276782#step:10:223) on master (triggered by my merge of #1010) seem to be an symptom of pandas 1.5.0, [released ~3 hours ago](https://pypi.org/project/pandas/1.5.0/).

```
+    File "/home/runner/work/augur/augur/augur/filter.py", line 866, in apply_filters
+      if isinstance(e, pd.core.computation.ops.UndefinedVariableError):
+  AttributeError: module 'pandas.core.computation.ops' has no attribute 'UndefinedVariableError'
```

From what I've seen so far, this appears to be limited to our error handling around `augur filter --query` so won't appear for users unless they have a bad query.

**Comment by victorlin** [comment]
According to [release notes](https://pandas.pydata.org/docs/whatsnew/v1.5.0.html), the error class has been moved to `pandas.errors`, so the reference in Augur just needs to be updated along with a pandas version bump to require >=1.5.0.

**Comment by tsibley** [comment]
I'd suggest using `pandas.errors` and `pandas.core.computation.ops` and not bumping the version.

Auditing for usage of the other classes moved in https://github.com/pandas-dev/pandas/issues/27656:

```
DataError
SpecificationError
SettingWithCopyError
SettingWithCopyWarning
NumExprClobberingError
UndefinedVariableError
IndexingError
PyperclipException
PyperclipWindowsException
CSSWarning
PossibleDataLossError
ClosedFileError
IncompatibilityWarning
AttributeConflictWarning
DatabaseError
PossiblePrecisionLoss
ValueLabelTypeMismatch
InvalidColumnName
CategoricalConversionWarning
```

I don't find any other occurrences.
