### ISSUE TITLE
Strain is duplicated in output tree.json

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#105]
Currently, output `tree.json` files have `strain` listed for each node as both a direct attribute and as an attribute under `attr`, like so:

```
"strain": "NGA/2016/ISTH_0187", 
"tvalue": 362.23867, 
"yvalue": 266.0, 
"attr": {
	"raw_date": "2016-01-17"
	"strain": "NGA/2016/ISTH_0187", 
	"country": "nigeria", 
	"region": "africa", 
	"accesion": "MH053478", 
	"host_species": "human", 	
```

This is confusing. As described here: https://github.com/nextstrain/augur/blob/master/docs/auspice_output.md#tree-json, `strain` should live directly under a node.

**Comment by jameshadfield** [comment]
For the record, those docs (in augur) will be out of date. The JSON spec is best viewed here: https://nextstrain-static-dev.herokuapp.com/api/auspice/json-format. I'll remove those docs today.

**Comment by trvrb** [comment]
I just checked and this issue is resolved in modular augur. I'm going to mark this as closed.
