### ISSUE TITLE
DOC(export): Document auspice config options and what they mean

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1056]
I wanted to look for all the things that can be configured through our auspice_config but couldn't find much in the documentation.

The `augur export v2` docs just say:
```
--auspice-config
Auspice configuration file
```
which is very incomplete.

<img width="859" alt="image" src="https://user-images.githubusercontent.com/25161793/193416219-ffde4a40-18c8-4fdc-9df2-ddb8fda0e194.png">

Do we have something other than the schema at: https://github.com/nextstrain/augur/blob/master/augur/data/schema-auspice-config-v2.json

Is there a way we can turn the schema directly into documentation?

It would be great if there was a description of what values are expected by the various color scales for example, this isn't exactly self-documenting: `"enum": ["continuous", "temporal", "ordinal", "categorical", "boolean"]`

**Comment by jameshadfield** [comment]
There is documentation of the dataset JSON settings [in auspice's docs](https://docs.nextstrain.org/projects/auspice/en/stable/advanced-functionality/view-settings.html#dataset-json-configurable-defaults), and the key names are the same (I think?) for the auspice-config JSON, but it would be good to centralise this.

**Comment by huddlej** [comment]
@tsibley notes that there is a lot of support for storing document inside the JSON schema for the config file itself and there are tools that integrate with sphinx to autogenerate doc pages. It sounds like there are at least two steps to closing this issue with this approach:

1. Write the documentation in the schema files
2. Setup sphinx integration for schema-to-docs generation

**Comment by jameshadfield** [comment]
👍 Create docs version of auspice config schema #819

**Comment by corneliusroemer** [comment]
Duplicate of #819
