### ISSUE TITLE
filter: Allow `--group-by week`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1063]
### Context
To make sample boundaries smoother and allow focusing on very recent weeks in ncov, it would help if we had the ability to group by week, in addition to `year` and `month`.

Right now only year and month are supported, unfortunately. This creates quite sharp boundaries in our plots. Sampling by week would smooth things out a lot and allow recent weeks with less data to be more evenly represented.

**Comment by corneliusroemer** [comment]
Exact implementation details aren't that important I think - it's more important to have _something_ and the sooner the better as this would be highly useful at the moment.

**Comment by victorlin** [comment]
Closing this as a duplicate of #960.
