### ISSUE TITLE
ENH: Allow export without any `--node-data`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1064]
### Context
I wanted to test how a certain export worked. I just have `nwk` tree, metadata and auspice_config.json

I don't have any node-data. I would like to still run export.

But when I do I get an error that `--node-data` is required.

I get that branch lengths are very important, but to test export it's not necessary.

I could appease export by passing a `recency.json` that doesn't change anything about the branch_length situation.

It doesn't make much sense to require any `--node-data`. If so we should require _specific_ node data or no node data.

**Comment by jameshadfield** [comment]
Yup! This is the same as https://github.com/nextstrain/augur/issues/273 but would be great to fix
