### ISSUE TITLE
ENH: Support `3W` for `--max/min-date` in filter, as we support `3M`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1066]
### Context
To make nextstrain builds useful again for variant spotting, it would be great if one could filter min/max date by week relative to current date.

We do support `--min-date 3M` right now for "sampled in previous 3 months", but I'm not sure `--min-date 3W` or `--min-date 3D` works. It would be great if we could make this work as well to be more flexible for making builds with recent focus.

I assumed this was possible seeing we used pandas and timedelta in the date filter, but for some reason it didn't work when I quickly tried this out.

@victorlin I hope it's ok if I add you to this.

**Comment by tsibley** [comment]
Hmm. `--min-date` and `--max-date` should support [ISO 8601 duration strings](https://en.wikipedia.org/wiki/ISO_8601#Durations) (with the slight extension that the per-spec leading `P` is optional), so `--min-date 3W` and `--min-date 3D` should both work.

https://github.com/nextstrain/augur/blob/e1e8bb155c25a2901bcd41423b0f67d14386b6b3/augur/dates.py#L12-L34

**Comment by joverlee521** [comment]
> for some reason it didn't work when I quickly tried this out.

Did it raise an error or was the output of the command not what you expected?

**Comment by victorlin** [comment]
This works fine:

```sh
cat >metadata.tsv <<~~
strain	date
SEQ1	2022-09-28
SEQ2	2022-09-29
SEQ3	2022-09-30
SEQ4	2022-10-01
SEQ5	2022-10-02
~~

augur filter --metadata metadata.tsv --min-date 3W --output-metadata out.txt
# 1 strains were dropped during filtering
# 	1 of these were dropped because they were earlier than 2022.74 or missing a date
# 4 strains passed all filters
```

And note that it's described in the output of `augur filter -h`:

```
  --min-date MIN_DATE   minimal cutoff for date, the cutoff date is inclusive; may be specified as: 1. an Augur-style numeric date
                        with the year as the integer part (e.g. 2020.42) or 2. a date in ISO 8601 date format (i.e. YYYY-MM-DD) (e.g.
                        '2020-06-04') or 3. a backwards-looking relative date in ISO 8601 duration format with optional P prefix (e.g.
                        '1W', 'P1W') (default: None)
```

Closing as "can't repro", but @corneliusroemer please re-open if you can reproduce.
