### ISSUE TITLE
Update pin for `xopen`

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/augur#1073]
### Context
`xopen` has added **optional** support for zstandard files (see: https://github.com/pycompression/xopen/pull/91) 

Should we update our pin for `xopen` to guarantee support for zstandard files for `augur.io` functions?

**Comment by huddlej** [comment]
Updating the pin sounds like a good idea. xopen doesn't require [a newer minimum Python version](https://github.com/pycompression/xopen/blob/5ddd692b5ce436d144d05ab7303bf52d8131bec6/setup.cfg#L16) than we do, so unless there are other dependency conflicts we should probably do it.

**Comment by victorlin** [comment]
This needs to wait for a release with that merged change.
