### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'SITE'

### ISSUE THREAD

**Issue by mariamLaamarti** [nextstrain/augur#1075]
Hello, 

I'm trying to run the tb pipline, and i got this error n the augure sequence-traits step, 
can you please help.

 augur sequence-traits             --ancestral-sequences nt_muts.vcf             --vcf-reference translations.vcf             --vcf-translate-reference translations_reference.fasta             --features drm_sites.txt             --count traits             --label Drug_Resistance             --output-node-data drms.json
This method may change in future! Please use 'augur sequence-traits -h' to check the latest options.
Unfortunately this method currently only works with VCF input.
Traceback (most recent call last):
  File "/home/mariem/miniconda3/envs/nextstrain/lib/python3.10/site-packages/augur/__init__.py", line 81, in run
    return args.__command__.run(args)
  File "/home/mariem/miniconda3/envs/nextstrain/lib/python3.10/site-packages/augur/sequence_traits.py", line 331, in run
    features = read_in_features(args.features)
  File "/home/mariem/miniconda3/envs/nextstrain/lib/python3.10/site-packages/augur/sequence_traits.py", line 168, in read_in_features
    pos = m.SITE-1 #put in python numbering
  File "/home/mariem/miniconda3/envs/nextstrain/lib/python3.10/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'SITE'

**Comment by victorlin** [comment]
Hi @mariamLaamarti,

I'm sorry you're running into this uninformative error! At the very least, the error message can be improved.

I think this error means your file `drm_sites.txt` does not have the correct columns. Can you check that the file has the five columns listed on [this documentation page](https://docs.nextstrain.org/en/latest/guides/bioinformatics/seq_traits.html)? It is also referenced in the output of `augur sequence-traits --help`:

```
  --features FEATURES   file that specifies sites defining the features in a
                        tab-delimited format: "GENE SITE ALT DISPLAY_NAME
                        FEATURE". For nucleotide sites, GENE can be "nuc" (or
                        column excluded entirely for all-nuc sites).
                        "DISPLAY_NAME" can be blank or excluded entirely.
                        (default: None)
```

**Comment by victorlin** [comment]
In case you are re-using some files from [nextstrain/tb](https://github.com/nextstrain/tb/blob/master/Snakefile), the `--features` file be [config/DRMs-AAnuc.tsv](https://github.com/nextstrain/tb/blob/master/config/DRMs-AAnuc.tsv), not [config/drm_sites.txt](https://github.com/nextstrain/tb/blob/master/config/drm_sites.txt).

**Comment by victorlin** [comment]
Close this as "can't reproduce" due to inactivity. Please re-open if you are still facing this issue or have more information.
