### ISSUE TITLE
Cram tests: `$TMP` is not a per-test directory

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1083]
_Filing this issue mostly to document behavior that I came across today._

### Context

Unintuitively, the `$TMP` directory defined by Cram [is the same across all tests invoked by the same `cram` command](https://github.com/brodie/cram/blob/d245cca8d121ea1d5bbad3b76e343540df313973/cram/_main.py#L183-L186). This means it isn't cleaned up at the end of each test, and lingering output files from one test may affect the outcome of another test.

Instead, the starting directory of a test file is a directory under `$TMP` that is truly unique for that test file.

### How to reproduce

See [this GitHub gist](https://gist.github.com/victorlin/440f35d39de25f44cedd405285eda2e3).

#### 1. Clean up `$TMP` after every test

This is what most tests do already (e.g. [tests/functional/mask.t](https://github.com/nextstrain/augur/blob/7f968ce7a0ebf1226bf1a5e99717f0175ae55159/tests/functional/mask.t)). However, some tests still leave things under `$TMP` (e.g. [tests/builds/zika.t](https://github.com/nextstrain/augur/blob/7f968ce7a0ebf1226bf1a5e99717f0175ae55159/tests/builds/zika.t) leaves a directory `$TMP/out/`). Find these lingering files and add cleanup commands to prevent unintended side effects.

#### 2. Run tests from the starting directory

1. Remove `pushd $TESTDIR …` commands to stay in the per-test temporary directory.
2. Change the `export AUGUR` commands accordingly.
3. Replace all usage of `$TMP` with relative paths.
4. Update the relative paths with `$TESTDIR` to use existing test files.

**Comment by corneliusroemer** [comment]
Thanks for tackling this! I've noticed this in the past, too.

**Comment by victorlin** [comment]
This has been factored into [dev docs](https://github.com/nextstrain/augur/blob/5d04da22723a308069b8b0ea457beb3f212b5e67/docs/contribute/DEV_DOCS.md#tips-for-writing-cram-tests) and concrete solutions proposed in #1176.
