### ISSUE TITLE
minor bugs 

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#11]
A running list of minor bugs found during analysis of H7N9 data.

- [ ] reference genome gene co-ords misparsed for complex genbank
- [ ] spaces in strain names throw alignment errors
- [ ] `country_cmap` must be hardcoded
- [ ] geo_inference fails if # countries < 2

**Comment by rneher** [comment]
94eaec7017b7095c03049e9cac42540a71ab20a2 should fix the geo inference. 

the `country_cmap` should have a fall back in auspice rather than augur. 

spaces in fasta labels are not allowed. `fauna` should fix them

I usually curated the reference genomes bc genbank files are very non-standardized.
