### ISSUE TITLE
refine: `--year-bounds` has no effect

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1136]
### Current Behavior

The help text of `--year-bounds` states:

```
  --year-bounds YEAR_BOUNDS [YEAR_BOUNDS ...]
                        specify min or max & min prediction bounds for samples with XX in year (default: None)
```

However, ambiguous dates with `XX` in the year are unbounded by the value passed to this option.

The value gets passed through many functions in dates.py, down to [DateDisambiguator](https://github.com/nextstrain/augur/blob/e4614f274595a4ebd4f53a8d0c6f9a4197fa0283/augur/util_support/date_disambiguator.py#L44) where it is left unused.

I believe this is because [some old logic](https://github.com/nextstrain/augur/commit/1cf41fb7eb388077aff0ded044d32aab2e4c5590#diff-8f66173c8ddc9d2afae3a0146d3abfcf6004537354e5ba7cec8fdf5186c3c0f0L75-L82) got lost in a refactor: 1cf41fb7eb388077aff0ded044d32aab2e4c5590

### Expected behavior

This option should limit the range of date inference when `XX` is in the year.

### How to reproduce

1. Setup: Create a copy of tests/functional/refine/metadata.tsv, adding partial ambiguity on the century-level (`20XX`) for the first strain `PAN/CDC_259359_V1_V3/2015`.

    ```sh
    cat >metadata-custom-date.tsv << ~~
    strain	date
    PAN/CDC_259359_V1_V3/2015	20XX-XX-XX
    COL/FLR_00024/2015	2015-12-XX
    PRVABC59	2015-12-XX
    COL/FLR_00008/2015	2015-12-XX
    Colombia/2016/ZC204Se	2016-01-06
    ZKC2/2016	2016-02-16
    VEN/UF_1/2016	2016-03-25
    DOM/2016/BB_0059	2016-04-04
    BRA/2016/FC_6706	2016-04-08
    DOM/2016/BB_0183	2016-04-18
    EcEs062_16	2016-04-XX
    HND/2016/HU_ME59	2016-05-13
    ~~
    ```

2. Run without `--year-bounds`. Note that `--timetree` must be specified otherwise the `--year-bounds` value is never used in refine.py. Observe that the inferred date for the strain is `2023-01-26`.

    ```sh
    augur refine \
      --tree tests/functional/refine/tree_raw.nwk \
      --alignment tests/functional/refine/aligned.fasta \
      --metadata metadata-custom-date.tsv \
      --timetree \
      --output-tree output_tree.nwk \
      --output-node-data output_branch_lengths.json \
      --coalescent opt \
      --date-confidence \
      --date-inference marginal \
      --clock-filter-iqd 4 \
      --seed 314159 \
      --divergence-units mutations-per-site

    jq -r '.nodes."PAN/CDC_259359_V1_V3/2015".date' output_branch_lengths.json
    # 2023-01-26
    ```

3. Run with `--year-bounds 1900 2000`. That should have limited the inferred date to be between 1900 and 2000, however it is still `2023-01-26`.

    ```sh
    augur refine \
      --tree tests/functional/refine/tree_raw.nwk \
      --alignment tests/functional/refine/aligned.fasta \
      --metadata metadata-custom-date.tsv \
      --timetree \
      --year-bounds 1900 2000 \
      --output-tree output_tree_year_bounds.nwk \
      --output-node-data output_branch_lengths_year_bounds.json \
      --coalescent opt \
      --date-confidence \
      --date-inference marginal \
      --clock-filter-iqd 4 \
      --seed 314159 \
      --divergence-units mutations-per-site

    jq -r '.nodes."PAN/CDC_259359_V1_V3/2015".date' output_branch_lengths_year_bounds.json
    # 2023-01-26
    ```

### Existing usage

A [simple GitHub search](https://github.com/search?q=augur+refine+--year-bounds+NOT+path%3A%2F%5Eaugur%5C%2Frefine.py%2F&type=code) shows these public usages:

- [External workshop from May 2020](https://github.com/apeltzer/plague-phylogeography/blob/c46c2c5cb29fb0178d64a4159de440e04f674e66/docs/exhibit/exhibit_dhsi2020.rst?plain=1#L215)
- [Neher lab workshop from Jan 2019](https://github.com/neherlab/2019-krisp-nextstrain-workshop/blob/36c4931a148128f272184d125b2b78f1d88175da/tb_walker/Snakefile#L71-L82)

There may be non-public usages.

### Possible solution

1. Remove the option. Formally, this would be a breaking change, though it has been broken since version [9.0.0](https://github.com/nextstrain/augur/tree/9.0.0).
2. Properly re-implement functionality.

**Comment by tsibley** [comment]
> Remove the flag. A [simple GitHub search](https://github.com/search?q=augur+refine+--year-bounds+NOT+path%3A%2F%5Eaugur%5C%2Frefine.py%2F&type=code) shows only one public usage of this, last updated in May 2020. I don't think it's being actively used.

A search of public code on GitHub is not, IMO, sufficient for determining usage of Augur. I expect (justifiably, I think) that a lot of Augur usage is "dark", e.g. not publicly visible.

That's not to say we can't remove `--year-bounds`, but I don't think we can use public code search to declare it unused.

**Comment by tsibley** [comment]
(I realize in this case it's kinda moot because `--year-bounds` hasn't done anything for 2 years, but the general point remains.)

**Comment by tsibley** [comment]
But also, maybe it _should_ work, since we ourselves expected it to (and it used to)? 

https://github.com/neherlab/2019-krisp-nextstrain-workshop/blob/master/tb_walker/Snakefile#L71-L82

**Comment by victorlin** [comment]
I just realized that the previous example was irrelevant as `--timetree` wasn't passed, so `--year-bounds` wasn't even used in refine.py. Updated with a better example that explains expected vs. observed behavior.

**Comment by victorlin** [comment]
I mentioned this in [Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1674769150665199) and the consensus is to properly re-implement functionality.
