### ISSUE TITLE
dates: Unsupported ambiguity significance leads to unhandled exception

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1137]
### Current Behavior

When metadata contains a date that has an ambiguous month followed by an exact day (e.g. `2022-XX-30`), an unhandled exception is shown.

The same goes for ambiguous years followed by exact month and/or day.

### Expected behavior

There should not be an unhandled exception. I'd think behavior should follow as if the exact date parts were ambiguous, possibly with a warning message indicating the implicit conversion. See "Possible solutions" section for detailed alternatives.

### How to reproduce

```sh
cat >metadata.tsv <<~~
strain	date
SEQ1	2022-09-28
SEQ2	2022-09-29
SEQ3	2022-XX-30
SEQ4	XXXX-10-01
SEQ5	2022-10-02
~~

augur filter \
  --metadata metadata.tsv \
  --min-date 2022-09-29 \
  --output-metadata out.txt
# ... long stack trace
# ValueError: Invalid date: Month contains uncertainty, so day must also be uncertain.
```

### Possible solutions

1. Handle the exception properly to avoid printing a stack trace, and add a more specific output (e.g. `ValueError: Invalid date '2022-XX-30': Month contains uncertainty, so day must also be uncertain.`). However, (1) this only sounds beneficial if all invalid dates are specified which requires a heavier code change, and (2) this still doesn't allow the command to continue as it would if the exact date parts were ambiguous.
2. Make date parsing "smart" and automatically apply ambiguity to more specific parts (e.g. `2022-XX-30` → `2022-XX-XX`, `XXXX-10-01` → `XXXX-XX-XX`). This would allow the command to run successfully, possibly with warnings such as:

    ```
    WARNING: 'metadata.tsv' contains a date '2022-XX-30' which will be treated as '2022-XX-XX'.
    WARNING: 'metadata.tsv' contains a date 'XXXX-10-01' which will be treated as 'XXXX-XX-XX'.
    ```

**Comment by emmahodcroft** [comment]
I think we discussed this previously either in an issue or on Slack - However for me I voted to keep this as an error because this type of date is nonsensical and the user should be alerted. For example, this may occur because someone is using 'American style' dates (day in the middle). Or, at best, something's gone super wrong with their parsing and they've XX-ed out the wrong column or something. Either way, Having ambiguous month and non-ambig day is nonsensical and the user should fix this appropriately on their end (flipping day month or amibig-ing everything) rather than us silently changing what they may be expecting to run.

**Comment by emmahodcroft** [comment]
However I agree that we may need to be more specific in an error message, if the current one shows the same thing for both bad-ambig months & bad-ambig years!

**Comment by victorlin** [comment]
Thanks for adding your input again @emmahodcroft! You're right, we discussed this in #855 and I completely forgot.

Sounds like this should be kept as an error. We'll just need to handle the exception properly so it doesn't print out the long stack trace.

**Comment by victorlin** [comment]
> However I agree that we may need to be more specific in an error message, if the current one shows the same thing for both bad-ambig months & bad-ambig years!

The messages are actually different:

```sh
# triggered by 2022-XX-30
ValueError: Invalid date: Month contains uncertainty, so day must also be uncertain.

# triggered by XXXX-10-01
ValueError: Invalid date: Year contains uncertainty, so month and day must also be uncertain.
```

But I think they can be made better by printing out the culprit date string which should be an easy change:

```
ValueError: Invalid date '2022-XX-30': Month contains uncertainty, so day must also be uncertain.
ValueError: Invalid date 'XXXX-10-01': Year contains uncertainty, so month and day must also be uncertain.
```

**Comment by emmahodcroft** [comment]
Ah yes, it's always nice if we can print examples so that people know what to go hunt down in their data! 👍

**Comment by victorlin** [comment]
With #1140, the error messages become:

```
ERROR: Invalid date '2022-XX-30': Month contains uncertainty, so day must also be uncertain.
ERROR: Invalid date 'XXXX-10-01': Year contains uncertainty, so month and day must also be uncertain.
```
