### ISSUE TITLE
ENH: Augur clades does not throw helpful error when no `--clades` is passed

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1153]
### Context
Augur clades doesn't seem to throw a helpful error when required options are missing.

Also, the documentation doesn't seem to mention which options are required.

E.g. (from a user who didn't pass any `--clades` option:

```
augur clades --tree results/tree.nwk --mutations results/nt_muts.json --reference data/reference.fasta --output-node-data augur_node_data.json
Validating schema of 'results/nt_muts.json'...
Traceback (most recent call last):
  File "/nextstrain/augur/augur/__init__.py", line 67, in run
    return args.__command__.run(args)
  File "/nextstrain/augur/augur/clades.py", line 280, in run
    clade_designations = read_in_clade_definitions(args.clades)
  File "/nextstrain/augur/augur/clades.py", line 51, in read_in_clade_definitions
    sep='\t' if clade_file.endswith('.tsv') else ',',
AttributeError: 'NoneType' object has no attribute 'endswith'
```

Also confusingly, it can appear to users that the error happened in the validation step - because the error happens right after the line: `Validating schema of 'results/nt_muts.json'...`, that should probably start with `INFO:` or otherwise be separated better.

Would be good if the docs for `augur clades` command linked to: https://docs.nextstrain.org/projects/augur/en/stable/faq/clades.html#labeling-clades

**Comment by Wen1953** [comment]
I have the same problem running nextstrain clades:

augur clades --tree refine_tree.nwk --mutations ancestral.json translate.json --output-node-data clades.json
Validating schema of 'ancestral.json'...
Validating schema of 'translate.json'...
Traceback (most recent call last):
  File "/home/veronica/miniconda3/lib/python3.9/site-packages/augur/__init__.py", line 67, in run
    return args.__command__.run(args)
  File "/home/veronica/miniconda3/lib/python3.9/site-packages/augur/clades.py", line 280, in run
    clade_designations = read_in_clade_definitions(args.clades)
  File "/home/veronica/miniconda3/lib/python3.9/site-packages/augur/clades.py", line 51, in read_in_clade_definitions
    sep='\t' if clade_file.endswith('.tsv') else ',',
AttributeError: 'NoneType' object has no attribute 'endswith'

I'm using https://docs.nextstrain.org/projects/augur/en/stable/faq/clades.html#labeling-clades as reference but it doesn't work. @jameshadfield @corneliusroemer some idea?

**Comment by jameshadfield** [comment]
@Wen1953 - you are missing the clades TSV definition file in your call to `augur clades`. (PR #1199 will make this error clearer.)

**Comment by Wen1953** [comment]
Thanks @jameshadfield. It works!
I follow this instruction to construct TSV format > https://docs.nextstrain.org/projects/augur/en/stable/faq/clades.html#labeling-clades
