### ISSUE TITLE
NO VALID SITES REMAIN AFTER IGNORING UNCALLED SITES

### ISSUE THREAD

**Issue by BaiRouYa** [nextstrain/augur#1198]
### Current Behavior

```
ERROR: NO VALID SITES REMAIN AFTER IGNORING UNCALLED SITES
Traceback (most recent call last):
  File "/nextstrain/augur/augur/__init__.py", line 67, in run
    return args.__command__.run(args)
  File "/nextstrain/augur/augur/tree.py", line 469, in run
    variable_fasta = write_out_informative_fasta(compress_seq, args.alignment, stripFile=args.exclude_sites)
  File "/nextstrain/augur/augur/tree.py", line 347, in write_out_informative_fasta
    raise Exception
Exception

An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>
```

### How to reproduce
1. git clone https://github.com/nextstrain/tb
cd tb

2. Prepare my own Sequences: vcf file, metadata, reference fasta file.

3. Masking my own vcf file with the mask file tb tutorial provided.
My vcf file only has 3 samples.

```
augur mask --sequences data/core.vcf \
            --mask config/Locus_to_exclude_Mtb.bed \
            --output results/masked.vcf


Skipped row 1 of config/Locus_to_exclude_Mtb.bed, assuming it is a header.
488624 masking sites read from config/Locus_to_exclude_Mtb.bed
Removing masked sites from VCF file using vcftools... this may take some time. Call:
vcftools --exclude-positions data/core.vcf_maskTemp --vcf data/core.vcf --recode --stdout  > results/masked.vcf
```

4. Construct an Initial Tree to Get the Topology 
```
augur tree --alignment results/masked.vcf \
           --vcf-reference data/ref.fa \
           --method 'iqtree' \
           --exclude-sites config/drm_sites.txt \
          --output results/tree_raw.nwk

162 masking sites read from config/drm_sites.txt
ERROR: NO VALID SITES REMAIN AFTER IGNORING UNCALLED SITES
Traceback (most recent call last):
  File "/nextstrain/augur/augur/__init__.py", line 67, in run
    return args.__command__.run(args)
  File "/nextstrain/augur/augur/tree.py", line 469, in run
    variable_fasta = write_out_informative_fasta(compress_seq, args.alignment, stripFile=args.exclude_sites)
  File "/nextstrain/augur/augur/tree.py", line 347, in write_out_informative_fasta
    raise Exception
Exception


An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>
```

### Your environment: if running Nextstrain locally
 - Operating system: Ubuntu
 - Browser: Google Chrome
 - Version: augur 21.0.0

### Additional context
I downloaded your workflow repository from "Creating a bacterial pathogen workflow" but I use my own vcf file, and metadata, and I did fix something in the Snakefile.
There are only 3 samples in my vcf file. Would it be a problem?

**Comment by mikal16** [comment]
I am also having a very similar issue. My code seemed to be running fine 2 months ago, but I am getting this issue when running augur tree with my VCF files. Was just wondering if this issue was solved or maybe I'm missing something here?

Thanks a lot in advance!

Mikal

**Comment by jameshadfield** [comment]
I've just run the TB pipeline without any issues:

```
$ augur --version
augur 21.1.0
$ git rev-parse HEAD
f3a76a2fe8339af6120e245c090ffc138ef6678f
$ snakemake --cores 1 -pf auspice/tb.json
...
[Mon Apr 17 16:13:20 2023]
Finished job 0.
11 of 11 steps (100%) done
```

which leads me to believe this is related to your samples and/or masking files. That particular error arises when the sequences (after masking) are all identical (note that `N` or `-` characters are ignored for this definition of identical). If this doesn't help pinpoint the issue, it would help us debug things if you were able to share the files used by `augur tree`, although I realise this may not be possible if the data's sensitive.

**Comment by mikal16** [comment]
I see, I think my issue may be with my VCF file. The only thing is, I've been generating my VCF files using bcftools call (bcftools call -m -Ov -o ) for a while and then running augur tree with no problem at all. After the variant calling step, I merge several samples (each it's own VCF) into one VCF file using vcf-merge and then that's when I run augur tree. When I'm running augur tree using that VCF file I'm getting this error, which says  "ERROR: File not found or incorrect input, pls check it again.iqtree". 

<img width="826" alt="Screen Shot 2023-04-17 at 1 37 13 AM" src="https://user-images.githubusercontent.com/66184173/232393516-48bfcc47-4ba8-485a-9688-449ad4f303d9.png">


Another error I have also gotten, but I can't seem to recreate it is the one below:

<img width="755" alt="Screen Shot 2023-04-16 at 6 57 54 AM" src="https://user-images.githubusercontent.com/66184173/232393549-afb54083-c86a-4d86-b234-d0e5da847495.png">


So something seems for sure off with my VCF file, but I can't seem to figure out what's going on.

I tried attaching my VCF here, but github doesn't seem to support it, would I be able to email it to you by any chance?

Thanks a ton for the help in advance!

Mikal

**Comment by mikal16** [comment]
Hi there, 

So, I've simplified my issue and attached a csv file version of my vcf file.

[test_run.csv](https://github.com/nextstrain/augur/files/11257651/test_run.csv)

The major problem I'm having here is that when I try running augur-tree with my VCF with data from a number of different samples, I'm not getting any errors when using raxml or fasttree, however my tree looks very odd and I can't seem to understand why. 

<img width="1421" alt="Screen Shot 2023-04-17 at 11 38 15 PM" src="https://user-images.githubusercontent.com/66184173/232664876-a3a3c4f2-278c-4f7d-9f43-f56c3e1c83b6.png">

Previously, I've used --method iqtree with augur tree, but when I try using iqtree it stalls the running of the tree and never completes the run:
<img width="949" alt="Screen Shot 2023-04-17 at 11 39 35 PM" src="https://user-images.githubusercontent.com/66184173/232665056-f1dd1459-43cf-4c5d-aac7-a484c83fd36e.png">

Any insight would be really appreciated!

Thanks a ton in advance,

Mikal

**Comment by jameshadfield** [comment]
> however my tree looks very odd and I can't seem to understand why.

That looks like the very-long strain names are taking up the entire display and obscuring the tree. Can you try changing the "tip label" dropdown to "None" and this should bring up the tree. 

More generally, Augur 24.0.0 includes improved VCF support. If you are still getting these issues please re-open this comment and I'll help debug.
