### ISSUE TITLE
DOC(parse): No useful error when no `--fields` passed, required args not documented

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1222]
### Current Behavior
Just tried out `parse` for first time. It seems certain args, like `--fields` are required, but this doesn't seem to be [documented](https://docs.nextstrain.org/projects/augur/en/stable/usage/cli/parse.html), and neither is a helpful error thrown:

### Expected behavior
Helpful error given to user

### Example

```
zstdcat data/gisaid.fasta.zst |  augur parse --sequences /dev/stdin  --output-sequences /dev/stdout | zstd > data/gisaid_parsed.fasta.zst
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/augur/parse.py", line 165, in run
    if 'name' in args.fields:
TypeError: argument of type 'NoneType' is not iterable


An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>
```

Besides `--fields`, also `--output-metadata`, `--output-sequences` and `--sequences` seem to be required (plus possibly more)

**Comment by huddlej** [comment]
Agreed that we should make `--fields`, `--output-metadata`, and `--output-sequences` required args.
