### ISSUE TITLE
Allow selection of metadata ID column

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#1237]
A number of augur commands perform linkage between input sequences (FASTA, sometimes VCF) and metadata via a column in the metadata.

The default columns are (only the first found column will be used):
https://github.com/nextstrain/augur/blob/713959584415da21d414702fc849c1dbbf27afb3/augur/io/metadata.py#L18

Augur filter has the ability to modify this, but other augur commands do not:
https://github.com/nextstrain/augur/blob/713959584415da21d414702fc849c1dbbf27afb3/augur/filter/__init__.py#L21

We should add this ability to all applicable augur commands - [export v2, refine, frequencies](https://github.com/search?q=repo%3Anextstrain%2Faugur+read_metadata%28&type=code). There may be others? We don't need to add it to `export v1`. 

This will allow us to simplify workflows such as [monkeypox](https://github.com/nextstrain/monkeypox/blob/master/workflow/snakemake_rules/core.smk#L16-L27), dengue and RSV which use accession as the sequence identifier.

**Comment by victorlin** [comment]
> @jameshadfield: This will allow us to simplify workflows such as [monkeypox](https://github.com/nextstrain/monkeypox/blob/master/workflow/snakemake_rules/core.smk#L16-L27), dengue and RSV which use accession as the sequence identifier.

I created PRs for monkeypox and RSV. I don't see any references in dengue, so no PR there.

**Comment by jameshadfield** [comment]
> I created PRs for monkeypox and RSV. I don't see any references in dengue, so no PR there.

Thanks! The dengue work is [happening on a branch](https://github.com/nextstrain/dengue/pull/6) so I'll let @j23414 update that as desired 😄
