### ISSUE TITLE
export v2: metadata ID column not used if `strain` column already exists in the metadata

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/augur#1262]
Reviewing https://github.com/nextstrain/augur/pull/1261 and the related https://github.com/nextstrain/monkeypox/pull/161 made me realize that `augur export v2` does not use the provided metadata ID column if "strain" already exists as a column in the metadata. 

Looking at the outputs of the [monkeypox CI run for the PR](https://github.com/nextstrain/monkeypox/actions/runs/5650966637), when the "strain" and "accession" columns have different values, the final Auspice JSON will be missing attributes from the metadata. For example, the sequence `MPXV_USA_2022_FL001` is missing "region", "country" and "host" attributes even though they are available in the [example metadata.tsv](https://github.com/nextstrain/monkeypox/blob/master/example_data/metadata.tsv#L35)

---

The issue comes from how `export v2` adds metadata to the tree `node_attrs`.

The metadata gets added using the hard-coded `strain` field 
https://github.com/nextstrain/augur/blob/9ef471129fc048f596952af5cbee4cd87feac20b/augur/export_v2.py#L1018-L1024

However, the metadata ID column only gets assigned to the `strain` field if `strain` does not already exist in the metadata
https://github.com/nextstrain/augur/blob/9ef471129fc048f596952af5cbee4cd87feac20b/augur/export_v2.py#L1081-L1083

---

Potential fix: https://github.com/nextstrain/augur/commit/974127944bef18dd16dd4203ff832724479f12d8

**Comment by jameshadfield** [comment]
This bug is also present in `augur export v1`. I don't think we should be backporting improvements there, so I would favor removing `--metadata-id-columns` from `v1` rather than fixing the bug. In fact, I think we should put it on the roadmap to remove `augur export v1` entirely, and then ~symlink `augur export` to `augur export v2`.

**Comment by victorlin** [comment]
@jameshadfield re: `export v1`, see #1266.
