### ISSUE TITLE
export v2: Add option to choose sample name from metadata

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/augur#1264]
### Context
Since https://github.com/nextstrain/augur/pull/1240, we support using arbitrary columns as the metadata ID column.
This column is then used as the sample `name` in the final output Auspice JSON. 

### Description
It would be nice to be able to choose a different column from the metadata to use as the sample name. 
The column used as the metadata ID may not be descriptive enough to use as the sample name for display in Auspice. 

### Examples
We already do this in basically identical scripts for [monkeypox](https://github.com/nextstrain/monkeypox/blob/5c461dc7e90cd70c1f16b193f82fd1666d4c95e2/scripts/set_final_strain_name.py) and [rsv](https://github.com/nextstrain/rsv/blob/ba171f4a43110382c38b6154be3febd50408d7bf/scripts/set_final_strain_name.py).

**Comment by jameshadfield** [comment]
See https://github.com/nextstrain/auspice/pull/1668 for an alternative solution

**Comment by joverlee521** [comment]
@jameshadfield Ah nice! I totally missed that PR! 

Then we would need to add `tip_label` as an allowed property for `display_defaults` in our [auspice config schema](https://github.com/nextstrain/augur/blob/9ef471129fc048f596952af5cbee4cd87feac20b/augur/data/schema-auspice-config-v2.json#L157). 

I also think `export v2` should verify the `tip_label` field is an available `node_attr` or automatically add it as a `node_attr` if the field is available in the metadata file.

**Comment by jameshadfield** [comment]
Great suggestions -- I think that Auspice PR needs more testing & feedback before we use it, but I think it's ultimately a better direction than swapping back in the strain name (as monkeypox + rsv do) because of how duplicate node names are handled in Auspice.

**Comment by joverlee521** [comment]
Closing since the alternative solution in Auspice has been released.
