### ISSUE TITLE
H7N9 build fails

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#13]
H7N9 build is currently failing for me. The fault occurs during [RAxML branch length estimation](https://github.com/nextstrain/augur/blob/master/base/tree.py#L126):

```
RAxML was called as follows:

raxml -f e -T 2 -s temp.phyx -n branches -c 25 -m GTRGAMMA -p 344312987 -t raxml_tree.newick 


RAxML expects to read a taxon label in the tree file
but the taxon label is an empty string.

RAxML will print the context of the error and then exit:

/1051:0.00060,(((((:0.00055,(A/GD-103/20
```

Here, the input tree `raxml_tree.newick` is poorly formatted. An entire taxon label has been dropped (as above). At fault then, is the [previous RAxML command to build the tree topology](https://github.com/nextstrain/augur/blob/master/base/tree.py#L104).

**Comment by rneher** [comment]
I vaguely remember such issues in the past. could have been due to illegal characters in taxon names, number only names etc.

**Comment by jameshadfield** [comment]
Working (locally) using

`raxmlHPC-PTHREADS-SSE3 -f d -T 2 -N 3 -m GTRCAT -c 25 -p 235813 -n ... -s ...`

without optimising branch lengths etc. I'd be tempted to drop the optimisation step from augur. Thoughts?

**Comment by rneher** [comment]
yes, we can skip the branch length part. treetime redoes those anyway.

**Comment by jameshadfield** [comment]
For the time being this has been done in branch `avian`, commit 212511d8052c280c8ca81602d79f9745cabe7cf7
It requires testing with other flu / zika / ebola scripts before merging into master

**Comment by jameshadfield** [comment]
working on branch `rejig`
