### ISSUE TITLE
test failure beyond pandas 2.0

### ISSUE THREAD

**Issue by emollier** [nextstrain/augur#1303]
### Current Behavior
As initially identified in [Debian bug#1044079], augur up to version 22.4.0 fails one test item with pandas 2.0.3 available in Debian experimental, while the test item passes with pandas 1.5.3 in Debian unstable.

The failure is the following:
```
=================================== FAILURES ===================================
___________________________ TestParse.test_fix_dates ___________________________

self = <test_parse.TestParse object at 0x7f32feb89b10>
capsys = <_pytest.capture.CaptureFixture object at 0x7f32fe8f7750>

    def test_fix_dates(self, capsys):
        full_date = "4-5-2020"
>       assert parse.fix_dates(full_date) == "2020-05-04"

tests/test_parse.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

d = '4-5-2020', dayfirst = True

    def fix_dates(d, dayfirst=True):
        '''
        attempt to parse a date string using pandas date parser. If ambiguous,
        the argument 'dayfirst' determines whether month or day is assumed to be
        the first field. Incomplete dates will be padded with XX.
        On failure to parse the date, the function will return the input.
        '''
        try:
            from pandas.core.tools.datetimes import parsing
>           results = parsing.parse_time_string(d, dayfirst=dayfirst)
E           AttributeError: module 'pandas._libs.tslibs.parsing' has no attribute 'parse_time_string'

augur/parse.py:33: AttributeError
```

[Debian bug#1044079]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1044079

### Expected behavior
I would expect all augur test items to pass with the newer pandas version.

### How to reproduce
Steps to reproduce the current behavior:
1. Upgrade the python3 module pandas to version 2.0.3 or later.
2. Run the test suite with e.g. `python3 -m pytest`
3. See error

### Your environment: if running Nextstrain locally
 - Operating system: Debian unstable
 - Browser: N/A
 - Version (e.g. `auspice 2.7.0`): N/A

### Additional context
The test failure is caught as part of the packaging effort around augur in Debian.

**Comment by victorlin** [comment]
Hi @emollier, thanks for sending this report.

We currently [pin pandas to 1.x](https://github.com/nextstrain/augur/blob/934fdf49f21a0722c889772efbfb0e0fdfb7d92e/setup.py#L62) and do the same for many other dependencies. This is to avoid problems like the failure you've encountered.

I noticed that [the Debian package](https://packages.debian.org/bookworm/augur) does not apply these pins. I'd recommend mirroring them over there and checking for any dependency changes in setup.py on every new version. This is what we do for [Augur's Bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/augur/meta.yaml) which is a similar effort.
