### ISSUE TITLE
export: Automatically minify JSON

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1331]
_proposed by @tsibley [on Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1698944692720619)_

## Context

Currently, JSON minification is opt-in with the `--minify-json` option. However, it is not uncommon for large-scale analyses to have thousands of tips resulting in a dataset file that takes significantly more time to load compared to a minified version.

## Related issues

- https://github.com/nextstrain/auspice/issues/1622
- Other discussions and emails from users that have been affected by large Auspice JSONs

## Proposed solution

Make JSON minification the default behavior for anything >1000 tips (threshold used by @trvrb's [example on Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1698947110088169?thread_ts=1698944692.720619&cid=C01LCTT7JNN)). This allows smaller JSONs (which don't gain much performance benefit with minification) to be in the indented, human-readable format.

**Comment by corneliusroemer** [comment]
I support minification by default. Should we offer an option for pretty printing or is that unnecessary as one can simply use `jq '.'` or similar to do so?

**Comment by tsibley** [comment]
@corneliusroemer Yeah, that would be the (new) `--no-minify-json` option to disable minification. Discussed in the linked Slack thread, but not noted here.

**Comment by victorlin** [comment]
Implemented in Augur version [24.0.0](https://github.com/nextstrain/augur/blob/24.0.0/CHANGES.md):

> export v2: Automatically minify large outputs. Use `--no-minify-json` to disable this default behavior.
