### ISSUE TITLE
IQtree 2.2.3 errors with SIGSEGV when analyzing 130k SARS-CoV-2 seqs

### ISSUE THREAD

**Issue by NikitaSitharam** [nextstrain/augur#1338]
### Current Behavior

I am attempting to run the ncov workflow using custom data I curated from the full GISAID database (https://docs.nextstrain.org/projects/ncov/en/latest/guides/data-prep/gisaid-full.html).

_This job produces the error message below:_
Job 5: Building tree
Reason: Missing output files: results/custom-build/tree_raw.nwk; Updated input files: results/custom-build/filtered.fasta

_Error message:_
ERROR: Shell exited from fatal signal SIGSEGV when running: iqtree2 -ntmax 8 -s results/custom-build/masked_filtered-delim.fasta -m GTR -ninit 2 -n 2 -me 0.05 -nt AUTO -redo -ninit 10 -n 4 > results/custom-build/masked_filtered-delim.iqtree.log
Command output was:
  OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
  /bin/bash: line 1:  1679 Segmentation fault: 11  iqtree2 -ntmax 8 -s results/custom-build/masked_filtered-delim.fasta -m GTR -ninit 2 -n 2 -me 0.05 -nt AUTO -redo -ninit 10 -n 4 > results/custom-build/masked_filtered-delim.iqtree.log

7 masking sites read from defaults/sites_ignored_for_tree_topology.txt
Building a tree via:
	iqtree2 -ntmax 8 -s results/custom-build/masked_filtered-delim.fasta -m GTR -ninit 2 -n 2 -me 0.05 -nt AUTO -redo -ninit 10 -n 4 > results/custom-build/masked_filtered-delim.iqtree.log
	Nguyen et al: IQ-TREE: A fast and effective stochastic algorithm for estimating maximum likelihood phylogenies.
	Mol. Biol. Evol., 32:268-274. https://doi.org/10.1093/molbev/msu300

ERROR: TREE BUILDING FAILED
ERROR: Command '['/bin/bash', '-c', 'set -euo pipefail; iqtree2 -ntmax 8 -s results/custom-build/masked_filtered-delim.fasta -m GTR -ninit 2 -n 2 -me 0.05 -nt AUTO -redo -ninit 10 -n 4 > results/custom-build/masked_filtered-delim.iqtree.log']' returned non-zero exit status 139.
Please see the log file for more details: results/custom-build/masked_filtered-delim.iqtree.log

Building original tree took 660.5297021865845 seconds

### Expected behavior

I have run the ncov workflow with custom data and genomic surveillance data before, with no issue. I am unsure why I am receiving this error.

### How to reproduce
Steps to reproduce the current behavior:

1. nextstrain build . --configfile ncov-analyses/custom-data.yaml
Where I have provided the inputs for the metadata and sequence files.
2. Runs jobs with no errors.
3. Until it reaches job 5.

### Your environment: if browsing Nextstrain online
 - Operating system: -
 - Browser: -

### Your environment: if running Nextstrain locally
 - Operating system: macOS
 - Browser: Chrome
 - Version (e.g. `auspice 2.7.0`): augur 23.0.0
 
[masked_filtered-delim.iqtree.log](https://github.com/nextstrain/augur/files/13365961/masked_filtered-delim.iqtree.log)

**Comment by corneliusroemer** [comment]
Hi Nikita, thanks for making an issue! This looks like a segmentation fault in IQtree, which is quite likely not something we can do much about from within Augur.

I have a few followup questions:

1. When you rerun the command, do you get the same error again? Or does it appear only sometimes?
2. Please copy/paste the output of the terminal command `nextstrain version --verbose` [This tells us how you are using `nextstrain` and `augur` and what the versions are of important Nextstrain components]
3. Please enter the nextstrain shell as follows: type `nextstrain shell .` into the terminal, then inside that shell type `iqtree --version` and copy/paste the output you get into here. [This tells us the versions of IQtree used]

This may end up an issue for: https://github.com/iqtree/iqtree2/issues

**Comment by corneliusroemer** [comment]
Someone else reported a segmentation fault in version 2.2.5 here: https://github.com/iqtree/iqtree2/issues/145

Previous issues:
- https://github.com/nextstrain/augur/issues/1338
- https://github.com/nextstrain/augur/issues/780

**Comment by NikitaSitharam** [comment]
Hi Cornelius,

Oops! That makes sense, thank you so much!
