### ISSUE TITLE
[translate] GFFs + node-data input produce invalid output

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#1346]
### Current Behavior
GFF references used by `augur translate` do not have the nuc (~genome) coordinates parsed, and thus are not exported as part of the node-data file's annotations when the input `--ancestral-sequences` is a node-data JSON. Thus, the node-data file doesn't conform to [our schema](https://github.com/nextstrain/augur/blob/master/augur/data/schema-annotations.json) and fails validation.

### Expected behavior

Export a "nuc" definition in the annotations block so that the node data JSON is valid.

### Possible solution
The provided node-data JSON will have the annotation→nuc entry, so we can just re-export this. For completeness this can be checked against the GFFs `##sequence-region` pragma or the "region" feature (if they exist).

### Your environment: if running Nextstrain locally
augur 23.1.1

**Comment by huddlej** [comment]
I ran into this issue recently, too, and noticed that “nuc” feature only gets loaded properly from a GFF by `load_features` [when it appears as a line in the GFF file with a type of “source”](https://github.com/nextstrain/augur/blob/9839199f8396466ad346bcc84a5149544d7380e2/augur/utils.py#L181-L182). For example, the mpox workflow uses `augur translate` with [a GFF file that includes a “source” entry for the full nucleotide sequence](https://github.com/nextstrain/mpox/blob/9ff822f31f513ba25ee28ef84ed9a708859d5c59/phylogenetic/config/genemap.gff#L5).

Adding a "source" entry to the GFF solved the problem for me then, but I agree that it could be nicer to just pull the existing `nuc` entry from the input nt muts JSON. I wish we generally looked for the nucleotide range in the `##sequence-region` pragma, but I don't see that being defined consistently across pathogens...

**Comment by corneliusroemer** [comment]
In general, it's best to allow gffs that come straight from genbank to work - adding source is a workaround that's not ideal but it's what I've been doing when necessary.

**Comment by jameshadfield** [comment]
Source isn't a valid GFF ID¹, I think we've just been applying the INSDC/GenBank term to GFF files. 

¹ GFF types (what we call features / feature names) [must be a term from the Sequence Ontology](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md), and 'source' isn't one according to [their browser](http://www.sequenceontology.org/browser/current_release/term/SO:0002206)
