### ISSUE TITLE
`export` crashes with `KeyError: 'tree'` when jsonschema v4 is installed

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1358]
## Description

Augur pins jsonschema to version 3 in [setup.py](https://github.com/nextstrain/augur/blob/5d04da22723a308069b8b0ea457beb3f212b5e67/setup.py#L60) and [Bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/4a799838b65e7d7237f5db199fe930c5513eb2cb/recipes/augur/meta.yaml#L31) as current code does not work with jsonschema version 4.

Despite those declared version constraints, we've had numerous reports from users ending up with jsonschema version 4 and running into errors. This can happen in a Conda environment if Augur is first installed through Bioconda then other Python packages are installed using `pip`. If the Python package requested depends on jsonschema somewhere in the dependency tree, `pip` ignores Biopython version constraints and will resolve to the latest version of jsonschema supported by the dependency tree.

This is not a great experience for users who are managing their own environments and do something like `pip install jupyter` (not uncommon for our users), then run into the cryptic error below.

### `KeyError: 'tree'`

```
Validating schema of 'auspice/tb.json'...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jsonschema/validators.py", line 1153, in resolve_fragment
    document = document[part]
KeyError: 'tree'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
…
jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer: '$defs/tree'
An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>
```

### Deprecations

```
+  DEPRECATED: jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
+  
+  DEPRECATED: Accessing Draft6Validator.resolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization.
```

## User workarounds

1. Install jsonschema version 3
2. Set up a non-ambient Nextstrain runtime (instructions on [Nextstrain install](https://docs.nextstrain.org/en/latest/install.html))

## Developer solutions

1. (quick fix) Check jsonschema version during runtime ([ref](https://github.com/nextstrain/augur/issues/1358#issuecomment-2113161430))
2. (proper solution) Update Augur to support jsonschema version 4

**Comment by tsibley** [comment]
Yep. [I suggested the newer APIs](https://github.com/nextstrain/augur/pull/1281#discussion_r1298856930) in the work which added the older API usage.

**Comment by victorlin** [comment]
It's worth noting that installation of other packages in the same environment can pull in `jsonschema>4`. Looks like pip doesn't prevent that from happening. Example:

```
$ micromamba install -c conda-forge python=3.9

$ pip install nextstrain-augur

$ pip list | grep jsonschema
jsonschema          3.2.0

$ pip install "latch[snakemake]"==2.37.1
…
Collecting jsonschema>=4.5.1 (from lytekit==0.15.3->latch==2.37.1->latch[snakemake]==2.37.1)
  Using cached jsonschema-4.21.1-py3-none-any.whl.metadata (7.8 kB)
…
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nextstrain-augur 24.0.0 requires jsonschema==3.*,>=3.0.0, but you have jsonschema 4.21.1 which is incompatible.
Successfully installed …
```

I've seen this happen a few times recently, with Latch in the example above and today in an [internal Slack thread](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1706031477283689). Both scenarios were surfaced to devs because they resulted in an error, not just a deprecation warning:

```
Validating schema of 'auspice/tb.json'...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jsonschema/validators.py", line 1153, in resolve_fragment
    document = document[part]
KeyError: 'tree'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
…
jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer: '$defs/tree'
An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>
```

**Comment by corneliusroemer** [comment]
Yep I've also gotten errors in the past but I didn't mention them here because I thought it was "user error" - i.e. if I were to use the official nextstrain environments and not custom install various things I would not have encountered the error.

And technically, there's nothing wrong with saying we have a certain version requirement. That pip ignores it is a pip bug more than an augur bug ;)

But agreed that it'd be good to move to v4, after all I made this issue :)

**Comment by victorlin** [comment]
Agreed that this is not an Augur bug! While it would be nice to have everyone use the official Nextstrain environments (managed runtimes), in practice we have many users (both internal and external) that custom install things and will face this error. With the error messages alone, it's easy to think that something is wrong with the file or Augur's code, though in the end it's just due to having a newer version of `jsonschema` installed, which most likely got installed as a dependency of something completely unrelated.

**Comment by victorlin** [comment]
[On Slack](https://bedfordlab.slack.com/archives/C0K3GS3J8/p1708902932013319), @jameshadfield and @joverlee521 uncovered that `pip list` / `pip show` is not a good indicator of what version of `jsonschema` is used by Augur due to potential interference by another package manager like Conda. The proper way to inspect the version is to check with the Python interpreter directly:

```
python -c 'import jsonschema; from importlib import metadata; print(jsonschema.__path__, "VERSION", metadata.version("jsonschema"))'
```

**Comment by victorlin** [comment]
This was brought up again on [Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1714743557515229?thread_ts=1706031477.283689&cid=C01LCTT7JNN) - seems like `pip install juypter` also resolves to `jsonschema` v4 which breaks Augur.

**Comment by victorlin** [comment]
This was reported again in #1461. I've updated the issue with a more comprehensive description and workarounds.

**Comment by genehack** [comment]
> ```
> python -c 'from importlib import metadata; print(metadata.version("jsonschema"))'
> ```

I wonder if a quick-and-dirty improvement here (until the work can be done to update to the new API) would be to version-detect `jsonschema` when `augur` is starting up, and throw an informative error message when `jsonschema` v4 is detected?

**Comment by victorlin** [comment]
> I wonder if a quick-and-dirty improvement here (until the work can be done to update to the new API) would be to version-detect `jsonschema` when `augur` is starting up, and throw an informative error message when `jsonschema` v4 is detected?

Added as a solution in the issue description.

**Comment by huddlej** [comment]
I just ran into this issue, too, trying to run `augur export v2` from a Docker image that extends the Nextstrain base image as follows:

```dockerfile
FROM nextstrain/base

RUN pip3 install seaborn notebook altair[all] \
 && rm -rf ~/.cache
```

Another realistic (not ideal) user workaround is to add `--skip-validation` to their `augur export v2` command which is what I just did.

+1 for supporting version 4 of jsonschema, though.

**Comment by victorlin** [comment]
I'll take a look at upgrading jsonschema usage to work with v4. If it's easy, we should just do it. If it's difficult and requires extensive testing, I think the comprehensive quick-and-dirty improvement is to detect jsonschema v4 and error with a suggestion to re-run with `--skip-validation` as an easy workaround.

**Comment by huddlej** [comment]
Thank you, @victorlin!
