### ISSUE TITLE
Unable to run augur filter step

### ISSUE THREAD

**Issue by swantan** [nextstrain/augur#1359]
### Current Behavior
I have a set of flu H3N2 sequences for a period of 10 years, which is about 28k sequences. I wanted to build a Nextstrain instance locally and keep getting this error when running augur filter step - "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 434: invalid start byte". I have successfully running this step with other data besides flu. So I have no idea where is this issue coming from.

### Expected behavior
Expected to run the filtering step with an output 'filtered.fasta' 

### How to reproduce
Steps to reproduce the current behavior:
1. Run
augur filter     --sequences data/flu_H3N2_sequences.fasta     --sequence-index results/sequence_index.tsv     --metadata data/metadata.tsv     --exclude config/dropped_strains_v2.txt     --output results/filtered.fasta
2. See error
Traceback (most recent call last):
  File "/Users/stan1/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
  File "/Users/stan1/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/augur/filter/__init__.py", line 97, in run
    return _run(args)
  File "/Users/stan1/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/augur/filter/_run.py", line 167, in run
    metadata_reader = read_metadata(
  File "/Users/stan1/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/augur/io/metadata.py", line 79, in read_metadata
    "sep": _get_delimiter(metadata_file, delimiters),
  File "/Users/stan1/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/augur/io/metadata.py", line 462, in _get_delimiter
    return csv.Sniffer().sniff(file.readline(), valid_delimiters).delimiter
  File "/Users/stan1/.nextstrain/runtimes/conda/env/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 434: invalid start byte

### Possible solution
(optional)

### Your environment: if browsing Nextstrain online
 - Operating system: Mac OS
 - Browser: Chrome

### Your environment: if running Nextstrain locally
 - Operating system: Mac OS terminal
 - Version (e.g. `auspice 2.7.0`): augur 22.0.2

**Comment by victorlin** [comment]
Hi @swantan, this looks like an issue with some text in your metadata file. Are you able to share your `data/metadata.tsv` so we can investigate?

**Comment by jameshadfield** [comment]
My guess is that your metadata is Windows-1252 encoded. Was it exported from Excel perhaps? I'd try re-exporting that file (from the program you used to create/edit it) ensuring that the encoding is utf-8.

**Comment by swantan** [comment]
Hi @victorlin and @jameshadfield, thank you for your comments and advice! I figured out what's going on with my metadata and the exact rows that give the error. Yes, it has a few rows with weird character like ã and ï. Again, thank your for your response. Much appreciate!

**Comment by victorlin** [comment]
@swantan glad to hear it's working now! Did you re-export with UTF-8 encoding or remove those characters? I just checked and `augur filter` works fine with metadata that has `ã` and `ï`, as long as it is UTF-8 encoded.

**Comment by swantan** [comment]
Thanks @victorlin! That's good to know. But I found that my metadata file was not UTF-8 encoded. So, I just manually locate the rows and remove the characters.

**Comment by victorlin** [comment]
Ok, I suspect that this was solved by whatever program you used to remove the characters, rather than the act of removing the characters themselves. That is, if you add the characters back and save using the same program, it should work. Just in case that you want to try in the future!
