### ISSUE TITLE
[ancestral] writing VCF files is sloooooow

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#1378]
### Current Behaviour

Using an relatively small real-life bacterial VCF file (~800k variable sites, 100 samples) which is 175MB (3.9MB gzipped), running `augur ancestral` is quick except for the writing of a vcf file (`--output-vcf`) which is _very_ slow. Rough cumulative timings and (even rougher) rss memory usage at some stopping points within `augur ancestral`:

```
Tree in 113MB 0min
VCF / Fasta loaded 948MB 0min
TreeTime inference finished 1176MB 1min
JSON written 1094MB 1min
VCF written (program finished) 184MB 464min  --- that's nearly 8 hours! --- 
```

### Expected behavior
VCF writing should take under a minute for this example

### Your environment: if running Nextstrain locally
Running Augur from branch james/vcf and TreeTime from branch james/vcf

### Other info

For comparison, here is the same dataset run using FASTA inputs (and thus no VCF out). The fasta file is around 400MB.
```
Tree in 111MB 0min
VCF / Fasta loaded 120MB 0min
TreeTime inference finished 608MB 1min
JSON written (program finished) 1183MB 1min
```
For our aims of running bacterial genomes through Augur, the high memory usage of our VCF representation is going to be problematic, so we will need to address that in future work as well.

**Comment by victorlin** [comment]
I haven't run an example yet, but from quickly skimming the code, this is what I can gather:

1. The bulk of what happens with `--output-vcf` is handed by `treetime.vcf_utils.write_vcf`:
    https://github.com/nextstrain/augur/blob/ad4ed1baee2b6a10f794a484f721b2c94320e122/augur/ancestral.py#L388
2. That function has O(n³) complexity in the way it handles deletions ([src](https://github.com/neherlab/treetime/blob/9fdceaa5157fd0fd4bb141f45e1d742167e5d4c9/treetime/vcf_utils.py#L281C5-L281C5)):

    ```py
    while i < len(positions):
        # …
        i, pi, pos, refb, pattern = handleDeletions(i, pi, pos, ref, delete, pattern)

        # below is from handleDeletions
        while (i+1) < len(positions) and positions[i+1] == pi+1:
            # …
            for k,v in sequences.items():
                # …
    ```
