### ISSUE TITLE
export: Reduce memory footprint when determining whether to automatically minify output

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1385]
https://github.com/nextstrain/augur/blob/4ab823d851dce53d281cf14c8bfbfb12b814a69b/augur/utils.py#L131-L133

@tsibley noted in https://github.com/nextstrain/augur/pull/1352#discussion_r1445518822:

> As we normally serialize to JSON directly to a file handle, serializing here to a Python string (which we immediately throw away!) will dramatically increase the memory footprint of `augur export`...
> 
> I would not be surprised if this ends up breaking people's workflows...

**Comment by tsibley** [comment]
LMK if you want a suggestion for how to calculate the size more efficiently...

**Comment by victorlin** [comment]
@tsibley sure. I had found a "recursive sizeof recipe" ([working link](https://web.archive.org/web/20230228112838/https://code.activestate.com/recipes/577504/)) mentioned in the [docs](https://docs.python.org/dev/library/sys.html#sys.getsizeof) for `sys.getsizeof`, but haven't tried it yet. Let me know if you have a better suggestion.

**Comment by tsibley** [comment]
Ah, `sys.getsizeof()` is going to be about the in-memory size of the Python value, not its the JSON serialization.

My thought was to implement a small IO class looking something like this:

```python
class BytesWrittenCounterIO(RawIOBase):
    written = 0

    def write(self, data: bytes) -> int:
        n = len(data)
        self.written += n
        return n
```

and then pass an instance of it to `write_json()` (after refactoring that to accept a file handle not just a file name).
