### ISSUE TITLE
CI failing on new release with version related errors

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1395]
CI is [failing](https://github.com/nextstrain/augur/actions/runs/7629727026/job/20783802892) on `ancestral` and `translate` functional tests:

```
--- tests/functional/ancestral/cram/general.t
+++ tests/functional/ancestral/cram/general.t.err
@@ -21,7 +21,7 @@
   >   "$TESTDIR/../data/simple-genome/nt_muts.ref-seq.json" \
   >   "nt_muts.ref-seq.json" \
   >   --exclude-paths "root['meta']['updated']" 
-  {}
+  {'values_changed': {"root['generated_by']['version']": {'new_value': '24.0.0', 'old_value': '23.1.1'}}}
```

```
--- tests/functional/translate/cram/general.t
+++ tests/functional/translate/cram/general.t.err
@@ -15,12 +15,18 @@
   >  --ancestral-sequences "$ANC_DATA/nt_muts.ref-seq.json" \
   >  --reference-sequence "$DATA/reference.gff" \
   >  --output-node-data "aa_muts.json" > /dev/null
+  ERROR: Augur version incompatibility detected: the JSON /home/runner/work/augur/augur/tests/functional/translate/cram/../../ancestral/data/simple-genome/nt_muts.ref-seq.json was generated by {'program': 'augur', 'version': '23.1.1'}, which is incompatible with the current augur version (24.0.0). We suggest you rerun the pipeline using the current version of augur.
```

### Possible solutions

- For `ancestral`, use `diff_jsons.py --exclude-regex-paths` in the functional tests
- For `translate`, Implement the `--validation-mode` option and use `--validation-mode skip` in the functional tests

**Comment by jameshadfield** [comment]
Ahh this is on me, I thought I accounted for them via https://github.com/nextstrain/augur/pull/1355/commits/2cb2c6d4d242a2e1ab795bbc75d74489ce2f0683 but I've skipped one and also missed the fact that node data reading will enforce a version check. I can tackle this unless you've already begun?

**Comment by victorlin** [comment]
I put in ~1 minute of effort right before lab meeting: c151b5d71b6f97701e7959aa966a0e64b29db46a

Have you started? I don't mind continuing!
