### ISSUE TITLE
Ebola metadata?

### ISSUE THREAD

**Issue by jason-p-pickering** [nextstrain/augur#14]
Hi there. Looking here https://github.com/nextstrain/augur/blob/master/ebola/ebola.py#L117, it would seem that some metadata for Ebola is being imported and transformed. I tried to locate these source files in the repo, but they do not seem to be available.

**Comment by trvrb** [comment]
Sorry to never respond here @jason-p-pickering. Our Ebola dataset came directly from here: https://github.com/ebov/space-time/tree/master/Data.
