### ISSUE TITLE
augur tree vs augur unrooted

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#140]
Related to #133, but separate enough that I wanted a separate issue.

Some of my semantic confusion lies in `augur tree`. I think it could be easier for people to immediately understand what's happening if we renamed this to `augur unrooted`. In the Snakefile it would produce `tree_unrooted.nwk` instead of `tree_raw.nwk`.

I think this flags things more appropriately to say that this tree is not yet rooted. And then we can make it clear that the tree produced by `augur treetime` has been rooted. This should make the change in topology between `tree_raw.nwk` and `tree.nwk` less of a surprise.

**Comment by rneher** [comment]
as long as we don't expose `outgroup` options of iqtree or raxml, that would be consistent.

**Comment by trvrb** [comment]
Closing in favor of suggestion in #133 of `augur tree` + `augur refine`.
