### ISSUE TITLE
Running TB

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#141]
@emmahodcroft ---

Currently the only files in `builds/tb` are `Snakefile` and `data/config.json`. However, the snakefile refers to:
```
seq = "data/lee_2015.vcf.gz",
meta = "data/meta.tsv",
exclude = "data/dropped_strains.txt",
mask = "data/Locus_to_exclude_Mtb.bed",
ref = "data/ref.fasta",
drms = "data/DRMs.txt",
sites = "data/drm_sites.txt",
generef = "data/Mtb_H37Rv_NCBI_Annot.gff",
genes = "data/genes.txt",
colors = "data/color.tsv",
config = "data/config.json"
```
Could you commit all these files to the repo? Except perhaps `data/lee_2015.vcf.gz` (which you could share separately). I'd like to be able to test TB to make sure I'm not introducing breaking changes.

**Comment by emmahodcroft** [comment]
Yes, no problem. I've confirmed they're all public data, so can include them all. I'll add tomorrow morning.

**Comment by trvrb** [comment]
Great. Thanks @emmahodcroft!

**Comment by trvrb** [comment]
With Emma's commit 553f6a162ecf53f6d9f81c4aaeeb4b7a6bc51dc6 I'm now able to build TB locally.
