### ISSUE TITLE
pandas version

### ISSUE THREAD

**Issue by rneher** [nextstrain/augur#144]
why do we restrict pandas version to <0.18 (9d1b078418858f4ee72c66ed7012ec756c6f4372). 0.17 is >2y old and the current stable version is 0.23. any known incompatibilities @trvrb  @tsibley

**Comment by tsibley** [comment]
[pandas release notes](http://pandas.pydata.org/pandas-docs/stable/release.html) indicate 0.18 had breaking changes, and I did not audit 0.18's changes, or the breaking changes of even newer releases, against augur's usage of pandas. This may be me being over-conservative. It would be less conservative, but still reasonable, to set minimums that are known good and accept the possibility of breakage from new versions we haven't tried.

**Comment by rneher** [comment]
on various systems I had 0.19, 0.20, 0.21 installed. haven't run into any problems. I think minimum req are fine. If we are incompatible with latest numpy, scipy, pandas, we better find out about it sooner rather than later.

**Comment by trvrb** [comment]
I would say to upgrade pandas version across the board. Keep it the same for `fauna/requirements.txt`, `augur/requirement.txt` and `augur/setup.py`. And quickly confirm nothing breaking with upgrades. Would be nice to keep dependency versions consistent across components. Certainly makes `pip` installs easier.

**Comment by rneher** [comment]
I removed the upper bound in augur. we only use it to read csv....
