### ISSUE TITLE
Add versions, tags & --version cmd

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#146]
As we move builds into separate repositories, augur versioning becomes important. I imagine:
* https://stackoverflow.com/a/7071358 seems to imply this should be in `_version.py`
* Does every push to `master` bump up the version?
* We should tag each version so that it's easy to checkout certain versions
* `augur --version` should print the version
* a changelog would also be a good idea at this point
* I think we start from `3.0.0`

**Comment by tsibley** [comment]
I would recommend (naturally) the approach I took in https://github.com/nextstrain/cli:

* an `augur/__version__.py` that's simple enough to be statically parsed (for [release management tooling](https://github.com/nextstrain/cli/blob/master/devel/release))
* …but that can still be used to import a `__version__` variable at runtime (for a `--version` option or `version` subcommand to use).
* `setup.py` then gets [a snippet](https://github.com/nextstrain/cli/blob/master/setup.py#L8-L10) to read that file.

> Does every push to master bump up the version?

No. The version should be managed manually and follow [semantic versioning](https://semver.org) rules. Releases are things you version, not commits.

> We should tag each version so that it's easy to checkout certain versions

Yes, totally. Here's what I did for `nextstrain-cli`: https://github.com/nextstrain/cli/blob/master/devel/release

> `augur --version` should print the version

Yep, or `augur version`.

> a changelog would also be a good idea at this point

Yes!

> I think we start from 3.0.0

Sure.

**Comment by trvrb** [comment]
I endorse all of this.

**Comment by tsibley** [comment]
There's one bit of this that wasn't resolved by #210: a `--version` flag as an alias for `augur version`.  I'll do that soon.
