### ISSUE TITLE
Use PyPI's pyright?

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1468]
_continuing discussion from https://github.com/nextstrain/augur/pull/1246#discussion_r1604238438_

From that thread:

> @jameshadfield: How about adding this as a dev dependency in `setup.py` …

> @tsibley: The [`pyright` distribution on PyPI](https://pypi.org/project/pyright/) is unofficial and [all it does](https://github.com/RobertCraigie/pyright-python?tab=readme-ov-file#how-pyright-for-python-works) is set up Node and invoke npm behind the scenes to install the official NPM `pyright` distribution. It's still "crossing the streams", just behind your back.
> 
> It seems more straightforward and less prone to issues with Node envs to do this ourselves instead. I personally don't really see an issue with mixing package ecosystems/managers when they're disjoint.

This would apply to both Augur and [Nextstrain CLI](https://github.com/nextstrain/cli).

**Comment by genehack** [comment]
I had either not known or had repressed that pyright is only officially distributed via NPM; I withdraw any objection to installing it via that vector.

**Comment by victorlin** [comment]
Given the votes above, it seems like we have consensus to stick with using pyright like this:

https://github.com/nextstrain/augur/blob/e5ced1c8b5e1aeb1923bc00219594336e8ceeb34/tests/test_pyright.py#L8-L22
