### ISSUE TITLE
Multi Thread option (align) without SnakeMake

### ISSUE THREAD

**Issue by kiranpatil222** [nextstrain/augur#1477]
Hi,

I am using NextStarin on shell mode, as i am new to using snakemake 

Just wanted to know if there is an option to give --threads/cores so that to increase `augar align`

**Comment by jameshadfield** [comment]
Yes, you can run `augur align --nthreads X ...`. Run `augur align --help` to see all the options.

For Snakemake workflows we typically use the [threads directive](https://snakemake.readthedocs.io/en/stable/tutorial/advanced.html) 

P.S. I transferred this issue to the augur repo, the [nextstrain.org repo](https://github.com/nextstrain/nextstrain.org/) is specific to the code behind the [nextstrain.org website](https://nextstrain.org)

**Comment by kiranpatil222** [comment]
thank you
