### ISSUE TITLE
Augur mask should be able to take FASTA input

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#148]
Current `augur mask` only excepts VCF input. It should equally apply to FASTA input (in which case it replaces `ATGC` with `N`). Fortunately, I think the command line interface can stay exactly as is with a `--sequences` input and a `--ouput` output. If FASTA is given as input then FASTA should be given as output.

Not an immediate priority, but should exist for completeness.

**Comment by danielsoneg** [comment]
Per conversation in #72, I'm taking a look at this today
