### ISSUE TITLE
augur curate abbreviate-authors

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/augur#1483]
### Context 

As the command name states, this should abbreviate an authors list to `<first_author> et al.`

### Description

`augur curate abbreviate-authors` can start from [transform-authors from ingest](https://github.com/nextstrain/ingest/blob/main/transform-authors)

_Note_: I'm going with `abbreviate-authors` to be more explicit as `transform-authors` seems too vague.

**Comment by genehack** [comment]
> Note: I'm going with abbreviate-authors to be more explicit as transform-authors seems too vague.

There is a part of me that really wants to call this `abbrev-auths` ...but I will resist.
