### ISSUE TITLE
augur curate: Support Excel inputs

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/augur#1487]
### Context 

Previously mentioned in https://github.com/nextstrain/augur/pull/1039#issuecomment-1252912107 and https://github.com/nextstrain/augur/issues/1475. 

A lot of public health folks use Excel as their database and even GISAID/EpiFlu still only allows downloads of metadata as an xls file. Users often run into data parsing issues when converting Excel to TSV, so it seems like we can reduce a lot of this friction by supporting Excel as an input format for Augur commands. 

I think `augur curate` is at least a good place to start and we can add support for Excel across all other Augur commands later.

**Comment by tsibley** [comment]
Absolutely.

The long-standing standard Python packages for reading Excel files of all relevant vintages are `openpyxl` and `xlrd`. We could also use a promising looking new package, [`python-calamine`](https://pypi.org/project/python-calamine/), which binds to the Rust library `calamine`. I'd probably start with that and drop back to `openpyxl` + `xlrd` if we have issues with `calamine`.

If we need to [read Excel via Pandas](https://pandas.pydata.org/docs/user_guide/io.html#excel-files), e.g. in `augur.io.read_metadata()` outside of `augur curate`, we can configure it to use Calamine too.

**Comment by tsibley** [comment]
I wanted to try out Calamine a little, so I whipped up this after looking at the code briefly: https://gist.github.com/tsibley/5b088480ce778d238feebfb20db4515c

**Comment by tsibley** [comment]
@joverlee521 If you want, I can finish up that Excel patch. Or you can take it from there (or start from your own point).

**Comment by joverlee521** [comment]
> If you want, I can finish up that Excel patch.

@tsibley If you have the time, that would be much appreciated 🙏

**Comment by tsibley** [comment]
I'd love to have a set of example Excel files that we'd like to support. i.e. actual files used by actual folks. Do we have any of those I can collect into one place?

Since I haven't seen any examples so far, a question about functionality: do we need to support reading from arbitrary or multiple sheets in a single workbook (file)? My default inclination is to read only the first sheet as a simplification.

**Comment by tsibley** [comment]
There's [one example file from Louise](https://bedfordlab.slack.com/files/U3NTQPPJL/F042S6FNJS3/h5nx-gisaid-test2-2022-09-20.xls) (containing only a single row, though).

**Comment by joverlee521** [comment]
A couple examples off the top of my head:

 1. [GISAID metadata for seasonal flu](https://github.com/nextstrain/seasonal-flu/?tab=readme-ov-file#quickstart-with-gisaid-data), which is currently parsed with a custom [xls2csv.py](https://github.com/nextstrain/seasonal-flu/blob/master/scripts/xls2csv.py).

2. Example of private metadata used for mpox on [Slack](https://bedfordlab.slack.com/files/U1LUX6ULW/F074X8QH895/meatadata5.xlsx)

**Comment by joverlee521** [comment]
>  do we need to support reading from arbitrary or multiple sheets in a single workbook (file)?  My default inclination is to read only the first sheet as a simplification.

I agree starting with only first sheet makes sense, supporting arbitrary sheets can come later. A use case for parsing multiple sheets is to support parsing of seasonal flu titer data, but that's a whole other issue...

**Comment by tsibley** [comment]
> do we need to support reading from arbitrary or multiple sheets in a single workbook (file)? My default inclination is to read only the first sheet as a simplification.

Notably, the `xls2csv.py` program Jover linked to [only cares about the first sheet](https://github.com/nextstrain/seasonal-flu/blob/e2af9e6b51db6f55f65623e7f49842117f8df1d9/scripts/xls2csv.py#L15-L17) and the example from Louise and example from James both only have data in the first sheet.
