### ISSUE TITLE
augur curate I/O: verify NDJSON records have the same fields

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/augur#1510]
### Context

Originally discussed in https://github.com/nextstrain/augur/pull/1506#discussion_r1660441721

`augur curate` records can be output to a metadata TSV file, which uses the first record's fields as output columns. 

https://github.com/nextstrain/augur/blob/f6ee377336ec3813468fe641fa7910c14e54ced3/augur/io/metadata.py#L467-L474

With that in mind, the centralized inputs parser should verify that the input records all of the same fields. 
Then subcommands can operate under the assumption that all records should have the same fields and make changes accordingly.

**Comment by jameshadfield** [comment]
> the centralized inputs parser should verify that the input records all of the same fields

Probably sensible to do this for outputs too, to assert the curate subcommand's `run()` always returns a consistent set of fields. I haven't checked if `csv.DictWriter` orders each row based on the call to `writeheader()` or if it relies on the insertion order being the same for each row, but if it's the latter then we should assert that as well.

**Comment by jameshadfield** [comment]
Some more details about TSV writing:

* We don't need to worry about the order of TSV rows -- `DictWriter` will re-order each of them to match the header information provided in the set-up. 
* Fields missing from a row will be ignored (empty string used in their place). This is also [noted in our docstring](https://github.com/nextstrain/augur/blame/f6ee377336ec3813468fe641fa7910c14e54ced3/augur/io/metadata.py#L456) but it seems from the discussion in this issue that we may want to explicitly assert that each row has the same keys.
* Extra fields in a row are currently ignored - also [noted in our docstring](https://github.com/nextstrain/augur/blame/f6ee377336ec3813468fe641fa7910c14e54ced3/augur/io/metadata.py#L455) - but we may want to revisit this. We can remove [this line](https://github.com/nextstrain/augur/blame/f6ee377336ec3813468fe641fa7910c14e54ced3/augur/io/metadata.py#L484) to let `DictWriter` assert it for us.
