### ISSUE TITLE
Improve typing experience with CI

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1516]
Discussion [on Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1719876885396029).

**Comment by genehack** [comment]
Not to balloon the scope here, but if we're gonna change how we're handling typing in the CI, maybe it's time to re-assess why we're running both [`mypy`](https://github.com/nextstrain/augur/blob/master/tests/test_mypy.py) and [`pyright`](https://github.com/nextstrain/augur/blob/master/tests/test_pyright.py) in the test suite?

**Comment by victorlin** [comment]
Well right now we haven't configured Pyright to check types at all:

https://github.com/nextstrain/augur/blob/f9a071fdf05ffe309cc1be51007bff4e905bf7f8/pyrightconfig.json#L16

Even if/when we enable that option, is one strictly a subset of the other? Based on [Pyright's comparison](https://github.com/microsoft/pyright/blob/main/docs/mypy-comparison.md), it looks like each has its pros and cons.

**Comment by genehack** [comment]
i guess i don't see what this is improving. if the mypy test fails during CI for a particular python version, doesn't that indicate potential runtime issues with that particular python version? isn't surfacing that during CI beneficial?

**Comment by victorlin** [comment]
Apologies, the reasoning should have been in the issue description. This is what I think happened with @jameshadfield yesterday in #1506:

1. He pushed a3615eed380a4ce77d36b277faee0cf547ba861b and saw ❌ on a Python 3.10 job. Clicking that shows:

    ```
    tests/test_mypy.py::test_mypy augur/curate/rename.py:84: error: Invalid type: try using Literal[False] instead?  [valid-type]
    Found 1 error in 1 file (checked 74 source files)
    FAILED
    ```

2. He fixed that in [force-push](https://github.com/nextstrain/augur/compare/a3615eed380a4ce77d36b277faee0cf547ba861b..1671cdb675726e9036d0130e53c1e909688c0bc8) to 1671cdb675726e9036d0130e53c1e909688c0bc8 and saw ❌ on a Python 3.8 job. Clicking that shows:

    ```
    tests/test_mypy.py::test_mypy augur/curate/rename.py:30: error: "list" is not subscriptable, use "typing.List" instead  [misc]
    augur/curate/rename.py:30: error: "dict" is not subscriptable, use "typing.Dict" instead  [misc]
    augur/curate/rename.py:52: error: "list" is not subscriptable, use "typing.List" instead  [misc]
    augur/curate/rename.py:52: error: "dict" is not subscriptable, use "typing.Dict" instead  [misc]
    augur/curate/rename.py:52: error: "tuple" is not subscriptable, use "typing.Tuple" instead  [misc]
    augur/curate/rename.py:84: error: X | Y syntax for unions requires Python 3.10  [syntax]
    augur/curate/rename.py:84: error: "list" is not subscriptable, use "typing.List" instead  [misc]
    augur/curate/rename.py:84: error: "tuple" is not subscriptable, use "typing.Tuple" instead  [misc]
    Found 8 errors in 1 file (checked 74 source files)
    FAILED
    ```

Had he clicked a Python 3.8 job the first time around, he would have seen all the errors to fix:

```
tests/test_mypy.py::test_mypy augur/curate/rename.py:30: error: "list" is not subscriptable, use "typing.List" instead  [misc]
augur/curate/rename.py:30: error: "dict" is not subscriptable, use "typing.Dict" instead  [misc]
augur/curate/rename.py:52: error: "list" is not subscriptable, use "typing.List" instead  [misc]
augur/curate/rename.py:52: error: "dict" is not subscriptable, use "typing.Dict" instead  [misc]
augur/curate/rename.py:52: error: "tuple" is not subscriptable, use "typing.Tuple" instead  [misc]
augur/curate/rename.py:84: error: Invalid type: try using Literal[False] instead?  [valid-type]
augur/curate/rename.py:84: error: X | Y syntax for unions requires Python 3.10  [syntax]
augur/curate/rename.py:84: error: "list" is not subscriptable, use "typing.List" instead  [misc]
augur/curate/rename.py:84: error: "tuple" is not subscriptable, use "typing.Tuple" instead  [misc]
Found 9 errors in 1 file (checked 74 source files)
FAILED
```

but that's not very obvious from the GitHub UI since all Python 3.8 jobs were marked "canceled".

We really only care about mypy errors from the Python 3.8 job, so those should the only ones reported.
