### ISSUE TITLE
Update docs for new augur curate subcommands

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1519]
Add docs pages for everything on https://github.com/nextstrain/ingest/issues/43.

Doc updates are easy to forget. Maybe they should be a part of the PR checklist.

**Comment by joverlee521** [comment]
I _always_ forget this 🤦‍♀️ 

The PR checklist will help, but any reason the API docs can't be auto-generated as part of CI?

**Comment by victorlin** [comment]
> any reason the API docs can't be auto-generated as part of CI?

Let's consider this in #1524
