### ISSUE TITLE
Generate CLI documentation files?

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1524]
Doc updates such as #1523 are tedious and prone to human error. It would be good if they can be auto-generated.

API docs can already be auto-generated, https://github.com/nextstrain/augur/pull/1525 adds that to CI.

**Comment by victorlin** [comment]
I don't think this is trivial since some doc files e.g. [augur traits](https://github.com/nextstrain/augur/blob/0fa1e1a80633288b65747f808ae9bda17af0bc5d/docs/usage/cli/traits.rst) have custom text that isn't possible with auto-generation. If they were moved to docstrings such as [distance.py](https://github.com/nextstrain/augur/blob/0fa1e1a80633288b65747f808ae9bda17af0bc5d/augur/distance.py) it might be possible.

**Comment by joverlee521** [comment]
> I don't think this is trivial since some doc files e.g. [augur traits](https://github.com/nextstrain/augur/blob/0fa1e1a80633288b65747f808ae9bda17af0bc5d/docs/usage/cli/traits.rst) have custom text that isn't possible with auto-generation.

Following the [dev docs](https://github.com/nextstrain/augur/blob/master/docs/contribute/DEV_DOCS.md#building-documentation), I thought the doc files were auto-generated with 

```
sphinx-apidoc -T -f -MeT -o docs/api augur
```

Then any custom text is added manually? 

We can at least run the `sphinx-apidoc` command to autogenerate the pages and they can get manually filled in with custom text as needed?

**Comment by victorlin** [comment]
I created this before realizing API docs could be regenerated but this still applies to CLI docs. Closing as unplanned since there is no obvious solution and CLI docs aren't updated as frequently.
