### ISSUE TITLE
Officially support python 3.12: test for it and add trove classifier

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1536]
This is actually blocked by pandas v2 support, as v2 is the first to support Python 3.12:
- https://pandas.pydata.org/pandas-docs/version/1.5/getting_started/install.html#python-version-support

Blocked on https://github.com/nextstrain/augur/issues/1473

**Comment by victorlin** [comment]
I just checked locally to confirm that pandas 1.x is the only dependency that doesn't have pre-built wheels for Python 3.12.

Also, from https://github.com/nextstrain/augur/issues/1473#issuecomment-2420030483:

> Augur+pandas are installable on Python 3.12 as-is. The lack of 3.12 support on pandas 1.x just means that it has to be built from source instead of installing pre-built wheels. I haven't done any actual testing, but maybe this is good enough to get things going on your end.

**Comment by victorlin** [comment]
Closed by #1678
