### ISSUE TITLE
Update .mailmap

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1537]
I noticed we have a .mailmap file which hasn't been touched in 5 years - should we actively maintain it or remove it?

**Comment by victorlin** [comment]
I didn't realize we had the file. Since we don't have it in other repos ([query](https://github.com/search?q=org%3Anextstrain%20path%3A.mailmap&type=code)), I vote to remove it.

**Comment by tsibley** [comment]
While not being touched in 5 years means it might be out of date/stale, it's not like it's become wrong or anything. It's a backwards-looking file over immutable commit data, so it doesn't rot like other things, just get more stale.

I suspect neither of you looked at the git history of it, as it's still used in the generation of https://docs.nextstrain.org/projects/augur/en/stable/authors/authors.html. Which yes, shows that it could use some updates.

**Comment by corneliusroemer** [comment]
Thanks for the context @tsibley - I didn't look at git history indeed.
