### ISSUE TITLE
Simplify probabilistic sampling calculation

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1588]
## Context

The probabilistic sampling calculation currently takes the number of sequences available per group [as input](https://github.com/nextstrain/augur/blob/d8faf01ec1008b4e7b98fa2285d2f9c931c505d7/augur/filter/subsample.py#L437).

This information doesn't seem to be necessary. The output is based on the number of groups rather than the size of each group. Example:

```py
from augur.filter.subsample import _calculate_fractional_sequences_per_group

_calculate_fractional_sequences_per_group(3, [1,2,3,4])
_calculate_fractional_sequences_per_group(3, [1,1,1,1])
_calculate_fractional_sequences_per_group(3, [100,100,100,100])
_calculate_fractional_sequences_per_group(3, [1,1,1,1000])
# All of the above return 0.726570078125
```

Taking a closer look at implementation:

https://github.com/nextstrain/augur/blob/d8faf01ec1008b4e7b98fa2285d2f9c931c505d7/augur/filter/subsample.py#L474

This seems to be an overly complex way of approximating the fraction $\frac{\text{max sequences}}{\text{number of groups}}$. When it is changed to

```py
while (hi / lo) > 1.000001:
```

, the return value of the commands above is $0.7499999898397923 \approx \frac{3}{4}$.

## Impact

The deviation can lead to assertion errors here

https://github.com/nextstrain/augur/blob/da1c89d4b3232aa977b69fb8df33d666532c9a56/augur/filter/subsample.py#L285

when `--subsample-max-sequences` is slightly lower than the number of groups such as https://github.com/nextstrain/augur/issues/1598:

```py
_calculate_fractional_sequences_per_group(400, [1,]*406)
# This returns 1.0254 when the exact calculation should be 0.9852
```

## Proposal

Replace [`_calculate_fractional_sequences_per_group()`](https://github.com/nextstrain/augur/blob/d8faf01ec1008b4e7b98fa2285d2f9c931c505d7/augur/filter/subsample.py#L435-L481) with the exact fraction `target_max_value / len(group_sizes)`.

**Comment by corneliusroemer** [comment]
I think the reason is that one can't just pick `desired_total/groups` because some groups might have less than that number. So we wouldn't end up with the right desired total.

**Comment by victorlin** [comment]
Re: https://github.com/nextstrain/augur/pull/1599#issuecomment-2307528822 (copying to discuss design decisions here):

> There's a reason the original calculation is the way it is. I don't think that's a bug or unnecessary.
> 
> Imagine there are 90 groups with 1 sequence and 10 groups with 1000. We want to sample 1000 sequences.
> 
> The original calculation would pick around 91 sequences per group.
> 
> Yours now picks 10 per group.
> 
> The original resulted in around 1000 sampled sequences.
> 
> Your calculation now in only 190.

That scenario does not result in probabilistic sampling and will not fall through this code path. It will only come here if the number of groups exceeds the desired total sequences.

Your example has 100 groups so this would only happen when sampling less than 100 sequences. At that point the number of samples available in each group does not matter and either pick 1 or 0 samples should be picked per group.
