### ISSUE TITLE
filter: Confusing warning and error combination when query contains a missing column

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1592]
@huddlej noted in https://github.com/nextstrain/mpox/issues/273#issue-2476185121 that this output comes across as a bug (that a warning is also an error):

```
WARNING: Column 'QC_rare_mutations' does not exist in the metadata file. Ignoring it.
ERROR: Query contains a column that does not exist in metadata.
```

This happens because the columns are effectively checked twice:

1. `read_metadata` which does not error by design:

    https://github.com/nextstrain/augur/blob/d8faf01ec1008b4e7b98fa2285d2f9c931c505d7/augur/io/metadata.py#L124-L127

2. Evaluation of the query:

    https://github.com/nextstrain/augur/blob/d8faf01ec1008b4e7b98fa2285d2f9c931c505d7/augur/filter/include_exclude_rules.py#L243-L247

## Possible solution

Both checks are beneficial, so it doesn't make sense to remove either. Instead, the warning text could be updated to indicate potential issues:

```
WARNING: Column 'QC_rare_mutations' does not exist in the metadata file. This may cause subsequent errors.
ERROR: Query contains a column that does not exist in metadata.
```

**Comment by genehack** [comment]
I would think if you're going to be making changes here, updating the second (error) message to include the name of the missing column would be a good improvement — it will make the combination of messages overall more clear because it will be apparent that both of them are about the same column.

**Comment by victorlin** [comment]
> updating the second (error) message to include the name of the missing column would be a good improvement

I agree, and looked into this briefly. Pandas's `UndefinedVariableError` does not expose the column name apart from being in the error message text `name 'QC_rare_mutations' is not defined`, and parsing it from there feels wrong. Maybe a good compromise would be to tack on the entire Pandas error message like this:

```
WARNING: Column 'QC_rare_mutations' does not exist in the metadata file. This may cause subsequent errors.
ERROR: Query contains a column that does not exist in metadata: name 'QC_rare_mutations' is not defined
```
