### ISSUE TITLE
augur export case question

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#160]
While trying to get WNV through modular augur i'm running into the issue where:
* demes are specified in the metadata TSV in uppercase
* `augur export` converts these to lowercase to find a match in the lat-long database (code [here](https://github.com/nextstrain/augur/blame/master/augur/export.py#L122))
* `augur export` exports the deme names in lowercase 
* auspice can't match the uppercase deme name (encoded on the tree node) with the lowercase deme name in the metadata->geo mapping.

More generally, we've had these kind of errors in the past, how should we proceed?
(Note that auspice should get the deme names etc encoded in the form that one wants them displayed)

**Comment by trvrb** [comment]
My suggestion here would be to make sure that deme names in `metadata.tsv` match deme names in `lat_longs.tsv` and `colors.tsv`. I would suggest snake_casing everything in `metadata.tsv`. This was my standard practice for all other builds.

I want an `augur clean` module that would take some of the functionality of sacra that would make it easier to get a clean and snake_cased metadata file. Augur clean vs sacra is definitely worth a larger conversation.

In the interim, you could make a simple script to do this if FASTA coming in is capitalized (and has the "non-standard" 2-letter state codes).

**Comment by jameshadfield** [comment]
How about converting both the metadata.tsv defined demes and the lat-long demes to lowercase _for comparison only_, but the exported demes match those in the metadata.tsv?

**Comment by trvrb** [comment]
Sorry, but I'm worried about that approach. The canonical lat-long file will have names like `north_dakota`. If metadata comes in as `NorthDakota`, then simple lowercasing won't work. This particular example would cause some things to match and some to not. It will be opaque on why these are failing. I favor a simple direct comparison. This should make it obvious how to construct `lat_longs.tsv`. 

If someone really doesn't want to use snake_case deme names then they can make a lat-long file with names as `NorthDakota` etc...
