### ISSUE TITLE
Release workflow doesn't run tests successfully but continues anyway

### ISSUE THREAD

**Issue by tsibley** [nextstrain/augur#1633]
The test step:

https://github.com/nextstrain/augur/blob/227f52681a5bbd183a7a4993996fcf54dfdb5a57/.github/workflows/release.yaml#L28

doesn't error on test failures because `devel/test` masks the exit status:

https://github.com/nextstrain/augur/blob/227f52681a5bbd183a7a4993996fcf54dfdb5a57/devel/test#L28-L30

I noticed this [with the 26.0.0 release just now](https://github.com/nextstrain/augur/actions/runs/10907953155/job/30272814644#step:7:1693), but it's been happening with past release workflow runs too.

While we can "fix" this by propagating the exit status in `devel/test`, I don't think `devel/test` is really appropriate for CI/CD, at least in its current developer-focused form. Our release process should ideally use a very similar test setup as CI does, or even be _part_ of the CI/CD workflow.

**Comment by victorlin** [comment]
How about something like #1634?

**Comment by tsibley** [comment]
Left commentary there.
