### ISSUE TITLE
Augur index may always report sequence file is missing even if output dir is missing?

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/augur#1644]
### Current Behavior
My student Nosihle @Nosi-msomi reports that when trying to run:
```
augur index \
  --sequences data/sequences.fasta \
  --output results/sequence_index.tsv
```
If the `results` folder doesn't exist, she gets the error "ERROR: Could not open sequences file 'data/sequences.fasta'" (even though `data/sequences.fasta` does exist).

Checking the code I am wondering if this is because of the [generic `FileNotFoundError` catch](https://github.com/nextstrain/augur/blob/bf05db88da262322c59d5032920d32ad5c3047b3/augur/index.py#L218), which may be being triggered if the output directory isn't found?

Very sorry, I haven't had time to test this myself....

### Possible solution
- Make error more generic (say that either input or output dir is not found?)
- Test and see which file/dir is actually missing & send a specific error message in each case (if the sequence file is present, can we assume the output dir is missing?)

**Comment by victorlin** [comment]
> Checking the code I am wondering if this is because of the [generic `FileNotFoundError` catch](https://github.com/nextstrain/augur/blob/bf05db88da262322c59d5032920d32ad5c3047b3/augur/index.py#L218), which may be being triggered if the output directory isn't found?

Good thinking! I just tested and can confirm that this is the case.

Another solution would be to automatically create the directory (or add an option to do so), but that is a bigger change that should be considered across Augur.

It's very possible to fix the error message to show the right file – I would go for that solution over making it generic.
