### ISSUE TITLE
how to subsample segmented viruses

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#168]
Part of the way `prepare` was written allowed segmented viruses to be subsampled such that both segments had the same samples taken forward for analysis (or at least a high overlap). How should one achieve this in modular augur? This is critical for tanglegrams and also fitness models using multiple segments.

**Comment by jameshadfield** [comment]
After talking to @huddlej this seems to be the best way:

* filter takes all `n` segments, and produces `n` subsampled fastas -- that is, the logic for subsampling multiple segements to ensure maximum overlap (or whichever is desired) is contained within filter  (e.g. https://github.com/nextstrain/janus/blob/master/Snakefile#L23)
* each rule after that uses wildcards, so that only one `align` rule is needed to process all `n` segments (e.g. https://github.com/nextstrain/janus/blob/master/Snakefile#L100)

**Comment by rneher** [comment]
This has been resolved for flu by sampling strains. This could be ported into augur if there is need.
