### ISSUE TITLE
merge: Quoting behavior

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1694]
Is it expected for `augur merge` to add quotes around values that contain spaces? It doesn't seem to be necessary per [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180#autoid-2):

> 6. Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.

I noticed this behavior while working on https://github.com/nextstrain/zika/pull/75. That workflow currently uses `csvtk concat`, which does not add quotes around values that contain spaces.

cc @tsibley

**Comment by tsibley** [comment]
It's not necessary, but it's allowed and shouldn't be an issue. SQLite's CLI has a pretty conservative [quoting strategy](https://sqlite.org/src/artifact/883d1470#:~:text=static%20const%20char%20needCsvQuote[]):

```c
/*
** If a field contains any character identified by a 1 in the following
** array, then the string must be quoted for CSV.
*/
static const char needCsvQuote[] = {
  1, 1, 1, 1, 1, 1, 1, 1,   1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1,   1, 1, 1, 1, 1, 1, 1, 1,
  1, 0, 1, 0, 0, 0, 0, 1,   0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 1,
  1, 1, 1, 1, 1, 1, 1, 1,   1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1,   1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1,   1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1,   1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1,   1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1,   1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1,   1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1,   1, 1, 1, 1, 1, 1, 1, 1,
};
````

Space is the leading `1` in the third line of data.
