### ISSUE TITLE
Augur export is messing with branch lengths

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#176]
_Edited to pin the blame on `augur export`._

Branch lengths are wrong in current `augur export`. Take a look at https://nextstrain.org/zika?l=clock (go to staging server). You'll see:

<img width="968" alt="zika" src="https://user-images.githubusercontent.com/1176109/42798400-8169eac8-8948-11e8-99eb-c229f8e3f9d5.png">

This is also apparent in that toggling between "time" and "divergence" does nothing. 

This can be reproduced from the `example_data/zika.fasta` input as well, resulting in:

<img width="959" alt="zika2" src="https://user-images.githubusercontent.com/1176109/42798567-1662a57a-8949-11e8-92ce-2c1d4d0e2ebd.png">

I confirmed that this was introduced in PR #165. Immediately prior to #165 (commit 341e43da06ef9670ebe7e5fdcb2cb9b04f966d75) I get:

<img width="960" alt="zika3" src="https://user-images.githubusercontent.com/1176109/42799271-140ec940-894c-11e8-994e-19505413d61e.png">

@jameshadfield: Could you investigate? I suspect it's just a misplaced `xvalue` or `tvalue`. It looks like divergence has been overwritten with time.

**Comment by jameshadfield** [comment]
Working on this now.

At commit `341e43da06ef9670ebe7e5fdcb2cb9b04f966d75` (the one prior to the PR which broke the divergence) the test dataset (`augur/test/zika`) looks like this:

![image](https://user-images.githubusercontent.com/8350992/42838629-2a773fd6-89b6-11e8-84ab-51f42c5d8295.png)

![image](https://user-images.githubusercontent.com/8350992/42838651-366cb96a-89b6-11e8-95e3-15651a16c611.png)

Is this correct @trvrb ?

**Comment by trvrb** [comment]
This the correct tree for `test/zika/`. It's a display bug in auspice I believe.
