### ISSUE TITLE
Augur filter needs more generic filtering options

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#179]
In order to migrate some of the existing augur builds, we need a way to specify to drop or include sequences based on generic metadata fields. Examples include:

* https://github.com/nextstrain/augur/blob/master/builds/mumps/mumps.prepare.py#L27
* https://github.com/nextstrain/augur/blob/master/builds/avian/avian.prepare.py#L76

There should be a nice way to specify this sort of thing via the command line interface.

**Comment by tsibley** [comment]
For those two examples, one interface for this might be:

`--exclude-where country=^unknown` (preserving the `startswith` behaviour, which could probably be dropped)

`--exclude-where host=laboratoryderived --exclude-where host=watersample`

with corresponding `--include-where` options.

**Comment by jameshadfield** [comment]
Here's the WNV example https://github.com/nextstrain/WNV/blob/master/scripts/parse_fasta_csv_query_entrez.py#L153

**Comment by huddlej** [comment]
Closing this issue as it was initially addressed by #190.

More specific filters on metadata are discussed in issue #244.
