### ISSUE TITLE
create conda install script / yaml

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#181]
We use conda to install dependencies for the travisCI build scripts (https://github.com/nextstrain/augur/blob/master/.travis.yml), and conda is frequently used in the bioinformatics community. I would like augur to contain a conda `meta.yaml` file to install non-pip dependencies. One would then run `pip` after installing & activating the conda env, just as is done in the travis script. 

This yaml file could be used inside the travis script (as an aside, I thought you had to run `source activate test-environment` before you ran `conda install...`)

**Comment by trvrb** [comment]
I don't have conda installed locally, so difficult to test. I think your `meta.yaml` file just looks like this:
```
name: augur
channels:
- bioconda
- defaults
dependencies:
- mafft
- fasttree
- iqtree
- raxml
- numpy
- vcftools
```

**Comment by jameshadfield** [comment]
Done 🎉 -- see https://nextstrain-augur.readthedocs.io/en/stable/installation.html#with-conda
