### ISSUE TITLE
Add meta top-level layer to schema v2

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#183]
Right now, `zika.json` looks like:
```
{
  "title": "Analysis",
  "maintainers": [
    {
      "name": "",
      "href": ""
    }
  ],
  "filters": [
    "region",
    "country",
    "sequence",
    "authors"
  ],
  "version": "2.0",
  "tree": {...}
...
```

I think the combined JSON schema would be better if there was a top-level `meta` layer that encloses metadata. I would have three just entries at top-level:
```
{
  "version": "2.0",
  "meta": {...},
  "tree": {...}
}
```

`tree` is so different from `title`, etc... that I think this needs more structure.

**Comment by tsibley** [comment]
I support this proposal.

**Comment by jameshadfield** [comment]
Fine by me.
