### ISSUE TITLE
How to name nodes in tree

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#185]
Currently all tree nodes have a `strain` attribute that looks like `"strain": "NODE_0000010"` for internal nodes and look like `"strain": "Colombia/2016/ZC204Se"` for tips. Calling an abtract internal node a `strain` offends my biological sensibilities.

I would propose to swap `strain` for `node`. All nodes in `tree` will have a `node` attribute, like `"node": "NODE_0000010"` and `"node": "Colombia/2016/ZC204Se"`.

**Comment by jameshadfield** [comment]
Can you call them "name"? We use `node` everywhere to refer to the node object, and i'd prefer `node.name` over `node.node`

**Comment by trvrb** [comment]
I'm just fine with using "name".

**Comment by rneher** [comment]
I prefer `node.name`. this also conforms with `Phylo.node`

**Comment by rneher** [comment]
Global search/replace and hope it still works ;)

**Comment by joverlee521** [comment]
Closed by PR #351
