### ISSUE TITLE
Multiple Python bindings for git

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#20]
There are two Python bindings for git used in augur:

  * [GitPython](https://github.com/gitpython-developers/GitPython) which provides the `git` module and is used by the `base/sequences_prepare.py` augur module
  * [pygit2](https://github.com/libgit2/pygit2) which provides the `pygit2` module and is used by the `base/process.py` module

~Neither git module is listed in the Dockerfile or requirements.txt. Is there a preference for which module to use?~. Sorry, gitpython is in requirements.txt for the rejig branch!

**Comment by trvrb** [comment]
This was resolved in 92a2e7934619f6ddbb878e77aac26c6ae56b95c4.
