### ISSUE TITLE
Augur modules need to preemptively clean out temporary files

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#201]
I was getting a strange bug while running Zika builds (first documented here https://github.com/nextstrain/cli/issues/20 because I thought it might have been a CLI issue). Basically some augur modules like `augur tree` generate temporary files like `temp_iqtree.fasta` that get created, used and deleted by the module. However, if the module crashes or if it's quit halfway through then the temp files will be left in the directory. When `augur tree` is next run then `temp_iqtree.fasta` will be fetched and it being empty will cause a crash.

My recommendation is this: if a module uses temp files, the module should attempt to delete these temp files at the beginning of it's run. This will prevent this sort of interference from occurring.

**Comment by tsibley** [comment]
> When augur tree is next run then temp_iqtree.fasta will be fetched and it being empty will cause a crash.

Hmm, this isn't what the code actually does. The beginning of `build_iqtree()` always overwrites the `temp_iqtree.fasta` file, regardless of any existing copy: https://github.com/nextstrain/augur/blob/5c86faa/augur/tree.py#L108-L112.  That's a pretty safe way to do it.

**Comment by huddlej** [comment]
It seems like the specific issue with `augur tree` might have been closed by [renaming the temp file output for IQ-TREE](https://github.com/nextstrain/augur/commit/7137b36f83d22c410bbdf4eac83b26f12e3e5b2e) and maybe by [renaming the log output](https://github.com/nextstrain/augur/commit/d82f8b7010a349957270c1b6df1e29abc1f98338#diff-fee0b033dec1c65b2a3d4542a49b0a45). It also looks like augur tree now cleans up all temporary files from different tree builders.

The [augur align command also automatically cleans up after finishing properly](https://github.com/nextstrain/augur/blob/7d9c962/augur/align.py#L116-L118).

Closing this now, but if this ends up not being fully resolved, we can reopen.
