### ISSUE TITLE
Include version script

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#202]
@tsibley ---

I hope it's is okay that I'm assigning this to you. You definitely have a lot familiarity here.

I'd like to start versioning augur. Let's start at `3.0.0` and go from there. Like auspice, I'd recommend having a `master` branch and a `release` branch. Both always exist. Release branch gets tagged with each new version. Release branch will make `docker-base` builds easier. I assume the release script looks something like https://github.com/nextstrain/cli/blob/master/devel/release.

One thing here, we have a somewhat different release script for auspice: https://github.com/nextstrain/auspice/blob/master/releaseNewVersion.sh. It would be nice if the release patterns were not wildly different between the two (this may mean revising the auspice release script as well).

Pushing to PyPI can be a separate issue once we have versioning in place.

**Comment by tsibley** [comment]
Sure, I can do this.

**Comment by jameshadfield** [comment]
Great! (This issue will also close https://github.com/nextstrain/augur/issues/146 👍 )
