### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by tillea** [nextstrain/augur#22]
Hi,
I'm writing you on behalf of the Debian Med team which is a group inside Debian with the objective to package free software in life sciences and medicine for official Debian.  It would be interesting for us to package treetime.  It would help if you could tag your releases to enable us automatically detecting what you consider as user targeting release and any ot such updates.
Thanks for considering, Andreas.

**Comment by rneher** [comment]
Hi Andreas,
thank you for interest! would be great to have it packaged. But I am slightly confused. You opened this issue on nextstrain/augur but refer to treetime (neherlab/treetime)? Either way, we'll look into releases but the code base of both projects have been a bit in flux lately. 

best,
richard

**Comment by tillea** [comment]
Hi Richard,
On Mon, Jun 19, 2017 at 05:57:09AM -0700, Richard Neher wrote:
> thank you for interest! would be great to have it packaged.

I was inspired by your Digital Epidemiology talk in RKI which I watched via video conference. :-)

> But I am slightly confused. You opened this issue on nextstrain/augur but refer to treetime (neherlab/treetime)? Either way, we'll look into releases but the code base of both projects have been a bit in flux lately. 

Sorry for the confusion - that was a cut-n-pasto from treetime.  BTW, treetime is just in Debian new queue with an arbitrary version based on the last changelog date.  This can be overriden by an upload of a properly versioned release easily.

Feel free to suggest more code that you might consider worth packaging, preferably to the public mailing list of the Debian Med team debian-med@lists.debian.org.

Kind regards, Andreas.

**Comment by trvrb** [comment]
Thanks Andreas. I agree that we should make tagged releases for augur. We can follow semantic numbering based on JSON export format.

**Comment by tillea** [comment]
Hi Trevor,
On Wed, Jun 21, 2017 at 10:55:44AM -0700, Trevor Bedford wrote:
> Thanks Andreas. I agree that we should make tagged releases for augur. We can follow semantic numbering based on JSON export format.
Thanks for the confirmation to tag releases.  I admit I do not understand what you mean by "semantic numbering".  It would be convenient if it starts with a number and is sortable.
Regarding the packaging:  I noticed that I need to package seqmagick, ipdb (which both look easy) and rethinkdb.  The latter seems to be complex but I'll have a look - most probably after vacation.  Andreas.

**Comment by trvrb** [comment]
I've started to tag releases here: https://github.com/nextstrain/augur/releases.
