### ISSUE TITLE
augur filter does not support filtering by attribute values

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#244]
For users who would like to filter a collection of sequences/metadata by specific attribute values (e.g., `region=north_america`), there isn't a path to perform this type of filter with the `augur filter` command.

The filter command does provide an `--include-where` argument that appears to provide this kind of filtering-by-attribute functionality, but instead this argument allows the user to include sequences that match one or more attribute values regardless of whether they have been filtered out already. For example, one would expect the following command to output only sequences >=10 kbp from North America.

```
augur filter \
    --sequences sequences.fasta \
    --metadata metadata.tsv \
    --output test.txt \
    --min-length 10000 \
    --include-where region=north_america
```

Instead, this command outputs sequences that are >=10 kbp plus all sequences from North America regardless of their length.

If this type of `--include-where` logic is helpful as currently implemented, could we add a corresponding `--filter-where` or simply a `--where` argument that allows users to filter records instead of including them? It would also help users to clarify the help documentation for `--include-where` and this potential `--filter-where` argument to avoid confusion.

**Comment by rneher** [comment]
Currently `include-where` operates as `OR` clauses. Historically this was done to allow selecting a certain set and adding other sequences *on top*. We certainly should be more explicit about what these arguments do. I am sure there good implementations of `AND`/`OR` conditionals on CLI.

**Comment by huddlej** [comment]
One potential implementation of and/or conditionals on the CLI would take advantage of pandas' built-in [query method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html) for data frames. This method allows the caller to specify a string query with any number of boolean tests. We could implement the `--filter-where` argument to pass a query that will filter the metadata table prior to all other downstreaming filter.

For example, we could implement the original filter in this issue's description as:

```
augur filter \
    --sequences sequences.fasta \
    --metadata metadata.tsv \
    --output test.txt \
    --min-length 10000 \
    --filter-where "region == 'north_america'"
```

If genome length was already annotated in the metadata (as it is for the ncov builds, for example), the filter command could be:

```
augur filter \
    --sequences sequences.fasta \
    --metadata metadata.tsv \
    --output test.txt \
    --filter-where "(region == 'north_america') & (length > 10000)"
```

The way metadata is currently read into augur as a dictionary from a pandas data frame, the simplest implementation would pass this `--filter-where` query string as an optional argument to the [read_metadata function](https://github.com/nextstrain/augur/blob/904ed6d/augur/utils.py#L74-L81). If that query string is not `None`, filter would apply the query to the pandas data frame prior to returning the metadata dict.
