### ISSUE TITLE
tree.py invalid syntax error

### ISSUE THREAD

**Issue by elasekness** [nextstrain/augur#257]
It looks like there's an errant "f" in line 352 of tree.py

File "/usr/local/lib/python3.5/site-packages/augur/tree.py", line 352
    masked_alignment_file = str(alignment_file_path.parent / f"masked_{alignment_file_path.name}")

**Comment by rneher** [comment]
Thanks for spotting this. @huddlej, looks like this got introduced when implementing the masking. Could you fix it?

**Comment by huddlej** [comment]
Thank you for catching this @elasekness and apologies for the inconvenience!
