### ISSUE TITLE
Consider supporting plugin-style interface for augur command interface

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#265]
Some functionality in augur is currently only used for seasonal flu builds (like `augur distance`), but keeping this functionality in augur prevents code duplication across flu projects. Could it be worthwhile to allow other projects like `seasonal-flu` to provide their own plugins to the augur command line interface? The code for these plugins could live in separate PyPI packages (e.g., `augur-flu`) and if they are installed, they could patch the existing augur interface.

Or would this make maintaining augur itself too complicated? Would it be simpler to maintain a separate `augur-flu` package that augur itself knows nothing about?

**Comment by tsibley** [comment]
While some of the distance measures themselves might be specific to flu, the concept of calculating distances between two nodes on a tree seems pretty general. For example, patristic distance is sometimes used for clustering determinations.

While augur's command-line interface and internal command dispatch system are well-suited for plugins, I'd advocate for avoiding the additional overhead of plugins as long as reasonable.

(For what it's worth, I'd expect an `augur-flu` package to provide an `augur flu` command that had other subcommands, like `augur flu distance` or somesuch.)

**Comment by huddlej** [comment]
Closing since this is unnecessary for now.
