### ISSUE TITLE
Metadata TSV should not be required for auspice export

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#275]
Currently a metadata TSV file must be provided with `augur export` [1], despite the code handling cases when this is not provided. Is this intentional? I am able to export working JSONs without such a file so I think we should make it optional. This was introduced in 0ad5088144a2a2c3c10313acc2643287909fb759

[1] https://github.com/nextstrain/augur/blob/master/augur/export.py#L437

**Comment by trvrb** [comment]
I agree that metadata TSV shouldn't be required by `augur export`. See also #273 for slimming down requirements for `augur export`.

**Comment by rneher** [comment]
agree as well.

**Comment by jameshadfield** [comment]
👍 this issue will be closed by c404ed350a93e18be408e73c6d01d41f64a6f68e in PR #276

**Comment by jameshadfield** [comment]
Closed in the v6 branch
