### ISSUE TITLE
lbi and numerical meta

### ISSUE THREAD

**Issue by TimHHH** [nextstrain/augur#287]
Hi there.
I am having a couple of (minor) issues here, any help would be appreciated.
Augur lbi is demanding parameters that are not supposed to be mandatory:
```nextstrain:/nextstrain/build $ augur lbi --tree results/tree.nwk             --branch-lengths results/branch_lengths.json             --output results/lbi.json
usage: augur lbi [-h] --tree TREE --branch-lengths BRANCH_LENGTHS --output
                 OUTPUT --attribute-names ATTRIBUTE_NAMES
                 [ATTRIBUTE_NAMES ...] --tau TAU [TAU ...] --window WINDOW
                 [WINDOW ...]
augur lbi: error: the following arguments are required: --attribute-names, --tau, --window
```
Also I can't seem to annotate metadata that solely consists of numbers, adding some random letters solves the issue.
Thanks.
Tim

**Comment by rneher** [comment]
Thanks for reaching out, Tim. 

These parameters are mandatory. But you can give 1,2,3,... sets of parameters (attribute-name, tau, window). For each (tau, window) combination, will be stored under the respective attribute name. 

could you be more specific regarding the issue with numerical metadata? metadata is parsed by pandas.read_csv. I don't see why this wouldn't allow purely numerical fields.

**Comment by TimHHH** [comment]
Thanks Richard, I will give the lbi a go as mentioned.
Re the metadata, it  looks like this:
```lineage_a
2
4
3
1```
color.tsv has this:
```lineage_a | 1 | #F2F2F2
lineage_a | 2 | #B3E2CD
lineage_a | 3 | #FDCDAC
lineage_a | 4 | #CBD5E8
```
and I get this error:
```nextstrain:/nextstrain/build $ augur export --tree results/tree.nwk --metadata data/meta.tsv --node-data results/branch_lengths.json results/traits.json results/traits2.json results/drms.json results/aa_muts.json results/nt_muts.json results/clades.json --auspice-config config/config.json --colors config/color.tsv --lat-longs config/lat_longs.tsv --output-tree auspice/EXIT_tree.json --output-meta auspice/EXIT_meta.json
Traceback (most recent call last):
  File "/usr/bin/augur", line 11, in <module>
    load_entry_point('nextstrain-augur', 'console_scripts', 'augur')()
  File "/nextstrain/augur/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/nextstrain/augur/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
  File "/nextstrain/augur/augur/export.py", line 514, in run
    meta_json["color_options"] = process_colorings(meta_json, color_mapping, nodes=nodes, nextflu=True)
  File "/nextstrain/augur/augur/export.py", line 156, in process_colorings
    case_map = {val.lower(): val for val in values_in_tree}
  File "/nextstrain/augur/augur/export.py", line 156, in <dictcomp>
    case_map = {val.lower(): val for val in values_in_tree}
AttributeError: 'int' object has no attribute 'lower'
```
as mentioned, things turn out fine when I add e.g. "lin" before the numerical values.

**Comment by rneher** [comment]
Ok. this makes sense. the pandas parser automatically detects these columns as numbers but the `augur export` wants to standardize everything to lowercase. I'll fix this with an explicit str cast.

thanks!

**Comment by trvrb** [comment]
Thanks for catching this @TimHHH and thanks for the fix @rneher. This issue was resolved in https://github.com/nextstrain/augur/commit/5f3806c0b30333906dad0ab468ae5d4fdab48ff3.
