### ISSUE TITLE
do the `install_requires` dependencies need to be pinned so precisely?

### ISSUE THREAD

**Issue by jbloom** [nextstrain/augur#290]
I'm having trouble installing `nextstrain-augur` because all of the dependencies are pinned to such precise versions in `setup.py` ([here](https://github.com/nextstrain/augur/blob/master/setup.py#L36-L46)). This makes it difficult to co-install with other packages that use more recent versions of the dependencies; for instance, I can't install concurrently with anything that uses `pandas` 0.24.* rather than 0.23.4, or `matplotlib` 3.*., etc.

Is this exact pinning necessary for `augur` to work? If not, would it be possible to relax the pinning? The Python [packaging docs](https://packaging.python.org/discussions/install-requires-vs-requirements/) say that "It is not considered best practice to use `install_requires` to pin dependencies to specific versions" unless it is absolutely needed.

**Comment by rneher** [comment]
pandas 0.24 or anything higher or lower will almost certainly work. it is only used for csv parsing. i haven't worked with matplotlib 3, but most steps don't do any plotting. So you should be safe just changing the setup.py locally. We'll look into what we can relax, I am not a big fan of this pinning either.

**Comment by rneher** [comment]
this should have been resolved in PR #291. TreeTime currently requires matplotlib 2*, but will ok with 2 or 3 starting with the next release.
