### ISSUE TITLE
Add versioning policy to docs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#295]
Cross linking to a point raised by @tsibley:

> We've been using semantic versioning for augur for a little bit now. It's useful for newcomers looking to figure out how augur will work for them to know what they can expect in terms of new versions breaking their code or not. I often see this for other projects as a doc page. Doesn't need to be long, mostly a pointer to semver.org.

**Comment by jameshadfield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document versioning policy](https://trello.com/c/JjBwaRXp/6-document-versioning-policy)

**Comment by St4rz** [comment]
Hi, newcomer here. I think this issue can be closed now as I see the link to the semver.org homepage linked in [DEV_DOCS.md](https://github.com/nextstrain/augur/blob/master/DEV_DOCS.md):

> Versions for this project, Augur, from 3.0.0 onwards aim to follow the Semantic Versioning rules.

**Comment by jameshadfield** [comment]
Agreed. We still need to discuss what counts as "private" functions, and therefore what constitutes a breaking API change, but that's raised in some other issues and isn't what this issue targeted.
