### ISSUE TITLE
traits which augur export v2 shouldn't export

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#316]
Current augur export (v1) behavior is confusing as it exports some combination of `clock_length`, `raw_date`, `num_date`, `div`, `branch_length`. Auspice (current v1 and v2) only uses `num_date` and `div`. The others should not be exported by `augur export v2`. Thanks @lmoncla for bringing this up 👍 

To check: `date` is sometimes exported. Does auspice ever use this?

**Comment by rneher** [comment]
v2 doesn't exporte `date` or any `*_length`
