### ISSUE TITLE
"chromName" Error in Conda distribution / TB tutorial

### ISSUE THREAD

**Issue by RaSieb** [nextstrain/augur#320]
Installing augur with conda and running the tb tutorial returns the error below in the "mask" step of the tutorial: 
```Traceback (most recent call last):
  File "/srv/data/tools/public_envs/env_nextstrain/bin/augur", line 10, in <module>
    sys.exit(main())
  File "/srv/data/tools/public_envs/env_nextstrain/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/srv/data/tools/public_envs/env_nextstrain/lib/python3.6/site-packages/augur/__init__.py", line 70, in run
    return args.__command__.run(args)
  File "/srv/data/tools/public_envs/env_nextstrain/lib/python3.6/site-packages/augur/mask.py", line 61, in run
    tempMaskFile = get_mask_sites(args.sequences, args.mask)
  File "/srv/data/tools/public_envs/env_nextstrain/lib/python3.6/site-packages/augur/mask.py", line 37, in get_mask_sites
    exclude.append(chromName+"\t"+str(pos))
UnboundLocalError: local variable 'chromName' referenced before assignment
```

**Comment by RaSieb** [comment]
It seems like the before created filtered.vcf.gz is empty. However, replacing it with the original produces a new error: 
```Removing masked sites from VCF file using vcftools... this may take some time. Call:
vcftools --exclude-positions config/Locus_to_exclude_Mtb.bed_maskTemp --gzvcf results/filtered.vcf.gz --recode --stdout | gzip -c > results/masked.vcf.gz
/bin/sh: vcftools: command not found
```
Maybe these are related?

**Comment by emmahodcroft** [comment]
Hi RaSieb,
The second error you posted seems to be that you don't have the program `vcftools`. You'll need this to work with the TB tutorial and any bacterial data in VCF format. On Linux you should be able to install it with `sudo apt install vcftools`. 

`vcftools` is used in the first step, `filter`, so if this isn't working, it may be causing the error in the second step, `mask`. Can you try installing it, emptying the 'results' folder, and trying the run again?

**Comment by emmahodcroft** [comment]
Great to hear! However, the error this causes is really unhelpful - sorry about that! I will be pushing some changes so that future users have a better idea of what went wrong. Thank you for taking the time to bring it to our attention!

**Comment by RaSieb** [comment]
Great to hear, thanks for the effort!
