### ISSUE TITLE
Test all augur builds with v6 augur / v2 auspice

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#334]
Shouldn't be started until all other [v6](https://github.com/nextstrain/augur/issues?q=is%3Aissue+is%3Aopen+label%3Av6) issues have been closed (although it can't hurt to test during development as well!)

Note that as the `augur export` signature is a breaking change, all build repositories will need to be changed.

**Comment by rneher** [comment]
i have pushed a v2_v6 branch for seasonal flu. 
https://github.com/nextstrain/seasonal-flu/tree/v2_v6
works fine, other than for automatic date coloring.

**Comment by rneher** [comment]
clade and date now work as auto colorings, but display order in auspice is weird.

**Comment by jameshadfield** [comment]
Now that augur 5.4.0 can use the `augur export v1` syntax, we can move core builds to using this, or to `augur export v2` via a branch.

Here's the list of builds which we maintain & need to be updated -- anyone should be able to edit this message in order to update 🙏 

Build | Github Repo | v6 compat? | in charge
----- | ------------ | ------------ | ---------
measles | [nextstrain/measles](https://github.com/nextstrain/measles) | yes (master) |
zika | [nextstrain/zika](https://github.com/nextstrain/zika) | yes (v2 branch) | 
zika-tutorial | [nextstrain/tb](https://github.com/nextstrain/tb) | yes (v6 branch) |
seasonal flu | [nextstrain/seasonal-flu](https://github.com/nextstrain/seasonal-flu) | ??? | @joverlee521 
avian flu | [nextstrain/avian-flu](https://github.com/nextstrain/avian-flu) | no | @lmoncla @trvrb 
ebola | [nextstrain/ebola](https://github.com/nextstrain/ebola) | no | @jameshadfield 
mumps | [nextstrain/mumps](https://github.com/nextstrain/mumps) | no | @lmoncla @trvrb 
WNV | [grubaughlab/WNV-nextstrain](https://github.com/grubaughlab/WNV-nextstrain) | no | @jameshadfield 
dengue | [nextstrain/dengue](https://github.com/nextstrain/dengue) ??? | no | @trvrb 
TB | [nextstrain/tb](https://github.com/nextstrain/tb) | yes (v6 branch) |

**Comment by trvrb** [comment]
All builds besides WNV are now working with `augur export v1` in `master` and with `augur export v2` in `export-v2`. The only remaining issue with updating core builds is export of vaccines in seasonal-flu. Issue is here: https://github.com/nextstrain/augur/issues/407.

**Comment by jameshadfield** [comment]
WNV is now using `export v1` in `master`. #407 is closed. So I think all augur builds are done & tested 🎉
