### ISSUE TITLE
Boolean Confusion in Schema & Auspice

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/augur#338]
With the following in a `config` file for `v6`:
![image](https://user-images.githubusercontent.com/14290674/62200129-140e1400-b385-11e9-8ac4-cec231d9ad5c.png)

`validate` complains:
![image](https://user-images.githubusercontent.com/14290674/62200104-06588e80-b385-11e9-83a1-4969248aebc1.png)
Because of the specification in `schema-export-v2.json`:
![image](https://user-images.githubusercontent.com/14290674/62200203-37d15a00-b385-11e9-962a-2904ee4f01ed.png)

Despite the fact that this ("true" or "false") works in `auspice`.

I created a 'fix' for this in `export v2` to convert string T/F into boolean T/F. However, this does *not* work in `auspice`, as it expects a string. 

Do we want to change this in the `augur` schema, or in `auspice`?

**Comment by jameshadfield** [comment]
It should be `true`, even tho that's going to need augur + auspice modifications 😦

**Comment by emmahodcroft** [comment]
I kept the code for `augur export v2` which converted to a boolean on that end (if it's any help), but will need to be met with `auspice` changes on that end!

Code:
```
            def str2bool(v):
                return v.lower() in ("yes", "true", "t", "1")

            display_options = {}
            for key in config["display_defaults"]:
                new_key = convert_camel_to_snake_case(key)
                display_options[new_key] = str2bool(config["display_defaults"][key]) if new_key=="map_triplicate" else config["display_defaults"][key]
               
```

**Comment by jameshadfield** [comment]
@emmahodcroft I've been playing with this and all seems to be working... I've added to the zika test build & improved deprecation warnings via 04e3092a028a3622f5cc4c3d58d037e5248e6d36 and checked auspice does parse boolean values for `map_triplicate` here: https://github.com/nextstrain/auspice/commit/a3d9961a02a2889a6a98f2fa1023bf73816385f4

If there are still bugs please make a test case in the augur test builds & I can work with that 👍
