### ISSUE TITLE
Clarify the use of --output-sequence in v2 export

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#341]
I was just working with `v6` branch in augur and found it funny to have to use `augur export --output-main`. I would have expected with merging of tree and meta to then just have `augur export --output`. Then I saw that we still have `--output-sequence`. A little looking shows that this is only used in our `seasonal-flu` builds:

https://github.com/search?q=org%3Anextstrain+--output-sequence&type=Code

resulting in files like `auspice/flu_seasonal_h3n2_ha_3y_root-sequence.json`, which end up available as http://data.nextstrain.org/flu_seasonal_h3n2_ha_3y_root-sequence.json.

The current help in `v6` states:
```
SOON TO BE REMOVED OPTIONS:
  These options were available in augur v5 but are seemingly unused. Unless
  we discover otherwise, they will be removed before the v6 release. Note
  that they are still available via `augur export v1` to preserve the v5
  behavior.

  --output-sequence JSON
                        (reconstructed) sequences for each node
```

I see now that there is discussion around original implementation of `--output-sequence` here: https://github.com/nextstrain/augur/pull/212

So... either we:
1. Keep `--output-main` and `--output-sequence` so that auspice in a future version can assign genotypes to all positions (notably lacking now: https://nextstrain.org/measles?c=gt-nuc_101.
2. Deprecate `--output-sequence` in favor of using something like `augur ancestral` / `augur translate` instead.

I would favor (1). But I have a couple recommendations:
* We rename this `--output-root-sequence`, as this is what it does. We can keep `--output-sequence` around but deprecate it, so that `seasonal-flu` doesn't break.
* Update help to make it clear that this is the root sequence only

If we keep it, we need to update `export_v2.py` to move it out the deprecated list.

**Comment by jameshadfield** [comment]
Cheers @trvrb  -- relevant slack thread which led to them being removed from `v6`: https://bedfordlab.slack.com/archives/C131TERB5/p1563943483004100. 

> We rename this --output-root-sequence, as this is what it does. We can keep --output-sequence around but deprecate it, so that seasonal-flu doesn't break.

Seasonal flu will need updating when it moves from v5 to v6 as the `augur export` interface has changed, but `augur export v1` should/will have the same arguments as `augur export` did.

**Comment by trvrb** [comment]
Thanks James! I'm not worried about our use of sequences downstream for `seasonal-flu`. The reason to keep `--output-root-sequence` would be to allow genotype colorings in auspice for every position along the genome. I don't really care about this, but I believe that it's a major feature request from @rneher and from @emmahodcroft. My understanding is that this was the motivation behind Richard's original PR https://github.com/nextstrain/augur/pull/212.

I personally don't have strong feelings one way or the other. I'm happy with either:

1. Keeping `--output-main` and `--output-root-sequence` in `augur export` and adding functionality to auspice so that it looks for `zika-root-sequence.json` (or whatever) and uses this to allow for all sites to have colorings.

2. Removing `--output-root-sequence` and using `--output` in `augur export`. I'm just fine having sites that aren't variable have legends like: https://nextstrain.org/measles?c=gt-nuc_101. This would save a fair bit of complexity in terms of files to keep track off and auspice fetch calls.

(I might lean slightly towards 2 actually, but if others want 1, I'm fully on board) @rneher? @emmahodcroft?

**Comment by rneher** [comment]
we discussed that the root sequence could be part of the main json and only be broken out if too large (eg bacteria). One could have the `--output-root-sequence` (or maybe `reference-sequence`) as optional flag that triggers output of the sequence into a separate file.  I am in favor of having genotype coloring for non-variable positions though:
 
  * https://nextstrain.org/measles?c=gt-nuc_101 looks broken to me.
  * if one for example wants to assess whether a mutation caused a glycosylation loss, you need to be able to look up the amino acid 2 sites before. Same holds for other motif type questions.

**Comment by trvrb** [comment]
Thanks Richard. Okay. After thinking on this, here's my proposal:

* We include two new command line options `--separate-root-sequence` and `--include-root-sequence`. We do an intelligent default in which sequences over 50kb are automatically separated and sequences under 50kb are automatically included. This intelligent default can be overridden through the use of these flags.

* We choose JSON file name based on `--output`. In the case of `--output zika.json` and `--separate-root-sequence` we also output the file `zika_root-sequence.json`. This automatic naming seemed sensible to me as that is how auspice will need to look for this file anyway (ie it wouldn't make sense to have the option to name it something else).

* In the case of `--separate-root-sequence`, this separate file looks exactly like current output, so, for flu:
```
{
 "HA1": "DTLCIGYHANNST...",
 "HA2": "GLFGAIAGFIEGG..."
 "SigPep": "MKAILVVLLY...",
 "nuc": "GGAAAACAAAAGC..."
}
```
In the case of `--include-root-sequence` this same block goes at the top-level of the JSON as:
```
"root_sequence": {
 "HA1": "DTLCIGYHANNST...",
 "HA2": "GLFGAIAGFIEGG..."
 "SigPep": "MKAILVVLLY...",
 "nuc": "GGAAAACAAAAGC..."
}
```
I preferred to place this at the top level of the JSON instead of within the root node of the tree because it felt like a more natural mirroring of the separate file option.

* In this scenario, auspic looks in the primary JSON for the presence of `root_sequence`. If it finds this sequence it uses it as reference for genotypes. Simultaneously, auspice tries to fetch`_root-sequence.json`, if it finds `_root-sequence.json` and `root_sequence` is not specified in the primary JSON then it uses the separate JSON as reference.

How does this sound @rneher, @emmahodcroft, @jameshadfield?

**Comment by rneher** [comment]
> I preferred to place this at the top level of the JSON instead of within the root node of the tree because it felt like a more natural mirroring of the separate file option.
this is what we discussed earlier. 

We also discussed whether the "root_sequence": field should alternatively contain the name of the file to fetch.

**Comment by trvrb** [comment]
Yeah. Most of this is exactly what was discussed as a thread in #212. But some is new. I just wanted to get proposed behavior all down in one place.

>We also discussed whether the "root_sequence": field should alternatively contain the name of the file to fetch.

Here, I was going with @tsibley's suggestion that "Worth thinking about is that if the normal value is also a string, then it can become ambiguous if the value is a filename or not." Seemed cleaner to me to just always do a fetch call for `_root_sequence.json` like we do for `_tip-frequencies.json`. This has the added benefit that we don't have to wait a few seconds for the main JSON to load before sending the request.

Generally, I'm okay enforcing a naming convention on these auxiliary files (`zika_root-sequence.json`, `zika_tip-frequencies.json`, etc...)

**Comment by emmahodcroft** [comment]
I don't have too strong feelings on a lot of this, and think generally sounds good. I do think that colouring non-variable sites would be very useful, so I'd like to have this be a possibility in future.

> We choose JSON file name based on `--output`. In the case of `--output zika.json` and `--separate-root-sequence` we also output the file `zika_root-sequence.json`. This automatic naming seemed sensible to me as that is how auspice will need to look for this file anyway (ie it wouldn't make sense to have the option to name it something else).

I like this. I like `--output` and I think this is neater, especially when we want the file to be named a certain way anyway.

My only question:
> We include two new command line options `--separate-root-sequence` and `--include-root-sequence`. We do an intelligent default in which sequences over 50kb are automatically separated and sequences under 50kb are automatically included. This intelligent default can be overridden through the use of these flags.

Would then then force users to include non-variable sites, then? How I'm reading - the two options above are presented just as override options, but the intelligent default would be to always export a root sequence, but detect by size which way?

I 100% agree with intelligently detecting which to do by size - I certainly wouldn't want to try to figure it out myself. However, I'm not sure we necessarily always want to export the non-variable sites, either. For something like TB (or something even bigger) would this slow things down at all? All gene translations + all nucs might be a fair size to load. 

If that's a concern at all, I think it should be optional to have the root sequence (though whether opt-in or opt-out, I'm unsure). So maybe the argument could change to something like `--export-root-sequence` and have options 'nothing' (intellegently detect), `separate` and `include`. 

I'd also suggest maybe just calling it like it is - I'm not sure if it's obvious what exporting a root sequence would do. Maybe something like `--export-all-sites`? Though both would benefit from a good `--help` description. Don't have strong feelings on this, just a suggestion.

**Comment by jameshadfield** [comment]
> Seemed cleaner to me to just always do a fetch call for _root-sequence.json like we do for _tip-frequencies.json.

This would be my preference.

Assigning @trvrb @rneher @emmahodcroft to this - thanks in advance!

Note that auspice doesn't yet fetch or use the `_root-sequence.json` but it'd be pretty simple to implement in the future.

**Comment by emmahodcroft** [comment]
If we always do a fetch, am I understanding then that the file would always be separate? I personally think this would be easier and cleaner, and avoids the problems I detailed above for VCF. 

Would this then always export, then, and users can choose whether or not to 'upload' it (have it accessible by `auspice`) as they wish (maybe size/speed depending)? Or would it still be an export option?

If still an export option, my only remaining comment would be perhaps the option name. I am unsure if `--export-root-sequence` conveys what this allows you to do in `auspice` (see all bases on all sites - not just shows you the root sequence) unless you know how `auspice` 'reconstructs' the tree mutations.
