### ISSUE TITLE
V2 schema 'author' format feedback

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#343]
@jameshadfield ---

Some small thoughts on the current state of V2 schema for 'author' on the `v6` branch of augur. Here is an example attribute:

```
"author": {
  "author": "Theze et al",
  "journal": "Unpublished",
  "title": "Tracking Zika virus spread in Central America and Mexico using metagenomic sequencing",
  "value": "Theze b"
},
```

Generally, I think being explicit about `value` in the JSON is a great idea.

My suggestions are as follows:

~1. I much prefer the term "authors" to "author" in this case. In English, I would say: "The authors Theze et al find that..." I believe more appropriate to refer to these entries as the "authors" of a paper rather than the "author" of a paper. I think this also makes more sense for auspice display items like "Color By / Authors" and "Filter by Authors".~

_Keeping as `author` as discussed in the issue thread._

2. I don't like how the inclusion of year interacts with number of samples, ie:
<img width="880" alt="authors" src="https://user-images.githubusercontent.com/1176109/62428748-ea712780-b6b9-11e9-8912-59c2eadcab92.png">
It results in visual confusion both in terms of 2014 vs 1 and in terms of the use of parenthesis to enclose both counts and years. For this reason, I wouldn't use year in in constructing a `value` to disambiguate in auspice display. Here, I would also keep "et al", just because I think it's polite when referring to a paper to acknowledge co-authors (though admittedly the use of "et al" goes hand-in-hand with referring to this as "authors"). I would just do the disambiguation with A, B, C... as you do within year currently. My proposed styling would be "Barrows et al / A" and "Barrows et al / B", like so:
<img width="851" alt="authors-2" src="https://user-images.githubusercontent.com/1176109/62428959-117d2880-b6bd-11e9-9b08-51453c786539.png">

**Comment by jameshadfield** [comment]
Thanks for testing this @trvrb! 

`authors` was renamed `author` in line with bibtex syntax -- https://github.com/nextstrain/augur/pull/315/commits/67439602e4030bff9ee2ce5a2e89eecb1e41f095. It's an easy change and I have no objections either way.

The augur code which generates the `value` is here: https://github.com/nextstrain/augur/blob/v6/augur/export_v2.py#L348

Also worth bringing up again the potential bugs with this unique value here: https://github.com/nextstrain/augur/pull/315#issue-298282760

**Comment by trvrb** [comment]
Thanks James! I can play around with augur export for these values.

@rneher: I see now that `author` was your addition. Are you okay with moving back to `authors` for (my preferred) front-end behavior? We're really not hewing to bibtex at this point.

**Comment by rneher** [comment]
there two separate issues here:
 * what is the data structure for storing bibliographic information
 * how do we display it. 

the former, I suggested to align with bibtex since we were a few one-letter spelling difference away from bibtex. I figure going forward it would useful to specify bib info as a bibtex file instead of a table and it will be handy to just export from a ref-manager. 
Whether it reads filter by `author` or `Authors` is a completely separate issue and in my opinion depends on whether the majority of records are by a single author or not.

**Comment by trvrb** [comment]
@rneher ---

Thanks for the feedback. I know this is a small thing. However, my inclination would be hew to Genbank terms rather than bibtex for citation information. We pull author information via accession (and I don't see an easier way for other groups to do so either).

If we take another example, of https://www.ncbi.nlm.nih.gov/nuccore/KY785446. We currently have:
```
"author": {
  "author": "Metsky et al",
  "journal": "Nature 546 (7658), 411-415 (2017)",
  "paper_url": "https://www.ncbi.nlm.nih.gov/pubmed/28538734",
  "title": "Zika virus evolution and spread in the Americas",
  "value": "Metsky (2017)"
},
```
The Genbank entry lists fields as `AUTHORS`, `TITLE`, `JOURNAL` and `REFERENCE` (for PubMed reference ID).

So, thinking more about this as schema. Here's my proposed update:
```
"authors": {
  "authors": "Metsky et al",
  "journal": "Nature 546 (7658), 411-415 (2017)",
  "title": "Zika virus evolution and spread in the Americas",
  "value": "Metsky (2017)"
},
```
Considerations:
* I went back-and-forth on whether to name the block `citation` or `authors`. I went with `authors` instead of `citation` because this seemed to encompass things like GISAID naming better (where there isn't a literature citation for a sequence, instead it's more about provenance). Plus, this would push for saying "Color by citation" and "Filter by citation" and it seemed more natural to say "Color by authors" and "Filter by authors".
* I went back-and-forth on what to name `paper_url` (because we don't always have papers and paper is mentioned no where else here) and ended up just dropping it. It seemed likely to be confusing in terms of ingesting metadata. This would need to be called `paper_url`, or `authors_url` to distinguish it from the unique sequence `url`. I believe the sequence `url` is the thing to link out to in the pop-up and not the paper. Ie reducing possible confusion is better than keeping the ability to directly link out to paper.

I don't have strong feelings about either of these.

Finally, if Richard, you prefer:
```
"author": {
  "author": "Metsky et al",
```
I'm happy to be overridden on this. Sorry to make this a seemingly big deal.

------------------------------------

>I figure going forward it would useful to specify bib info as a bibtex file instead of a table and it will be handy to just export from a ref-manager.

👍🏻I'd imagine doing these sorts of operations upstream of metadata TSV. Otherwise it's a rather messy merge involving citekeys when exporting.

**Comment by rneher** [comment]
If genbank is the model, then we go ALL CAPS? I really don't think this is that critical and I don't care enough. the only point 4w ago was that the following
```
"author": {
  "author": "Metsky et al",
  "journal": "Nature 546 (7658), 411-415 (2017)",
  "paper_url": "https://www.ncbi.nlm.nih.gov/pubmed/28538734",
  "title": "Zika virus evolution and spread in the Americas",
  "value": "Metsky (2017)"
},
```
looks like bibtex -- a widely accepted format for this type of information. deviating from it by single letter changes seems silly. I also don't see why this needs to be reopened 4w later.

**Comment by trvrb** [comment]
Okay. Thanks Richard. This was part of an attempted comprehensive review of v2 schema while it's still malleable. Happy to keep it as `author`. I've edited original post to make this clear. I'd like to leave this issue open as I would like to try to attend to point 2 on `value` export from augur.

**Comment by emmahodcroft** [comment]
I don't really have strong feelings but personally I think the `paper_url` is useful. We do depend on metdata to have a bunch of 'magic' values, as discussed elsewhere, and I think the real solution is better docs to explain this, and long-term, an interactive script to help people get metdata in the right shape (this is half-baked on my computer but very dusty).

At the moment we handle this well, in that if you have it, you can link directly to the paper, but if not, it's not a big deal. I don't think it's too confusing and I think it's nice to have that functionality as an option. I can certainly see where linking directly to the papers for Enterovirus D68 cases that were reported to have AFM (there are only a handful, and many are case reports with lots of detail) would be of interest to people.

**Comment by trvrb** [comment]
Great! Thanks for the feedback Emma. This makes sense to me.
