### ISSUE TITLE
add test build with frequencies

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#355]
@huddlej i've had great success using a number of (quick) test builds for augur development -- see https://github.com/nextstrain/augur/tree/v6/tests/builds -- whichcan all be run via `bash runner.sh`. Could you add one such test build which produces a `_tip-frequencies.json` so that we can test builds which use the frequencies panel. Cheers 🙏

**Comment by trvrb** [comment]
`tip-frequencies.json` export could just be added to `zika` test build as well.

**Comment by jameshadfield** [comment]
Closed by 9287b42ec79bbb1c025eea2982e4a577efef0128
