### ISSUE TITLE
How are N's handled in augur?

### ISSUE THREAD

**Issue by RaSieb** [nextstrain/augur#358]
Hi
Thanks a lot for this great tool! I'm really keen on finalising an analysis on bacterial evolution with nextstrain, but have a question about the handling of N's in the input fast file. 

Because the species I'm working with is characterised by a rather high level of recombination, the matrix of called SNP's is run through gubbins which replaces SNP's in regions identified as originating from recombination by N's, leaving a mosaic of actual SNP's and N's in the final matrix, which I would like to use with Nextstrain.

I have tried both the N-related flags `--keep-ambiguous` and `--keep-overhangs` as mentioned in issue #352 , and compared the results to a matrix where the N's were replaced by dashes ("-"). The results differ significantly, with a much earlier MRCA in the analysis with N's, indicating that they somehow are considered an extra stat. 
So how are N's handled in augur/treetime? (I am using the --treetime flag). I also attach my [Snakefile.txt](https://github.com/nextstrain/augur/files/3520749/Snakefile.txt) here for your information. 

Thanks a lot in advance for any clarification.

**Comment by emmahodcroft** [comment]
Hi RaSieb, thanks for getting in touch!

I see you are using Fasta input now, but have tried VCF.

Generally, N's are treated as ambiguous bases in `augur`, and if you run `refine` and/or `ancestral`, Treetime (the program which works behind the scenes) will try to infer their state. 

If other tip sequences in your tree have a non-N base at this location, this will inform what's inferred.

Using `--keep-overhangs` in `ancestral` with Fasta-input means that if you have gap "padding" on either side of your sequences (a common practice for some aligners), this won't be treated as Ns, but left as gaps. As you're working with N's this shouldn't really apply (except if they are the ends of the sequence when you try converting the Ns to gaps).  
I'll be honest, I'm not sure what this flag does if you are using VCF-input - very possibly nothing!

The flag `--keep-ambiguous` in `ancestral` will mean that after inferring the state of N-bases on internal nodes and on the tips, the bases that were originally N on the tips will be replaced with N again. (So, the tip sequences are not modified at ambiguous sites.) However, the ancestral sequences will still have bases inferred at N sites. 

And, perhaps more importantly, all of this (sequence reconstruction) essentially happens behind-the-scenes during `refine`, even though no ancestral sequences are output. But, the software is keeping track of changes in the ambiguous bases over the tree/time and how they impact the tree estimation. There's no way to _not_ have ambiguous/N bases inferred during `refine`. 

If all of your sequences have N at a particular site, then I'm a little surprised the tree differs so much and would like to investigate further. _(Please let me know)_ If some have Ns and some have 'real' bases at the same site, then I am not surprised this is influencing your tree. (Though I accept this is not so intuitive and probably a bit annoying!)

Here are a couple suggestions for how you might want to handle this, depending on the format and whether you want to include the position or not:

- Fasta input
  - Include position (ex: not all bases are N at this location) - turn all Ns into gaps; this will at least stop bases from being inferred
  - Exclude position (ex: all are Ns) - remove the site entirely from your alignment (if it's a SNP concatenation this isn't problematic)
- VCF input
  - Include position (ex: not all bases are N at this location) - turn all Ns into gaps, as above
  - Exclude position (ex: all are Ns) - use `mask` to remove these locations from the analysis entirely. (This will set them all to the reference base at this position, so they are no longer informative for tree-building.)

I hope this helps, but please reach out again if anything is unclear or if you'd like to go a bit more in-depth!

**Comment by RaSieb** [comment]
Hi Emma
Thanks a lot for your help and the quick reply. 

My alignment does not contain sites with all N, so the positions should all be included. And since gubbins does not handle vcf files, i'll stick with the fasta input and replace the N's with gaps. 

Thanks again for the great tool!

**Comment by rneher** [comment]
One thing to note here is that sites where you have only one state and otherwise only N are essentially treated as non-variable (there is no evidence for variation). This is different when you replace these positions with gaps. I assume your clock rate estimate is based on the branch length output by iqtree, right? I would add the flag `--branch-length-inference input` to the refine step to ensure that no additional branch length optimization is done.

**Comment by RaSieb** [comment]
How are such sites of only one state treated when N's are replaced by gaps then? Our clock rate is taken from the literature, so not inferred from our data, as recommended in the documentation for treetime. Should the `--branch-length-inference input` statement still be used then?
