### ISSUE TITLE
H7N9 scripts and outputs are not named or organized consistently with other viruses

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#36]
While writing code to automate builds of all nextstrain virus sites, I noticed several inconsistencies between H7N9 and other viruses:

- [x] fauna commands refer to “h7n9” while augur refers to “H7N9”
- [x] prepare and process scripts are not consistently named like the other viruses using “prepare.H7N9.py” instead of “H7N9.prepare.py”, for instance
- [x] H7N9’s prepare script builds all eight of its segments at once without providing any `--segments` argument
- [x] Output files from prepare and process add an “avian_” prefix even though there isn’t a higher level “avian” virus directory structure in augur like there is for “flu”

Renaming the prepare and process scripts should address the first two issues without significantly affecting the output from the scripts. Adding a `--segments` argument with a default to all eight segments should similarly avoid regressions while allowing users to specify one or more segments.

The last issue might involve a more significant structural change. It seems like it would make more sense for the H7N9 scripts and data to be grouped under an "avian" directory much like the "flu" scripts and data are. Then the prepare and process scripts would look like "avian.prepare.py" and would accept a `--lineage` argument to allow users to specify "h7n9" just as they can specify "h3n2" for flu now. These changes would make the augur side of the analysis consistent with the naming hierarchy in auspice where "avian" is the top-level virus and "h7n9" is a lineage within that heading.

Since this code is mostly maintained by @jameshadfield, what do you think about these changes? @trvrb might be interested, too.

**Comment by jameshadfield** [comment]
sounds good to me - keep h7n9 lowercase where possible as either the auspice fetch calls make things lowercase or S3 is lowercase. Moving to "avian" folder is fine.

**Comment by huddlej** [comment]
This issue was resolved by commits 931afb6 and 44a6110.
