### ISSUE TITLE
v1 export using v2 config files fails

### ISSUE THREAD

**Issue by rneher** [nextstrain/augur#373]
this is like not a case we want to support, but it would be good to warn the user that this doesn't work. If one attempts to do this, one currently gets meta.json that contain stuff like this:
```
"geo": {}, "geo_resolutions": [{"key": "country"}, {"key": "region"}]
 "color_options": null, "colorings": {"cTiter": {"key": "cTiter", "title": "Antigenic advance (tree model)", "type": "continuous"},..."
```

**Comment by emmahodcroft** [comment]
I imagine this would be a common mistake people could make as they switch over, and it would be fairly easy to check for terms like `geo_resolutions` and `colorings` and warn the user it looks like they're using a V2 config in V1 export - will probably be v. helpful for them figuring out where they went wrong!
