### ISSUE TITLE
Colors File Should be Tab-Delimited

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/augur#376]
I don't know if we officially declare anywhere that the `colors` file should be tab-delimited, but it seems we possibly should move that way.

We can now handle trait values on nodes with spaces in the value - and particular with the move to `v6` `augur` and `auspice` `2.0`, we will no longer 'prettify' things, so if you want "New Zealand" to display like that (rather than "New_Zealand"), you need to have it with a space, not underscore.

However, we parse our `colors` file (in utils.py) splitting just by whitespace. Traits with spaces in the name mess this up. 

If I change to split by tab, it then can't read the default `colors` file with the regions (this isn't tab-delimited, I guess), so this file would need to change too.

This isn't a difficult fix, but we'd need to ensure it doesn't mess up anything backwards-compatibility-wise. 
And should we fix for `master` `augur` (v1) or just `v6` `augur`?

**Comment by trvrb** [comment]
I agree with moving to proper tab-delimited files for `colors.tsv` and `lat-longs.tsv`.

**Comment by tsibley** [comment]
I very much want to use proper TSV or CSV files for this. We can support both formats by relying on Pandas' auto-detection with `pandas.parse_csv(…, sep = None)`.

I'd also like to include headers so the columns are self-describing and re-orderable.

I think any change that's backwards-compat will mean we could support it in both 5.x (`master`) and 6.x (`v6`), but we might only want to include in 6.x.

**Comment by jameshadfield** [comment]
I believe this has been resolved in augur v6. Please elaborate if not (and remove the label accordingly!)
