### ISSUE TITLE
Author Filter in 1.0 Looks Not Nice

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/augur#377]
When adding an `authors` filter in a V1 JSON file and viewing on the current Nextstrain.org server (`auspice` 1.0), the authors look not-so-good. I don't think this an `augur export` problem, as the author format is the same here as in an export from Jan 2019. 

![image](https://user-images.githubusercontent.com/14290674/64267153-28ba6a80-cf36-11e9-8337-5de9d259b62d.png)

Can see this behaviour here:
https://nextstrain.org/community/emmahodcroft/tb/enterovirusd68-vp1/aug19

**Comment by emmahodcroft** [comment]
To update on this - the flu example above actually matches what shows up on the Live Site, just without prettifying:

Live site:
![image](https://user-images.githubusercontent.com/14290674/65779288-caa13180-e147-11e9-93a4-0d0e06a0496a.png)

Heroku:
![image](https://user-images.githubusercontent.com/14290674/65779308-d12fa900-e147-11e9-9df4-13196760e8b7.png)

So this particular situation may be a case of ensuring we Prettify old V1 files properly.

**Comment by emmahodcroft** [comment]
I've ended up a bit confused over this. As far as I can tell, `augur export` (`v5`) "v1" export ("nextflu" or default when running `v5`) doesn't modify the author information (shortening author list etc) before exporting - is this correct?

So, whatever you have as your author list in your metadata is the 'key' in the JSON. If `auspice` is just going to display that as-is, then everything is happening as expected from the code:

Metadata (long author lists pulled directly from GenBank):
![image](https://user-images.githubusercontent.com/14290674/65783527-430bf080-e150-11e9-82a0-5c373ba3904d.png)

Meta JSON (run in `augur` `v5` with `export` (so v1):
![image](https://user-images.githubusercontent.com/14290674/65783562-56b75700-e150-11e9-9638-3761008ffb77.png)

View using `auspice` `v1` (see [here](https://nextstrain.org/community/emmahodcroft/tb/enterovirusd68-vp1/aug19)):
![image](https://user-images.githubusercontent.com/14290674/65783611-6df64480-e150-11e9-8fe0-8d4c1763ba7a.png)


Did we used to modify this in `auspice`? I think I remember it being prettier? But as far as I can tell the code is doing what I expect.

I find this is exactly the same if I run `augur` `v6` `export v1`. 

----

I don't know what data goes into the Flu builds, myself, but it seems like we've stopped prettifying authors in `auspice` `v2`. So viewing some flu on a [live build](https://nextstrain.org/flu/seasonal/h3n2/ha/2y):
![image](https://user-images.githubusercontent.com/14290674/65783750-be6da200-e150-11e9-91f8-8ba40d28d153.png)

And on [Heroku](https://nextstrain-dev.herokuapp.com/flu/seasonal/h3n2/ha/2y?c=weighted_distance_to_future):
![image](https://user-images.githubusercontent.com/14290674/65783785-d8a78000-e150-11e9-9422-2f049aa5db80.png)

We should probably keep prettifying V1 author data that comes in like this, like we continue to prettify other V1 things.

**Comment by emmahodcroft** [comment]
I also don't see any real difference in EV-D68 in `augur` `v6` `export v2`:
![image](https://user-images.githubusercontent.com/14290674/65785401-941de380-e154-11e9-80e9-879de28707c5.png)

On close inspection, some things that were grouped together in `v1` exports are now separated into A and B, but the author lists are still huge (so you can't even realistically see this difference).

**Comment by emmahodcroft** [comment]
So - what *should* author filters look like? 

Is this indeed behaving as expected (but just ugly) or have I missed something?

If it's behaving as expected, it's just that my stuff has super long author lists, is this what we want? I'd vote no. I'm pulling my author lists directly from GenBank, but I think this should be ok - we should be able to handle long author lists better than this, I think.

**Comment by trvrb** [comment]
(I'm sorry if I'm not completely following...) But I believe that augur should properly convert names to just "Hodcroft et al". I had thought that https://github.com/nextstrain/augur/pull/347 sorted this.

I believe the best fix to the flu issue is to rename this metadata column as "submitting lab", which is what it should be anyway.

**Comment by emmahodcroft** [comment]
So this was kind of my impression as well. (Though I started doubting myself working through this!)

But doesn't seem to be the case with the EV-D68 data, anyway. It's getting late here now but I can try to take another look on the weekend or Monday. At a glance, I can't see where it should be splitting down to just first author last name, though.

If you have any ideas as to why it's not working, I'd appreciate it thought!

**Comment by trvrb** [comment]
Can you share EV-68 fasta and metadata so I can test?

**Comment by trvrb** [comment]
I'm going to go ahead and close this issue. Author list looks not great in old V1 export. I don't think worth it going back and fixing this when we've moved on.
