### ISSUE TITLE
Provide consistent minimal interface for all virus prepare scripts

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#38]
There is some variation in the arguments provided by each virus's prepare.py script from 1 argument available in `ebola.prepare.py` to 9 in `flu.prepare.py`. For automated execution of augur scripts, it would be useful if each prepare script provided the same few options to the user include:

  * `--sequences`: one or more FASTA files to use for analysis
  * `--auspice_prefix`: a prefix for all auspice output files to allow automated scripts to predictably name output as desired
  * `--viruses_per_month` or `-v`: the number of viruses per month to sample; this exists for most scripts but the long form of this option for flu is named `--viruses_per_month_seq`

**Comment by trvrb** [comment]
I believe that PR #39 resolved this issue. Closing. @huddlej please re-open if I'm mistaken.
