### ISSUE TITLE
Indentation of exported JSONs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#395]
Currently, the indentation of (most) JSONs written by augur uses an indentation level of 1, or None if `AUGUR_MINIFY_JSON` is set -- see https://github.com/nextstrain/augur/blame/master/augur/utils.py#L199.

The current implementation of augur export (augur versions v5 + v6) use a different approach, obeying the `--minify-json` argument _not_ the env variable, and using an indentation of 2 if this is not set -- see https://github.com/nextstrain/augur/blame/master/augur/export.py#L469. 

@huddlej what's best to do here? should we minify jsons if _either_ the env variable or the argument is set? 

Perhaps separately I also prefer default indentation levels of 2, @tsibley did you choose 1  for a particular reason?

**Comment by tsibley** [comment]
@jameshadfield I didn't choose 1. That was the existing default.

**Comment by tsibley** [comment]
(Using an indent of 1 goes all the way back to the first commit to this repo in 2016.)

**Comment by trvrb** [comment]
I chose 1 I think because the trees generated heavily nested structures and using 2 padded things out in an even worse fashion. (No real preference on how things should behave now)

**Comment by jameshadfield** [comment]
Great, i'm going to go with a default indentation of 2 for augur v6 unless there are objections, since exported tree JSONs have been using 2 for a long time now (augur v5 and probably earlier).  

Will make `augur export ...` minify jsons if _either_ the env variable or the argument is set, but that's easy to change back to the current behavior if desired.

**Comment by trvrb** [comment]
Great. I agree with minifying if either env or argument is set.
