### ISSUE TITLE
Filters title in Auspice config JSON

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#399]
@jameshadfield @emmahodcroft ---

I've been working through upgrading to `export v2` across existing builds (https://github.com/nextstrain/augur/issues/334#issuecomment-552014597) and noticed an inconsistency in Auspice config JSON. 

Currently, `geo_resolutions` and `colorings` allow for both `key` and `title`. This is useful at the minimum to have capitalized titles in Auspice. However, `filters` does not allow for this instead taking just a list of strings, ie:

```
  "filters": [
    "country", "region", "author"
  ]
```

I would suggest making this work similarly to `geo_resolutions` so that this is allowed:

```
  "geo_resolutions": [
    { "key": "country", "title": "Country Custom Title" },
    { "key": "region"}
  ],
```

(I figured out that I could capitalize filters by also including as a color by, but this was unexpected behavior and we may have situations where we want an attribute as a filter, but not as a coloring)

**Comment by jameshadfield** [comment]
Auspice, when displaying filters (or attributes in the tip-clicked panel etc), checks to see if the filter is also a coloring with a title and uses that if so. I don't believe we can switch the filters to a different structure without modifying the [JSON schema](https://github.com/nextstrain/augur/blob/v6/augur/data/schema-export-v2.json#L83) in a non-backward compatible way.

Given that tables may be arriving soon, which will need to define available metadata that's not necessarily a coloring, perhaps we could use this JSON structure to define filter titles in a backwards-compatible fashion.

**Comment by trvrb** [comment]
I'm sure about best path forward. I am finding it slightly frustrating (but not hugely so) that I'm forced to include "submitting lab" and "originating lab" colorings for seasonal flu when I only want these as filters and not as colorings. And if I run with #402, they show up but are not properly capitalized.

**Comment by jameshadfield** [comment]
Possible solutions are: adding a `hidden` property to colorings, which was previously brought up in regards to auspice displaying multi-color-bys, or preset-panels of color-bys. Or accepting the slightly less-than-ideal

**Comment by trvrb** [comment]
If this is too much of a headache (which is just fine), my workaround would be to just close #402 and enforce colorings exist for all filters (and document that this is the case). And possibly use `hidden` once / if this exists.

**Comment by jameshadfield** [comment]
If #402 goes in (which I think it should), the issue here is that filters-which-aren't-color-bys will have string formatting that's not ideal? A solution to this would be to rename the metadata trait `submitting_lab` to `Submitting Lab` in the metadata TSV & the filters array.

**Comment by trvrb** [comment]
Clever, but I don't think I like this. I want my field names to be a particular format (and I suspect others do as well). My inclination is still to close #402 and just be okay thinking of filters as tied to a coloring. The cost is a couple extra colorings, but it avoids a bunch of edge cases. Ie I'd be more annoyed with forcing `Submitting Lab` in my metadata.tsv than having to include submitting lab as a coloring.

**Comment by jameshadfield** [comment]
Sure, no problem. But I don't think these are exclusive. One can have #402 and, if one wants to (a) keep field names a particular format in the TSV and (b) wants these to be rendered differently in auspice, then they can make them a coloring. 

(Note that making filters be colorings doesn't enforce that the strings will appear "pretty" -- one could always include a coloring for the `submitting_lab` key _without_ a title.)

**Comment by trvrb** [comment]
This makes sense. My own preferences would be to have pretty strings and so would make these a coloring to accommodate this. Others may prefer title cased metadata fields or be okay with lowercase display strings.

**Comment by trvrb** [comment]
I'm going to close this issue. I'm not sure it's worth dealing with at this point.
