### ISSUE TITLE
pip install fails on python 3.8

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#413]
running `pip install nextstrain-augur` from python 3.8.0, pip 19.3.1 (both installed via conda using http://data.nextstrain.org/nextstrain.yml but specifying python 3.8) on MacOS fails:

```
Building wheels for collected packages: datrie, matplotlib
  Building wheel for datrie (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/naboo/miniconda3/envs/nextstrain38/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ll/jk3j22jn2nscbh6rmm7c9c8h0000gp/T/pip-install-p0stu9dc/datrie/setup.py'"'"'; __file__='"'"'/private/var/folders/ll/jk3j22jn2nscbh6rmm7c9c8h0000gp/T/pip-install-p0stu9dc/datrie/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/ll/jk3j22jn2nscbh6rmm7c9c8h0000gp/T/pip-wheel-ksjqxpzh --python-tag cp38
...
error: command 'gcc' failed with exit status 1
```

This is using the system `gcc` (Apple LLVM version 10.0.1 (clang-1001.0.46.4)) however adding gcc 4.8.5 via conda does not change this error. (I remember discussion about this, but perhaps related to another project.)

**Comment by tsibley** [comment]
My guess is that datrie only installs on 3.6 without a compiler because there's a macOS Python 3.6 wheel (pre-compiled binary package) for it [on PyPi](https://pypi.org/project/datrie/#files). There is not one for 3.8.

Additional context I wrote in Slack that also seems relevant:

> The gcc errors when installing datrie and others is why I want to put a compiler in the Conda env, to avoid issues like that. I have a wip for that from a month or more ago I was testing on different platforms, but haven't gotten back it.)
>
> Pip will try to use binary packages if available, but their availability is subject to a lot of conditions out of our control, so a compiler is nice to have. datrie has binary packages for 3.6 but not 3.8, for example.

**Comment by willingc** [comment]
@tacaswell FYI This issue will likely benefit from your work re: datrie https://github.com/pytries/datrie/pull/78#issuecomment-603545922

**Comment by tacaswell** [comment]
If you are willing to install from conda-forge, you can get datrie for py38 for all platforms now.

**Comment by tacaswell** [comment]
datrie 0.8.2 is now an pypi (with wheels for all platforms) and will install on py38.  This issue can be closed.

**Comment by jameshadfield** [comment]
Tested & working via install into a py38 conda environment. Thanks all!
