### ISSUE TITLE
Infer numeric type for augur distance output from default and site weights

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#427]
When the augur distance command reads a distance map JSON, [it checks the numeric type of the default mismatch value](https://github.com/nextstrain/augur/blob/92f58c8/augur/distance.py#L249-L250) and converts all calculated distances to this type. Although this is [the documented behavior](https://nextstrain-augur.readthedocs.io/en/stable/api/augur.distance.html#distance-maps), it has actually led to issues in my own analyses where I thoughtlessly use an integer default of `0` for a distance map with float weights. This led to silently truncating distances from floats to integers.

One strategy would be to at least warn the user or throw an error when there is a mismatch between the default type and the site weights. A better approach would be to use the simplest type based on all user-provided numbers in the map (the default value and site weights). If any site weight or the default is a float, the outputs will always be floats. If all values are integers, the outputs will always be integers.

The main reason to continue using this type-aware behavior instead of always outputting floats is to minimize disk/memory usage for large data sets or downstream conversion of augur distance outputs to integers.

**Comment by CameronDevine** [comment]
Checking the entire map for the presence of a `float` weight could become a computational burden. What about adding a keyword argument to the function?

```python
def get_distance_between_nodes(node_a_sequences,
                               node_b_sequences,
                               distance_map,
                               output_type=float):
```

This keyword argument could be used to more explicitly define what type the function should output. This argument could also take a value of `None` by default, and revert to the old method to maintain backwards compatability.

**Comment by huddlej** [comment]
Possible solutions include:

  - Always using `float`
  - Supporting `output_type` in the distance map
  - Supporting an output precision in the distance map like [pandas.to_csv does with `float_format`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html?highlight=to_csv#pandas-dataframe-to-csv)

**Comment by huddlej** [comment]
Here is a test that will currently fail but should pass after we address this issue (running in [this context](https://github.com/nextstrain/augur/blob/92f58c85f670f16d8cac5cbb321bb84840e1c1db/augur/distance.py#L242-L244)):

```python
>>> distance_map = {"default": 0, "map": {"gene": {2: {('T', 'G'): 0.5}}}}
>>> get_distance_between_nodes(node_a_sequences, node_b_sequences, distance_map)
    0.5
```

This will currently return `0`.
