### ISSUE TITLE
update treetime

### ISSUE THREAD

**Issue by rneher** [nextstrain/augur#429]
I'll soon release TreeTime 0.7. Most changes are internal, but some might affect augur since augur at times reaches deep into the "internals" of TreeTime. I have been running augur without problem using TT 0.7 but it should be tested more broadly. Two changes in particular might change some of augur's behavior:
 - TreeTime no longer reconstructs ambiguous sequence of tips by default. This behavior was unexpected to most and after separating input and inferred sequence more cleanly in TT this seemed obvious to change. For the mugration analysis, however, tip reconstruction might be of interest. 
 - The overall mugration rate is now estimated numerically instead of relying on the linear approximation -- at least in the `treetime mugration` command. We probably would want to do this as well in `augur traits`.

**Comment by rneher** [comment]
just ran a few tests. One test fails here:
https://github.com/nextstrain/augur/blob/master/augur/traits.py#L75
This is no longer allowed since `node.sequence` is now a protected attribute that you can't set from the outside.

This could either be fixed by using the same construction as done here
https://github.com/nextstrain/augur/blob/master/augur/traits.py#L75

or by replacing the entire logic by 
https://github.com/neherlab/treetime/blob/master/treetime/wrappers.py#L678

**Comment by jameshadfield** [comment]
Released with 6.3.0
