### ISSUE TITLE
Geo coordinate format

### ISSUE THREAD

**Issue by rneher** [nextstrain/augur#430]
The way we specify latitude and longitude in augur is not robust. Once we go below country level, we are bound to have clashes (e.g., Georgia and Georgia), cities will be a complete nightmare (Athens!!!). Tuples like (country, division, city) will be mostly ok, though. This issue is made worth by our pattern of replacing missing division, city etc by the country names. (West Asia, Georgia, Georgia, Georgia). 

If we want to continue to ship latitudes and longitudes with augur, we will at some point have to rethink this. Any thoughts?

(I came think about this in the context of providing coordinates for all division levels in the flu db)

**Comment by jameshadfield** [comment]
This will also apply to auspice but be even worse! One solution (for auspice) which wouldn't require modifications to the JSON schemas is to identify such collisions and rename the exported deme name to "City, Country" (or "City, State, Country" as needed).

**Comment by rneher** [comment]
One way to address this is to move to a format
```
{(country, division, city):{'region':'XYZ, 'latitude':12.3242343, ..., 'avg temperature':sdfs}
# lower resolution
{(country, division, None):{'region':'XYZ, 'latitude':12.3242343}
# lower resolution
{(country, None, None):{'region':'XYZ, 'latitude':12.3242343}
```
But then we need an additional structure for regions or other geographic entities that are not countries. I am trying to avoid having regions be a level above countries since countries like Russia are part of several regions. Similar things can be said for Chile or the US when it comes to climate zones.  So different divisions should be able to be part of different regions. 

hence I am envisioning separate structures for `places` and `geo-groupings`.

**Comment by tsibley** [comment]
(Been meaning to respond to this for a while…)

> One solution (for auspice) which wouldn't require modifications to the JSON schemas is to identify such collisions and rename the exported deme name to "City, Country" (or "City, State, Country" as needed).

This is [the approach I took in ID3C's location catalog](https://github.com/seattleflu/id3c/blob/5a456d6f10953edf9e43da2f00aacda43f361a19/schema/deploy/warehouse/location.sql#L21-L25). It has the advantage of simplicity and matches how humans disambiguate anyway, and it doesn't preclude more sophisticated approaches in the future.

If we want an initially more complex approach, say with more formalized nesting structure, then I'd recommend following the examples of existing place catalogs like [Who's on First](https://whosonfirst.org/) ([documentation and commentary](https://whosonfirst.org/docs/)) or Google Places. The general principle here is like any catalog: human-readable identifiers (plural) are mapped (automatically with hueristics or manually) to stable catalog identifiers that are associated with rich metadata records for display purposes.

**Comment by nitfer** [comment]
"City, State, Country" isn't necessarily enough.  There are some cities that are duplicated within states and you need to specify the County to disambiguate.

It's really difficult to get a general solution to geographic areas because different countries organize things in different ways.  But "Who's on First" (which I never heard of before now) actually looks pretty flexible.

**Comment by tsibley** [comment]
> "City, State, Country" isn't necessarily enough. There are some cities that are duplicated within states and you need to specify the County to disambiguate.

Yep! :-) This is where using a database with uniqueness constraints can be handy since it'll automatically alert you to that problem, unlike a collection of flat files. So most of the time you can use the simplest identifier and only disambiguate with additional information (like county) when needed. Of course, it's always possible to add similar QC processes on top of flat files, but more work.

**Comment by trvrb** [comment]
I'm going to close this. We have a system for `ncov` with 4979 lat/long entries. We may think of a better approach here, but I don't think it's high priority.
