### ISSUE TITLE
Filter Count Buggy if `include.txt` has empty line

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/augur#433]
When running `augur filter` if the `--include` file has one empty line, the screen output will erroneously count this as a sequence being added back in - even though in reality nothing happens.

With an `include` file that has one empty line, here's the output:
![image](https://user-images.githubusercontent.com/14290674/73013247-3bb3d580-3e18-11ea-90a1-f05bdc986a2c.png)
In reality, only 325 samples were written out - as it should have been.

If you remove the blank line from `include` then the result is this:
![image](https://user-images.githubusercontent.com/14290674/73013289-4ec6a580-3e18-11ea-88b5-89558730c8e6.png)

The resulting fasta files are the same, but the text output is misleading.

**Comment by huddlej** [comment]
Closed by #451
