### ISSUE TITLE
Troubles with augur -refine

### ISSUE THREAD

**Issue by Stygiophobic** [nextstrain/augur#434]
Hi there,

I'm trying to make a build for our lab, but I'm currently stuck with the refine command;
 ```
   augur refine \
            --tree /path/meta_H1N1_S4.raw.nwk  \
            --alignment /path/meta_H1N1_S4.aligned.fasta \
            --metadata /path/meta_H1N1_S4.tsv \
            --timetree \
            --output-tree /path/meta_H1N1_S4.nwk \
            --output-node-data /path/meta_H1N1_S4.branch.lengths.json  
``` 
I get a python error: 

>  raise LinAlgError("Singular matrix")
> numpy.linalg.LinAlgError: Singular matrix

I dont realy know what to check, because I also generating an other bunch of couple files for the others Influenza subtypes (H3N2 etc...) which are working  fine with the same command.

How can I check the sanity of my raw tree and aligned.fasta file? 

Thx:)

**Comment by rneher** [comment]
sorry it has taken so long... could it be that all your dates are the same? In this case, you need to provide a clock rate.

**Comment by trvrb** [comment]
I hope you were able to resolve your problem @Stygiophobic. I'm closing this issue now, but please reopen if it's still an issue.
