### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by MarHayat** [nextstrain/augur#439]
I have installed augur successfully but I keep getting the invalid syntax error each time. As I checked the error is because of using python 3.7 and it is fixed for version<3.6. I was wondering if there is any update regarding the new version?

**Comment by tsibley** [comment]
Hi @MarHayat. I'm sorry you're having trouble using Augur. I'm not sure what invalid syntax error you're seeing; could you copy and paste it here along with the command you're running when you see it? We'll try to get the problem sorted out.

**Comment by CameronDevine** [comment]
I didn't have any issues installing augur with Python 3.7, but trying to install it with Python 3.8 I ran into this issue, pytries/datrie#73.

**Comment by jameshadfield** [comment]
@CameronDevine see https://github.com/nextstrain/augur/issues/413 for the issue about datrie on 3.8. Thanks for testing!

@MarHayat I'm going to close this now. Please reopen if you're still having this issue and copy&paste the error here for us. Thanks!
