### ISSUE TITLE
augur align warning with --reference-sequence 

### ISSUE THREAD

**Issue by MarHayat** [nextstrain/augur#457]
Hello, 

I keep getting warning while using augur align to align a set of sequences with the reference "reference_h3n2_ha.gb". The warning is: 
WARNING: Cannot read reference sequence.
	make sure the file ~/reference_h3n2_ha.gb  does not exist
The command is: 
python3 -m augur align --sequences ~/Data/final_data.fasta --reference-sequence ~/Data/reference_h3n2_ha.gb  --fill-gaps

Can you please let me know how can I fix this problem?

**Comment by danielsoneg** [comment]
Hey @MarHayat , two quick things - 
First, looks like you're using an older version of augur - might be worth an update.

Second - that error means that augur can't find the filename you passed to `--reference-sequence` - check you've got the correct path for that file.

**Comment by MarHayat** [comment]
@danielsoneg Thanks!
First, I have updated it, and now I am working with version 6.4.2. 
Second, I am sure about the path and it is correct. 
with this new version I got this error:
ERROR: Cannot read reference sequence.
	make sure the file "reference_h3n2_ha.gb " exists
Is there any restriction on the size of the data? I have around 63000 sequences.

**Comment by danielsoneg** [comment]
No, that error solely indicates that the path for the reference sequence file is incorrect. Make sure you're passing the full and correct path to `--reference-sequence` (and you may want to put the path in quotes as well)

**Comment by MarHayat** [comment]
I checked the path several times and I am sure that it is correct. Both the reference sequence and the sequences "final_data.fasta" are in the same directory. It can read the "final_data.fasta" but cannot find the reference sequence.

**Comment by danielsoneg** [comment]
So the code path that generates that error is just checking whether the path given is a file - from [augur/augur.align:](https://github.com/nextstrain/augur/blob/master/augur/align.py#L165-L168)
```python
def read_reference(ref_fname):
    if not os.path.isfile(ref_fname):
        raise AlignmentError("ERROR: Cannot read reference sequence."
                             "\n\tmake sure the file \"%s\" exists"%ref_fname)
```
Per the [python docs](https://docs.python.org/3.5/library/os.path.html#os.path.isfile), `os.path.isfile` returns true if the file is an "existing regular file."

That function gets passed the supplied path name directly either on line [57](https://github.com/nextstrain/augur/blob/master/augur/align.py#L57) or [71](https://github.com/nextstrain/augur/blob/master/augur/align.py#L71) (the call is the same for either path):
```python
            ref_seq = read_reference(args.reference_sequence)
```

At this point the best I can suggest is to copy the files to a different directory and try loading them from there - you've either got a typo in the command or a really weird OS error, and hopefully moving the files will suss out which one it is.

One quick note - in your initial comment, you pasted in the error as:
> WARNING: Cannot read reference sequence.
> make sure the file **`~/reference_h3n2_ha.gb`**  does not exist
and the command in as:
> python3 -m augur align --sequences ~/Data/final_data.fasta --reference-sequence **`~/Data/reference_h3n2_ha.gb`**  --fill-gaps
Note that the path referenced in the error is not the same as the path referenced in the command - the error is missing the "~/Data/" folder name

**Comment by MarHayat** [comment]
initially, the reference file was in another directory then I moved it in the same directory as the sequences. I tried to put both files in a new directory but I got the same error. Now, I am going to run it on another system to see if it works or not.

**Comment by MarHayat** [comment]
Ok, it seems that the problem is with my system since it works in another system. Thanks for your help.

**Comment by willingc** [comment]
@huddlej @danielsoneg Looks like this issue is resolved and can be closed.

**Comment by huddlej** [comment]
Thanks for the head's up, @willingc! Closing now.
