### ISSUE TITLE
augur export example in zika tutorial now working

### ISSUE THREAD

**Issue by philippmuench** [nextstrain/augur#460]
I followed the tutorial from [here](https://nextstrain.org/docs/tutorials/zika/) and on the `augur export` step I get an the error (augur 6.4.2)

```
Augur export now needs you to define the JSON version you
                    want, e.g. `augur export v2`. ...
```

when using `augur export v2` I dont see the option to export both, the tree and the metadata which I would need to start `nextstrain view`. I also tried to download the datasets directly e.g. from [http://data.nextstrain.org/ncov.json](http://data.nextstrain.org/ncov.json) but the site seem to be down.

Thanks!

**Comment by huddlej** [comment]
@philippmuench Thank you for catching this. We already have [an open issue for this bug on the nextstrain.org repository](https://github.com/nextstrain/nextstrain.org/issues/83).

You can find the [correct documentation for the tutorial in the augur documentation](https://nextstrain-augur.readthedocs.io/en/latest/tutorials/zika_tutorial.html).
