### ISSUE TITLE
fill_gaps without reference name

### ISSUE THREAD

**Issue by tolot27** [nextstrain/augur#462]
I wonder whether [`make_gaps_ambiguous`](https://github.com/nextstrain/augur/blob/9d95ec71c12062ebc5506bbc2b6a17540a6b247b/augur/align.py#L108) works correctly, if no reference (strain) name is provided to `augur align`. The referenced code looks like as if `seqs` still contains the original sequences or an existing alignment but not the newly generated alignment generated in line 91.

Please can you verify this?

**Comment by tolot27** [comment]
If neither `--reference-sequence` nor `--reference-name` is provided to `augur align`, the following error is thrown:

```
Traceback (most recent call last):
  File "/usr/local/bin/augur", line 9, in <module>
    load_entry_point('nextstrain-augur', 'console_scripts', 'augur')()
  File "/mnt/c/Develop/augur/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/mnt/c/Develop/augur/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/mnt/c/Develop/augur/augur/align.py", line 108, in run
    make_gaps_ambiguous(seqs)
  File "/mnt/c/Develop/augur/augur/align.py", line 254, in make_gaps_ambiguous
    seq.seq = Seq.Seq("".join(seq_array))
TypeError: can only join an iterable
```

**Comment by tolot27** [comment]
I suggest that `write_uppercase_alignment_in_place` returns the alignment without writing on it back to disk. Than `strip_non_reference` and `make_gaps_ambiguous` can "act" on it and in a last step it is written back using `write_seqs(seqs, args.output)`.
In between, I can rename autoadjusted sequences as mentioned in https://github.com/nextstrain/ncov/issues/252.

**Comment by huddlej** [comment]
@tolot27 Thank you for catching these issues! Are you interested in tackling a solution? If so, I will assign this issue to you, so we know someone is looking into it.

**Comment by tolot27** [comment]
> @tolot27 Thank you for catching these issues! Are you interested in tackling a solution? If so, I will assign this issue to you, so we know someone is looking into it.

Yes, of course!
