### ISSUE TITLE
Deprecate Python 3.4, 3.5 and add 3.6 as minimum supported version

### ISSUE THREAD

**Issue by willingc** [nextstrain/augur#475]
**Context**  
Python 3.4 has reached end-of-life, and Python 3.5 is security fixes only.

NumPy in its next release will drop support for Python 3.5. [ref](https://numpy.org/neps/nep-0029-deprecation_policy.html)

Moving to Python 3.6 as the minimum version enables use of f-strings which simplify formatting of strings and allows asyncio.

**Description**   
Deprecate or drop Python 3.4 and 3.5 support. Set 3.6 as minimum supported version.

**Comment by tacaswell** [comment]
I am :+1: on this from a policy position and suggest following https://numpy.org/neps/nep-0029-deprecation_policy.html .

I will open a PR with the required metadata / setup.py / CI changes.
