### ISSUE TITLE
restore alignment broken

### ISSUE THREAD

**Issue by rneher** [nextstrain/augur#48]
Restore alignment no longer works for flu. It is saved without reference but a reference is a condition for successful recovery. 

Is is written out here (in most cases without reference): 
https://github.com/nextstrain/augur/blob/master/base/process.py#L198

and after reload checked for existing reference:
https://github.com/nextstrain/augur/blob/master/base/sequences_process.py#L136

not sure why reference is needed on reload.

**Comment by trvrb** [comment]
This was resolved in PR #49.

**Comment by huddlej** [comment]
This issue might not be fixed, after all. PR #49 made sure that the reference was written out in the MSA, but a rearrangement of when the alignment is checked for "the same sequences" in [another commit](https://github.com/nextstrain/augur/commit/36b7179fdea0e55955d73e9553e76ded979af2a3#diff-c9679891d684732d942b131543243152) now fails when the reference is in the MSA and not in the data set.

**Comment by trvrb** [comment]
Thanks for catching this @huddlej. Please do make this switch.

**Comment by huddlej** [comment]
Fixed by 59590b7.
