### ISSUE TITLE
Add testing guide

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#480]
Could we (perhaps @willingc or @huddlej) add a section to DEV_DOCS about how tests should be implemented, and point to general best practices? (Or create a README in `./tests`). There's been a lot of help with augur over the past few days and it'd be good to have a high level summary of how testing should be implemented

From my point of view, encouraging tests which cover the `augur` shell command -- e.g. [PR 479](https://github.com/nextstrain/augur/pull/479/files) -- would be incredibly valuable before we refactor the internals too much! 

It also seems that [we're favoring standalone tests over doctests](https://github.com/nextstrain/augur/pull/463#issuecomment-603549959) which seems great to me.

Note also that we also have a rudimentary form of e2e testing where a number of builds are run (via [this runner scipt](https://github.com/nextstrain/augur/blob/master/tests/builds/runner.sh)). Any non-zero-`augur`-exit-codes are breaking (and break CI) but it also requires manual examination of the output JSONs in auspice (and even then some subtle bugs can be missed). Thoughts on better ways to do this would be :100:

This issue is related to #476

**Comment by willingc** [comment]
Hi @jameshadfield, I can take a look at this in the morning.
