### ISSUE TITLE
Add coverage tool for pytest and enable codecov service

### ISSUE THREAD

**Issue by willingc** [nextstrain/augur#485]
We've successfully used pytest's coverage tool, coverage, and codecov with Travis CI or CircleCI. This will help automate the testing process and give feedback to contributors on each PR.

As an example, many of the Juptyer projects use this approach.

**Comment by willingc** [comment]
Once codecov is enabled, this PR can be closed.

**Comment by huddlej** [comment]
This is done now. Thanks, @willingc!
