### ISSUE TITLE
[BUG] run_tests.sh looks like it is missing a call to shift

### ISSUE THREAD

**Issue by terrycojones** [nextstrain/augur#500]
`run_tests.sh` has this:

```sh
case "$@" in
	*-k*) partial_test=1 ;;
esac
```

which looks like it should be

```sh
case "$@" in
	*-k*) partial_test=1 ; shift;;
esac
```

Otherwise the `-k` gets passed in the `"$@"` at bottom.

Anyway, all that processing could go away and you could just let people put `--no-cov` on the command line.  Maybe this script isn't used any more. I get an error no matter how I run it. E.g.,

```sh
$ ./run_tests.sh
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --cov=augur
  inifile: pytest.python3.ini
  rootdir: /home/terry/s/net/augur
```

**Comment by elebow** [comment]
`-k` is actually an argument to `pytest`, so it is supposed to be passed through to the `"$@"` below. The script only detects whether it is present, and consequently adds additional arguments to pytest.

`run_tests.sh` was just intended to be a convenience tool. Invoking `python -m pytest` directly and passing `--no-cov` is certainly an option for those who prefer it.

---

The error you see appears to be due to a missing `pytest-cov` package. You can ensure all development dependencies are installed with this:
```bash
pip install -e '.[dev]'
```

**Comment by terrycojones** [comment]
Hi @elebow - thanks for the reply!

> `-k` is actually an argument to `pytest`, so it is supposed to be passed through to the `"$@"` below. The script only detects whether it is present, and consequently adds additional arguments to pytest.

Ah, ok, got it.

> `run_tests.sh` was just intended to be a convenience tool. Invoking `python -m pytest` directly and passing `--no-cov` is certainly an option for those who prefer it.
> 
> The error you see appears to be due to a missing `pytest-cov` package. You can ensure all development dependencies are installed with this:
> 
> ```shell
> pip install -e '.[dev]'
```

OK, the pip install ran fine, thanks. If I then run `./run_tests.sh`, 36 tests are run. If I run `python -m pytest` only 24 tests are run.  Using `-k` with `./run_tests.sh` still gets an error:

```sh
$ ./run_tests.sh -k
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: argument -k: expected one argument
```

Thanks again!

**Comment by willingc** [comment]
@terrycojones Can this issue be closed or is there still something outstanding?

**Comment by terrycojones** [comment]
> @terrycojones Can this issue be closed or is there still something outstanding?

Hi. It could be closed - up to you. I don't know why a different number of tests get run in the 2 scenarios I mention above, but I don't think that's any kind of bug. I don't know why I get an error using `-k` either.  Anyway, for me it's fine to close this.

**Comment by willingc** [comment]
Thanks @terrycojones. We'll close this. If you have issues at a later date, please let us know.

@huddlej Recommend closing.

**Comment by huddlej** [comment]
@terrycojones Using `run_test.sh` includes doctests while running `python -m pytest` without specifying the test config file only runs unit tests.

The `-k` option is designed to specify a subset of tests you want to run.
