### ISSUE TITLE
BED file coordinates should be treated as 0-start, half-open intervals

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#511]
**Current Behavior**

augur's functions to read in BED files with a CSV parser treat coordinates as 0-start, fully-closed intervals. This means they include both the start and the end coordinates in the interval and treat these as zero-based coordinates. This behavior happens in [load_excluded_sites in tree.py](https://github.com/nextstrain/augur/blob/d5dbc75bce43f9439bad5ac3016ded492fb43b7a/augur/tree.py#L230) and also in augur mask.

The current behavior results in one extra base getting included at the end of given interval.

**Expected behavior**

[BED coordinates should be 0-start, half-open intervals](http://genome.ucsc.edu/blog/the-ucsc-genome-browser-coordinate-counting-systems/).

**Possible solution**  

  - Update BED functions to not add 1 to the final coordinate of each range
  - Update corresponding BED files in test data and production builds to the desired coordinates under the expected BED coordinate behavior

**Comment by jstoja** [comment]
I've taken a shot at it with #521 but I didn't find any BED files for `excluded_sites`.
