### ISSUE TITLE
Enable a time-tree with polytomies

### ISSUE THREAD

**Issue by batson** [nextstrain/augur#537]
**Context**  
When a large number of viral genomes are sequenced from a small population or in a short period of time, there are may be many identical genomes in the tree. Currently, the maximum likelihood tree computed by `augur tree` arbitrarily resolves the implicit multifurcation into a sequence of bifurcations. Then `augur refine` then infers properties (such as geographic location) for the internal nodes with genomes identical to all their children on the basis of that arbitrary resolution. This can lead to significant artifactual structure in the `Time` view of the tree in nextstrain. See example below. Switching to the `Div` view collapses these identical genomes into a polytomy, which is a more accurate depiction of the uncertainty involved, but it removes the ability to see the samples in time.

This is a considerable problem for the hCov-19 trees, where there are many identical sequences, often from many countries, from a time period lasting days to weeks.

**Description**   
I would like a view of the tree in which the x-axis is time, but monophyletic states with identical genomes are collapsed into a multifurcation.

**Examples**  

In this subtree of the current nextstrain `ncov` build, there are 29 identical genomes which have been resolved into a structured-looking tree by `augur tree` and `augur refine`. Moreover, the common ancestor is displayed has having 100% country confidence for USA. Were all within-country coalescent events performed before joining countries, that probability might be lower. (I'm not 100% sure of this.)

<img width="1011" alt="Screen Shot 2020-04-13 at 12 22 19 PM" src="https://user-images.githubusercontent.com/1261162/79183875-8b76bd00-7dc7-11ea-8eae-e771de6cd903.png">

All that structure from zero SNVs!
<img width="552" alt="Screen Shot 2020-04-13 at 12 22 40 PM" src="https://user-images.githubusercontent.com/1261162/79183881-8f0a4400-7dc7-11ea-8c8a-48cf55e5a2c8.png">
On the `Div` tree, you get a line, but lose time.
<img width="1010" alt="Screen Shot 2020-04-13 at 12 23 30 PM" src="https://user-images.githubusercontent.com/1261162/79183887-92053480-7dc7-11ea-8976-3646151324d0.png">
Very (over-?) confident country call for internal node.

**Possible solution**
There are a few stages of the pipeline in which this could be addressed.

1. Visualization: only display internal nodes which have a different (imputed) genome than their parent, i.e., collapse all branches between internal nodes that have no mutations on them. Display the corresponding multifurcation as a vertical line, with horizontal lines extending to children (positioned in the same place they would be in the existing tree. The internal node, the eldest of its class, would keep its own date, and the date window would still be interpretable as the time of the first occurrence of that genome in circulation.

Pro: no new computation necessary.
Con: inferred properties for internal nodes may still be biased by the initial arbitrary bifurcation used as the input to `treetime`.
<img width="563" alt="Screen Shot 2020-04-13 at 8 44 56 PM" src="https://user-images.githubusercontent.com/1261162/79183913-a9442200-7dc7-11ea-9879-e836c938d247.png">

2. Generate a tree with polytomies in `augur tree`, and feed that tree into `augur refine`. Actually produce a tree with polytomies in it, and display that tree using `auspice`. The best way to do this will depend on the package; it could be using the `-czb` flag in `iqtree`, doing some bootstraps, and collapsing branches with low support. Ideas of how to do this in other packages appreciated! `treetime` can handle polytomies, but someone more expert with the package would likely have better ideas how.

Pro: principled, may give better inferences for properties of internal nodes.
Con: additional computation.

**Comment by trvrb** [comment]
Thanks @batson!

You can experiment with adding `--keep-polytomies` to the `augur refine` step. It does as you propose. We've gone back and forth on whether to switch to this. It messes with the macro-level view of the tree and makes all the clades look explosive. But it's good for representing what we can trust about clade structure in a time time. I prefer to toggle back-and-forth between div and time to get at this issue. I don't have an immediate link to a JSON with `--keep-polytomies` run unfortunately.

**Comment by rneher** [comment]
this exists, so I think we can close this, right?
