### ISSUE TITLE
Is Augur compatible with matplotlib 3.x?

### ISSUE THREAD

**Issue by boegel** [nextstrain/augur#538]
In setup.py, there's a relatively script version requirement for `matplotlib`:

https://github.com/nextstrain/augur/blob/6e64923a025531f4c00bb44ca2af59afb751cc36/setup.py#L60

Is that just to be on the safe side and is Augur actually compatible with `matplotlib` 3.x as well, or are there known compatibility issues with matplotlib 3.x?

**Comment by iamsinghrajat** [comment]
Yes, Augur is compatible with matplotlib 3.x

**Comment by boegel** [comment]
OK, thanks for the info!
