### ISSUE TITLE
Is Augur compatible with cvxopt 1.2.x?

### ISSUE THREAD

**Issue by Darkless012** [nextstrain/augur#539]
In setup.py, there's a relatively script version requirement for cvxopt:

https://github.com/nextstrain/augur/blob/master/setup.py#L59

Is that just to be on the safe side and is Augur actually compatible with cvxopt 1.2.x as well, or are there known compatibility issues with cvxopt 1.2.x?

Looking on diff it seems no obvious breaking changes were introduced.
https://github.com/cvxopt/cvxopt/compare/1.1.9...1.2.0

**Comment by rneher** [comment]
we only use pretty standard solvers. the strict requirement is only to be on the safe side.

**Comment by huddlej** [comment]
Closing this as there does not seem to be a bug, per se. Please reopen this issue, though, @Darkless012, if you find that this strict cvxopt version does cause a bug in running augur.
