### ISSUE TITLE
error with treetime when running a nextstrain build

### ISSUE THREAD

**Issue by pauloluniyi** [nextstrain/augur#547]
when trying to run a nextstrain build, I'm getting an error message with treetime, "raise UnknownMethodError(TreeTime.run: rate variation for confidence estimation is not available. Either specify it explicitly, or estimate from root-to-tip regression." does anyone have a fix for this? or suggestions on how to solve it?

**Comment by jameshadfield** [comment]
Closing in favor of https://github.com/neherlab/treetime/issues/118 which has more information & discussion. We can reopen if this is an augur (not TreeTime) issue
