### ISSUE TITLE
Bug in refine.py

### ISSUE THREAD

**Issue by EricFournier3** [nextstrain/augur#554]
**Current Behavior**  
A clear and concise description of what is happening / what the bug is.  
Inferred a time resolved phylogeny using TreeTime:
        Sagulenko et al. TreeTime: Maximum-likelihood phylodynamic analysis
        Virus Evolution, vol 4, https://academic.oup.com/ve/article/4/1/vex042/4794731

Traceback (most recent call last):
  File "/data/Applications/Miniconda/miniconda3/envs/nextstrain/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/data/Applications/Miniconda/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/data/Applications/Miniconda/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__init__.py", line 76, in run
    return args.__command__.run(args)
  File "/data/Applications/Miniconda/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/refine.py", line 213, in run
    skyline, conf = tt.merger_model.skyline_inferred(gen=args.gen_per_year, confidence=2)
TypeError: 'interp1d' object is not iterable

It happen when treetime/merger_models/skyline_inferred() returns only skyline

**Expected behavior**  
A clear and concise description of what you expected to happen instead.  
We expected no bug

**How to reproduce**  
Steps to reproduce the current behavior:  
call refine.py from the following Snakefile rule;
rule refine:
    message:
        """
        Refining tree
          - estimate timetree
          - use {params.coalescent} coalescent timescale
          - estimate {params.date_inference} node dates
        """
    input:
        tree = rules.tree.output.tree,
        alignment = _get_alignments_for_tree,
        metadata = "results/metadata_adjusted{region}.tsv"
    output:
        tree = "results/tree{region}.nwk",
        node_data = "results/branch_lengths{region}.json"
    threads: 40
    params:
        root = "Wuhan-Hu-1/2019",
        clock_rate = 0.0008,
        clock_std_dev = 0.0004,
        coalescent = "skyline",
        date_inference = "marginal",
        divergence_unit = "mutations",
        clock_filter_iqd = 4
    shell:
        """
        augur refine \
            --tree {input.tree} \
            --alignment {input.alignment} \
            --metadata {input.metadata} \
            --output-tree {output.tree} \
            --output-node-data {output.node_data} \
            --root {params.root} \
            --timetree \
            --clock-rate {params.clock_rate} \
            --clock-std-dev {params.clock_std_dev} \
            --coalescent {params.coalescent} \
            --date-inference {params.date_inference} \
            --divergence-unit {params.divergence_unit} \
            --date-confidence \
            --no-covariance \
            --clock-filter-iqd {params.clock_filter_iqd}
        """

**Possible solution**  
(optional)  

**Your environment: if browsing Nextstrain online**  
 - Operating system:  
 - Browser:  

**Your environment: if running Nextstrain locally**  
 - Operating system:   CentOS 7
 - Browser:  Chrome
 - Version (e.g. `auspice 2.7.0`):  augur 7.0.2

**Additional context**

**Comment by rneher** [comment]
thanks for raising this. I just had a look. This probably happened when optimization of the coalescent model failed within treetime and this wasn't caught.If you change `coalescent` from `skyline` to `const` it should no longer fail.

**Comment by efournier8** [comment]
perfect. Thanks
