### ISSUE TITLE
Validation of 'results/aa_muts.json' failed

### ISSUE THREAD

**Issue by andersonbrito** [nextstrain/augur#558]
**Current Behavior**  
I'm running a quite large tree (nearly 10,000 taxa) on a server. The whole pipeline runs as expected, but at the last step `augur` fails to export the JSON file. I'm getting the error below:

```
Job 0: Exporting data files for for auspice

	ERROR: 1 is not of type 'string'. Trace: patternProperties - ^[a-zA-Z0-9*_-]+$ - properties - strand - type
	ERROR: 1 is not of type 'string'. Trace: patternProperties - ^[a-zA-Z0-9*_-]+$ - properties - strand - type
(...)
	ERROR: 1 is not one of ['-', '+']. Trace: patternProperties - ^[a-zA-Z0-9*_-]+$ - properties - strand - enum
	ERROR: 1 is not one of ['-', '+']. Trace: patternProperties - ^[a-zA-Z0-9*_-]+$ - properties - strand - enum
Validating schema of 'results/aa_muts.json'...
results/aa_muts.json contains an `annotations` block of an invalid JSON format. Was it produced by different version of augur the one you are currently using (7.0.2)? Please check the script / program which produced that JSON file.
Validation of 'results/aa_muts.json' failed.
```

**Expected behavior**  
Go through the last `augur` step and export a JSON file.

**How to reproduce**  
Maybe using a dataset of the same size as described above, but I'm not entirely this is the issue.

**Possible solution**  
It seems to be related to the reference genome annotation file, although I'm using the exact same reference as the main ncov global build (MN908947).

**Your environment: if running Nextstrain locally**  
 - Operating system: Linux (on a server, not sure which distro)
 - Version: `augur 7.0.2`

**Comment by emmahodcroft** [comment]
Hi @andersonbrito ! 

So, I'll have to dig a little bit deeper to remember exactly the details here, but I think I know vaguely the issue, thought that might be worth commenting on in case that's helpful short-term (as it's late here and I can't promise I can dig into this tonight!). 

In older versions of `augur` we specified strand as either 0 or 1, but more recently (9 months ago?) we switched this so that we specify strand as a more canonical `+` and `-`.  This mostly happens in the output of `translate` (see [here](392) as an example), but then can cause trouble if the output from an older `translate` is read into a newer `export`. 

It seems like this should be working and raising a warning (from the PR I just linked to...), so I'm a little uncertain why it's erroring. Could you check the output of your `translate` file to see if strand is indeed `0` or `1` - and maybe try forcing a regeneration of the translate data? If it's all new, can you double-check that all parts of the pipeline are running the same (preferably latest) `augur` version?

**Comment by emmahodcroft** [comment]
Sorry - as an update, the PR I linked gives the inverse scenario (I said it was later here!) where an older version of export was using a newer generated translate file! I believe your situation is the inverse. It seems somehow an older version of `translate` is generating the annotations file...

**Comment by emmahodcroft** [comment]
I've looked into this a bit more and yes, it seems like somehow you have a 'v5' version of your `translate` files (`aa_muts`) being generated, which is then getting passed into your `v6`) (or `v2`) `export` function, thus failing validation (see end of my comment [here](https://github.com/nextstrain/augur/issues/379)]) . 

I'm very unsure how this might have happened though! Is it possible these were generated on two different computers/clusters/environments, and one is running a fairly old `augur` version?

**Comment by andersonbrito** [comment]
Hey @emmahodcroft, thanks a lot for explaining the reasons behind this issue.

It indeed looks like a disconnect between components which are not in sync in terms of version. Event though the server runs `augur 7.0.2`, the `aa_muts` file is formatted like shown below:

```
{
 "annotations": {
  "E": {
   "end": 26472,
   "start": 26244,
   "strand": 1
  },
  "M": {
   "end": 27191,
   "start": 26522,
   "strand": 1
  },
  "N": {
   "end": 29533,
   "start": 28273,
   "strand": 1

```

In rule `export`, my Snakefile uses `augur export v2`. Would reverting the Snakefile to `augur export` solve the issue? Or the solution is more about reinstalling nextstrain from scratch?

**Comment by andersonbrito** [comment]
@emmahodcroft, following your comments, the approach below worked. ✨

I reverted the `Snakefile` and the `auspice_config` to fit `augur export v1`, re-ran `snakemake translate --force` and `snakemake export`, and both meta and tree JSON files were generated with the results I expected.

Thank you for your quick response.

**Comment by emmahodcroft** [comment]
Hi @andersonbrito - I'm glad it got working, but this is super weird! I'm 100% unsure how you were able to generate an 'old style' translate file, as essentially this shouldn't happen with newer `augur` versions! 

With the new format, with '+' as your strand, you should be able to now use `export v2` if you so wish, as well. However, as long as both parts of your pipeline are using the latest `augur` (v6 as it's dubbed in our discussions at our time) then using `v6 translate` and `v6 export v1` should work correctly, too. (See top ooint [here](https://github.com/nextstrain/augur/issues/379#issuecomment-547454148).)

Hopefully, `export v2` should now work for you too, if you prefer to make use of the latest options, etc!

I'm still very curious how this happened though. Is there a chance the original `aa_muts` file was generated on a different computer, or in a different environment, which was running an older `augur` version?

**Comment by andersonbrito** [comment]
Hi @emmahodcroft,

That makes sense. I guess there is a chance that only `augur` was updated outside the main conda environment found in the server, and probably I was running in distinct environments without noticing that. Anyway, I'll try to get the how environment updated, so that to avoid possible 'hybrid' runs.

Thank you.

**Comment by emmahodcroft** [comment]
Yea, environments are both a blessing and a curse! 😆  Thanks for your patience, I'm glad it got sorted anyway! Feel free to reopen or start a new issue if it causes trouble again!
