### ISSUE TITLE
Ancestral trait reconstruction can fail for traits with more than 62 unique states

### ISSUE THREAD

**Issue by tsibley** [nextstrain/augur#559]
`augur traits` [calls](https://github.com/nextstrain/augur/blob/42a26edc229c32cd83e4bf272ce0bdada1c100c6/augur/traits.py#L67-L70) TreeTime's `reconstruct_discrete_traits()` function for each trait given by `--columns`. `reconstruct_discrete_traits()` builds a single character alphabet representing the unique states for the trait by enumerating the states and assigning them a Unicode character starting from codepoint 65 (uppercase A). A "missing data" state is always added, so with 62 unique states for a trait + the "missing data" state, the alphabet will exceed the end of the ASCII codepoints, which ends at 127. This appears to work fine on its own, although the alphabet will contain non-printable characters represented using 2-byte sequences (instead of a single byte) when written out as UTF-8.

The problem comes when `augur traits` goes to write the `*.mugration_model.txt` files. It does so [without  specifying a file encoding](https://github.com/nextstrain/augur/blob/42a26edc229c32cd83e4bf272ce0bdada1c100c6/augur/traits.py#L190-L196), which means that the locale-preferred encoding is used. On many systems, this is UTF-8, in which case things appear to work fine, but sometimes it is ASCII, which fails with a traceback like:

```
Traceback (most recent call last):
File "/usr/local/bin/augur", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.6/dist-packages/augur/__main__.py", line 10, in main
return augur.run( argv[1:] )
File "/usr/local/lib/python3.6/dist-packages/augur/__init__.py", line 74, in run
return args.__command__.run(args)
File "/usr/local/lib/python3.6/dist-packages/augur/traits.py", line 190, in run
ofile.write(k+':\t'+str(v)+'\n')
UnicodeEncodeError: 'ascii' codec can't encode character '\x80' in position 0: ordinal not in range(128)
```

Note that 0x80 is one more than the last ASCII codepoint, 0x7F.

I believe Augur can fix this merely by specifying an explicit `encoding="UTF-8"` in the appropriate `open()` calls, but it would be good to also double check that TreeTime's reconstruction is happening correctly when the alphabet contains non-printable, multi-byte characters.

For anyone encountering this bug, a workaround is to set your locale to a Unicode friendly one, such as `en_US.UTF-8`, by setting the environment variable `LC_ALL=en_US.UTF-8` when you run Augur. You can inspect your default locale with the `locale` command and test Python's handling of it with `python3 -c 'open("/dev/null", "w").write("\x80")'`. If your locale is `C`, for example, you'll see an error like the one above:

    LC_ALL=C python3 -c 'open("/dev/null", "w").write("\x80")'

I noticed that TreeTime also leaves the encoding unspecified when it writes out similar data. There are many places in `treetime.wrappers` where the model alphabet is written out without an explicit encoding, but [here's one example](https://github.com/neherlab/treetime/blob/master/treetime/wrappers.py#L885-L890).

**Comment by rneher** [comment]
good to know. I have never run into this but my locale certainly is `*.UTF-8`.  We have recently merged some PRs that fix this in other places (e.g. this one https://github.com/nextstrain/augur/pull/503) and it makes sense to harmonize this across files (and in treetime).

TreeTime used to be restricted to byte arrays for sequences, but in python3 these are unicode arrays and the core machinery should work fine. but I haven't paid much attention to the fileIO.

**Comment by tsibley** [comment]
I've opened #560 to be explicit about this across Augur for all the `open()` calls I could find.
