### ISSUE TITLE
NextStrain augur refine treetime.MissingDataError: ERROR: ALMOST NO VALID DATE CONSTRAINTS

### ISSUE THREAD

**Issue by shashibioinfo143** [nextstrain/augur#566]
augur refine -t indian_837_data.nwk -a aligned_indian_837.fasta --metadata metadata_2020-06-16_07-16.tsv --output-tree refine_indian_837_data.nwk --output-node-data branch_lengths_indian_837.json --root hCoV-19/Wuhan/WH01/2019 --timetree --clock-rate 0.0008 --clock-std-dev 0.0004 --coalescent skyline --date-inference marginal --divergence-units mutations --date-confidence --no-covariance --clock-filter-iqd 4 

augur refine is using TreeTime version 0.7.6
Traceback (most recent call last):
  File "/home/cdfd/anaconda3/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/home/cdfd/anaconda3/lib/python3.7/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/home/cdfd/anaconda3/lib/python3.7/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/home/cdfd/anaconda3/lib/python3.7/site-packages/augur/refine.py", line 209, in run
    covariance=args.covariance, resolve_polytomies=(not args.keep_polytomies))
  File "/home/cdfd/anaconda3/lib/python3.7/site-packages/augur/refine.py", line 37, in refine
    verbose=verbosity, gtr='JC69', precision=precision)
  File "/home/cdfd/anaconda3/lib/python3.7/site-packages/treetime/treetime.py", line 34, in __init__
    super(TreeTime, self).__init__(*args, **kwargs)
  File "/home/cdfd/anaconda3/lib/python3.7/site-packages/treetime/clock_tree.py", line 83, in __init__
    self._assign_dates()
  File "/home/cdfd/anaconda3/lib/python3.7/site-packages/treetime/clock_tree.py", line 130, in _assign_dates
    raise MissingDataError("ERROR: ALMOST NO VALID DATE CONSTRAINTS")
treetime.MissingDataError: ERROR: ALMOST NO VALID DATE CONSTRAINTS

**Comment by rneher** [comment]
Please check that the taxon names in your tree match those in the meta data and that the dates are in the correct format.

**Comment by rneher** [comment]
did this solve your issue? can we close this?

**Comment by shashibioinfo143** [comment]
Hi sir,
I have changed the Date for columns which were empty in **ddmmyear** format.
and taxon names were fine.
but still i got this issue.
please help me to resolve it
Thanks.

augur refine is using TreeTime version 0.7.6
Traceback (most recent call last):
  File "/home/sashik/.local/bin/augur", line 11, in <module>
    sys.exit(main())
  File "/home/sashik/.local/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/home/sashik/.local/lib/python3.6/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/home/sashik/.local/lib/python3.6/site-packages/augur/refine.py", line 209, in run
    covariance=args.covariance, resolve_polytomies=(not args.keep_polytomies))
  File "/home/sashik/.local/lib/python3.6/site-packages/augur/refine.py", line 37, in refine
    verbose=verbosity, gtr='JC69', precision=precision)
  File "/home/sashik/.local/lib/python3.6/site-packages/treetime/treetime.py", line 34, in __init__
    super(TreeTime, self).__init__(*args, **kwargs)
  File "/home/sashik/.local/lib/python3.6/site-packages/treetime/clock_tree.py", line 83, in __init__
    self._assign_dates()
  File "/home/sashik/.local/lib/python3.6/site-packages/treetime/clock_tree.py", line 130, in _assign_dates
    raise MissingDataError("ERROR: ALMOST NO VALID DATE CONSTRAINTS")
treetime.MissingDataError: ERROR: ALMOST NO VALID DATE CONSTRAINTS

**Comment by rneher** [comment]
try 'YYYY-MM-DD' format. This is the ISO format augur supports.

**Comment by shashibioinfo143** [comment]
Hi,

I tried changing the format to 'YYYY-MM-DD'
but this showed different error 
please help me on this

augur refine is using TreeTime version 0.7.6
Error reading metadata file metadata_2020-06-16_07-16_updated2.tsv
Error tokenizing data. C error: Expected 4 fields in line 63, saw 5

PFA attachment of the tree and metadata excel files

[indian_837_data.zip](https://github.com/nextstrain/augur/files/4804286/indian_837_data.zip)
[metadata_2020-06-16_07-16_updated2.zip](https://github.com/nextstrain/augur/files/4804288/metadata_2020-06-16_07-16_updated2.zip)
Thank you

**Comment by shashibioinfo143** [comment]
> Hi,
> 
> I tried changing the format to 'YYYY-MM-DD'
> but this showed different error
> please help me on this
> 
> augur refine is using TreeTime version 0.7.6
> Error reading metadata file metadata_2020-06-16_07-16_updated2.tsv
> Error tokenizing data. C error: Expected 4 fields in line 63, saw 5
> 
> PFA attachment of the tree and metadata excel files
> 
> [indian_837_data.zip](https://github.com/nextstrain/augur/files/4804286/indian_837_data.zip)
> [metadata_2020-06-16_07-16_updated2.zip](https://github.com/nextstrain/augur/files/4804288/metadata_2020-06-16_07-16_updated2.zip)
> Thank you

Please help me to resolve this issue sir.
Hope to hear from you
Thank you

**Comment by rneher** [comment]
there is something wrong with your tsv file. You only sent the excel file along, so I can't tell.

**Comment by shashibioinfo143** [comment]
> there is something wrong with your tsv file. You only sent the excel file along, so I can't tell.

Thank you for reply
I can't able to attach tsv file here.
If you can please share your email address

Thank you

**Comment by jg95ae** [comment]
Hi Richard, I'm having the same error when using the example data

**Comment by shashibioinfo143** [comment]
> there is something wrong with your tsv file. You only sent the excel file along, so I can't tell.





> there is something wrong with your tsv file. You only sent the excel file along, so I can't tell.

**Comment by shashibioinfo143** [comment]
> there is something wrong with your tsv file. You only sent the excel file along, so I can't tell.
Hi sir,

Sorry for late reply, i was not in lab for last 2 days
PFA of tsv file
Please help me to resolve this

Thanks

[metadata_2020-06-16_07-16_updated2 (1).zip](https://github.com/nextstrain/augur/files/4823217/metadata_2020-06-16_07-16_updated2.1.zip)

**Comment by emmahodcroft** [comment]
Hi @shashibioinfo143 - you marked the issue as closed. Is the problem resolved, or do you continue to have problems?

I downloaded your file but I cannot open the TSV within the ZIP. It seems the file is corrupted or it's not actually a TSV file. If I change the extension to XLS it seems it's an Excel file. You cannot use an Excel file as input here (and just changing the extension doesn't work). You'll need to open in Excel, and 'save as' a Tab-Delimited file (.txt) - with the extension .tsv.

I hope that helps

**Comment by shashibioinfo143** [comment]
> Hi @shashibioinfo143 - you marked the issue as closed. Is the problem resolved, or do you continue to have problems?
> 
> I downloaded your file but I cannot open the TSV within the ZIP. It seems the file is corrupted or it's not actually a TSV file. If I change the extension to XLS it seems it's an Excel file. You cannot use an Excel file as input here (and just changing the extension doesn't work). You'll need to open in Excel, and 'save as' a Tab-Delimited file (.txt) - with the extension .tsv.
> 
> I hope that helps

Thanks for the response.
The Query got closed by mistake.
i will try to download metadata.tsv file again from GISAID and do analysis will update you accordingly

Thank you

**Comment by shashibioinfo143** [comment]
Hi,
I have downloded metadata file again and did analysis but still it shows same error.

i have sent metadata file in .zip format and tree file 

please help me to resolve this issue

Thank you

[indian_837_data_file.zip](https://github.com/nextstrain/augur/files/4828901/indian_837_data_file.zip)
[metadata.zip](https://github.com/nextstrain/augur/files/4828903/metadata.zip)

**Comment by shashibioinfo143** [comment]
Hi @emmahodcroft ,

Thank you so much for response. I have changed those Strain name in Excel hCoV-19.. and tried to do analysis from augur refine step but still error is same.

Im using Ubuntu 18.04 version and using Libre Office Cal Software for Excel metadata.tsv file for editing. I have changed the Format of date to 'YYYY-MM-DD' and saved . but when i reopen the metadata.tsv file in same software the date format cells shows as Text. 

Shall i edit the metadata file in microsoft excel ?

please do comment on this

Thank you

**Comment by shashibioinfo143** [comment]
[metadata.zip](https://github.com/nextstrain/augur/files/4830901/metadata.zip)
[indian_837_data_file.zip](https://github.com/nextstrain/augur/files/4830903/indian_837_data_file.zip)

**Comment by shashibioinfo143** [comment]
> Hi @shashibioinfo143 , the metadata file looks good now, but the tree file is not in the correct format to work with it. The names in the tree do not match the 'strain' names in the metadata. Where is this tree from?
> 
> For example, in `metadata.tsv` the strain name is listed as `India/S13/2020`
> In the tree, it's given as `hCoV-19/India/S13/2020|EPI_ISL_455643|2020-03-30` - these don't match, so the program cannot match up the metadata with the tree.
> 
> You should make a tree using the metadata file, and a sequence file which matches those strain names. Or, you can could generate another metadata file which has the longer strain names, as you have in the tree.

Dear @emmahodcroft ,

Thank you for your response the issue is resolved

**Comment by emmahodcroft** [comment]
Good to hear!

**Comment by madhuribelekar** [comment]
Traceback (most recent call last):
  File "/root/miniconda3/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/root/miniconda3/lib/python3.7/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/root/miniconda3/lib/python3.7/site-packages/augur/refine.py", line 209, in run
    covariance=args.covariance, resolve_polytomies=(not args.keep_polytomies))
  File "/root/miniconda3/lib/python3.7/site-packages/augur/refine.py", line 37, in refine
    verbose=verbosity, gtr='JC69', precision=precision)
  File "/root/miniconda3/lib/python3.7/site-packages/treetime/treetime.py", line 34, in __init__
    super(TreeTime, self).__init__(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/treetime/clock_tree.py", line 83, in __init__
    self._assign_dates()
  File "/root/miniconda3/lib/python3.7/site-packages/treetime/clock_tree.py", line 130, in _assign_dates
    raise MissingDataError("ERROR: ALMOST NO VALID DATE CONSTRAINTS")
treetime.MissingDataError: ERROR: ALMOST NO VALID DATE CONSTRAINTS

**Comment by madhuribelekar** [comment]
Hiii,

Why I am getting above error?
Please help me to resolve this.

Thanks
[metadata mha.xlsx](https://github.com/nextstrain/augur/files/5130915/metadata.mha.xlsx)

**Comment by anacmendesj** [comment]
I had a similar error, can anyone help me?

" raise MissingDataError("ERROR: Cannot read metadata: need at least one column that contains the taxon labels."
treetime.MissingDataError: ERROR: Cannot read metadata: need at least one column that contains the taxon labels. Looking for the first column that contains 'name', 'strain', or 'accession' in the header. " 

my csv file looks like this:
name,ID de acesso,data,
hCoV-19/Brazil/BA-FIOCRUZ-2068/2024,EPI_ISL_19058137,2024-02-02,
hCoV-19/Brazil/BA-FIOCRUZ-3371/2024,EPI_ISL_19133241,2024-02-02,

my tree looks like this:

'hCoV-19/Brazil/BA-LACEN-293034747/2023|EPI_ISL_17781208|2023-05-26':1.0E-6,

**Comment by corneliusroemer** [comment]
The tip labels in your tree need to match the names in the CSV/TSV. Based
on your example they don't match due to extra information in the tips in
the tree (after the | )

**Comment by anacmendesj** [comment]
@corneliusroemer  

This information is the size of the branch, can I remove this?

**Comment by corneliusroemer** [comment]
@anacmendesj I think there's a misunderstanding.

It's this that's causing the error:

```
'hCoV-19/Brazil/BA-LACEN-293034747/2023|EPI_ISL_17781208|2023-05-26':1.0E-6,
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

because in your csv file you have `name` being just `hCoV-19/Brazil/BA-FIOCRUZ-2068/2024`, without the extra stuff after `|`.

The identifiers need to match exactly. You can use `augur parse` to clean up the sequence names (or seqkit): https://docs.nextstrain.org/projects/augur/en/stable/usage/cli/parse.html
