### ISSUE TITLE
Accept ISO 8601 dates in augur filter's max-date and min-date

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/augur#567]
**Context**  
When providing an argument to augur filter's `--max-date` option, I automatically gave it an ISO 8601 date string (e.g. '2020-06-15'). Not being much of an augur user, I was surprised to learn that it only accepts float dates (e.g. 2020.46).  

**Description**   
Allow augur filter to accept ISO 8601 date strings along with date floats in a backwards compatible way.

More context can be found in this [ncov PR thread](https://github.com/nextstrain/ncov/pull/401#issuecomment-645081623).

**Comment by jameshadfield** [comment]
:+1: Small typo in the link to the ncov PR where this was discussed, it's at https://github.com/nextstrain/ncov/pull/401

**Comment by kairstenfay** [comment]
Ah, thank you, James. I updated the link so that it's now functional.
