### ISSUE TITLE
How to get specific positions of mutations on a tree?

### ISSUE THREAD

**Issue by COVIDMutational** [nextstrain/augur#570]
I have created a time tree and have calculated the mutations on all of my terminal branches and inferred ancestors.  Is there currently a feature that would enable me to get more specific information on the depth of these mutations in the tree, or even where these outputted mutations fall on their branches?  Thanks!

**Comment by jameshadfield** [comment]
Hi @COVIDMutational, if you use the `augur export` functionality to make a JSON for visualization in auspice you can interact with the resulting tree and see mutations on individual branches as you hover over them, as well as a diversity panel etc. The simplest way to use auspice is to simply drag & drop the JSON onto http://auspice.us, but you can also install it locally. 

If you are asking where along an individual branch a mutation occurred then this information is not available from augur.

**Comment by COVIDMutational** [comment]
Hi @jameshadfield, thank you for the reply.  I am looking to get depth estimates for individual mutations.  I've  been able to find the branches that each mutation falls on, and the length of said branches, but I didn't know if there was a command to extrapolate mutation depth from these.  

E.g. A command that would utilize branch_lengths.json and nt_muts.json to output depth estimates for mutations.  

Thank you!

**Comment by jameshadfield** [comment]
There's not a command specifically to do this, but you can match the data via the node names between those two JSONs. The dates in the `branch_lengths.json` (`numdate` key) refer to the bottom of the branch (i.e. the end closest to the tip) so to get the date at the top of each branch you'll have to look at the newick file which `augur refine` produces to find the parent node name. It may be easier to run the data through `augur export` and then parse the resulting (single) JSON which will encode the topology and include the node dates & mutations together on each node.

**Comment by COVIDMutational** [comment]
That makes sense, thank you!  One last question: I understand what branch_length represents in the branch_lengths.json but what does the mutation_length key represent?

**Comment by jameshadfield** [comment]
It depends on the [--divergence-units](https://github.com/nextstrain/augur/blob/master/augur/refine.py#L122) argument passed to `augur refine`. For CoV, we use [--divergence-units mutations](https://github.com/nextstrain/ncov/blob/master/config/config.yaml#L79) so it's the number of nucleotide changes ascribed to that branch by a GTR model (note that the output in the JSON from `augur export` represents cumulative divergence from the root). For other pathogens, the units may be different (e.g. inferred changes per site).

**Comment by COVIDMutational** [comment]
Thank you!  This solves this.
