### ISSUE TITLE
Trait reconstruction without trait diversity only fails

### ISSUE THREAD

**Issue by rneher** [nextstrain/augur#575]
**Current Behavior**  
In and ncov issue ( https://github.com/nextstrain/ncov/issues/426), @Addicted-to-coding reported that reconstruction fails when there is only one value on the metadata. This has to do with treetime not bothering to actually reconstruct anything which results in missing confidence vectors. When augur tries to access these, it fails.

**Comment by joverlee521** [comment]
Just wanted to chime in that I'm also seeing this bug when running the Seattle Flu builds.

**Comment by jaredroach** [comment]
I had the same problem as was mentioned in (nextstrain/ncov#426), in that I was getting this error as well:
     AttributeError: 'Clade' object has no attribute 'country_exposure_confidence'
The link mentioned by @jameshadfield in (nextstrain/ncov#426) to fix the Augur code was broken (https://github.com/nextstrain/ncov/blob/master/rules/builds.smk#L823). However, I fixed my problem by adding in values to all of these fields in the metadata file:
     country	division	location	region_exposure	country_exposure	division_exposure	segment
I just copied the value for the country into all the other fields, and 'genome' for segment.

I conclude that the "Required Metadata" section of the tutorial at "https://nextstrain.github.io/ncov/data-prep.html" could be updated to mention that these additional metadata fields, while not required, are a really good idea, particularly for beginners.

**Comment by trvrb** [comment]
This seems like a common enough edge case that it would be worth fixing, especially as the error provided is rather opaque.

**Comment by bede** [comment]
I'm running into this too

**Comment by ayotomiwaa** [comment]
I'm currently running into this problem. Please is there currently a fix. I have a huge metadata file that I may not be able to fill all of it.

**Comment by jonbra** [comment]
What's the status on this issue? I get this error when running a build with a single country only. Disabling augur traits in the snakemake workflow works, but is it also possible to disabling this through the builds.yaml file?

**Comment by huddlej** [comment]
Thank you for bumping this, @jonbra! We've decided the best fix would be on the Augur side of the implementation. This would allow the ncov workflow to run as expected without any changes. I also ran into this issue and wrote up a possible fix and some tests in #828 (before I realized we already had this issue).
