### ISSUE TITLE
Provide options to handle duplicate sequences more gracefully in augur filter 

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#586]
**Current Behavior**

When a user runs `augur filter` with a FASTA file of sequences that contains any duplicate sequences (by strain name), augur prints an error and exits with a nonzero exit code.

**Expected behavior**

It would be nice if the filter command provide users with options to more gracefully handle duplicate sequences as a type of filter. For example, in a common use case users will have downloaded sequences from the NCBI virus databases and even after collapsing identical sequences there can be unique sequences associated with the same strain name. Instead of throwing an error as shown below, augur filter should allow users to drop or collapse these duplicate sequences.

![image](https://user-images.githubusercontent.com/85372/86195460-cbfff000-bb05-11ea-8473-18e554990694.png)

Even when the user includes a list of duplicated strains in the `--exclude` argument to drop them from the analysis, augur filter throws the error before it knows these are going to be excluded anyway.

**Possible solution**

What if augur filter provided flags like `--drop-duplicates` or `--collapse-duplicates`? The first flag would drop any strains that appear multiple times in a given file. The second flag would try to pick one sequence. This could be a simple flag that always takes the first sequence or it could be a smarter argument that allows the user to specify "first", "last", "earliest", or "latest", etc.

**Comment by victorlin** [comment]
Closing this as not planned per https://github.com/nextstrain/augur/issues/810#issuecomment-2286856280
