### ISSUE TITLE
Error in translate.py from vcf

### ISSUE THREAD

**Issue by andreott** [nextstrain/augur#591]
When using translate for vcf an error comes up for the sequence length not being a multiple of 3. However this test is performed for the source feature. Probably the  `if feat.type != 'source':` should be placed at the outer loop level, e.g.

    for fname, feat in features.items():
        if feat.type != 'source':
            if is_vcf:
                trans = translate_vcf_feature(sequences, ref, feat)
                if trans:
                    translations[fname] = trans
                else:
                    deleted.append(fname)
            else:
                translations[fname] = translate_feature(sequences, feat)
instead of

https://github.com/nextstrain/augur/blob/3dcf8a1ba2e614094c69ab1d22d6df0e2630600a/augur/translate.py#L359-L368

**Comment by TheBready** [comment]
Hey @andreott, is this issue solved and merged?

**Comment by jameshadfield** [comment]
It seems this issue and the corresponding PR didn't get attention from us - apologies.

I'm currently doing some work on general VCF parsing and how this information flows through `augur ancestral` and `augur translate`, and part of this will address this issue. It should be up in the coming week or so.

**Comment by jameshadfield** [comment]
Closed by #1348. Please see comment https://github.com/nextstrain/augur/pull/1348#issuecomment-1863725773
