### ISSUE TITLE
Rewrite zika tutorial to incorporate content from the nextstrain.org version

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#594]
We currently have two similar, but diverged Zika tutorials: nextstrain.org/docs/tutorials/zika and https://docs.nextstrain.org/projects/augur/en/stable/tutorials/zika_tutorial.html. The source code for the former is [here](https://github.com/nextstrain/nextstrain.org/blob/master/static-site/content/docs/03-tutorials/01-zika.md) and the latter [here](https://github.com/nextstrain/augur/blob/master/docs/tutorials/zika_tutorial.md). Ideally there should only be one (canonical) Zika tutorial. 

PR https://github.com/nextstrain/nextstrain.org/pull/195 allows external links to be added to the nextstrain.org docs sidebar which was intended to remove duplicated help pages such as this. As the two Zika tutorials were so different, they were deemed outside the scope of that PR. This issue, therefore, asks for the zika tutorial in this repo to be updated so that the nextstrain.org version can be removed and an external link added from the nextstrain.org docs instead. For what it's worth, I find the content in the nextstrain.org version easier to follow, and think the augur version spends a lot of time introducing the concept of augur commands.

Note for context: @eharkins says (and I agree) "I vote for tutorials living in augur + auspice docs (so that they can be updated in sync with changes to each of those projects) so I would be in favor of consolidating the zika tutorial into https://nextstrain-augur.readthedocs.io/en/stable/tutorials/zika_tutorial.html".

**Comment by huddlej** [comment]
This has been partially resolved by [removing Augur's Zika tutorial in favor of the current docs.nextstrain.org version](https://github.com/nextstrain/docs.nextstrain.org/pull/48). However, there is still [an open issue to rewrite the original Augur version](https://github.com/nextstrain/docs.nextstrain.org/pull/50) which is Snakemake-based and a useful next step after the introductory tutorial.
