### ISSUE TITLE
Branch lenghts of mutations should be integers

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#617]
Currently `augur refine --divergence-units mutations` produces branch lengths which aren't integers (e.g. see https://nextstrain.org/ncov/global/2020-10-01?m=div). This becomes confusing, and we've had various questions along the lines of "what does a sample with 16.66 mutations mean?"

This issue proposes that the output here mirrors the number of (inferred) mutations between the root & the node. For instance, the "divergence" of this node should be exactly 1:
![image](https://user-images.githubusercontent.com/8350992/95689699-09c8f480-0c6f-11eb-890f-dc82a8e109ca.png)

I'm unsure whether this is best tackled as an improvement to `augur refine` or by extending `augur ancestral` to modify the branch-lengths JSON. (If we go for the latter then maybe we get rid of refine's `--divergence-units` argument.)

cc @rneher @emmahodcroft @huddlej @trvrb

**Comment by huddlej** [comment]
This was resolved by #618.
