### ISSUE TITLE
Unable to run ModelTest (augur tree)

### ISSUE THREAD

**Issue by ammaraziz** [nextstrain/augur#619]
**Current Behavior**  
The documentation states if `none` is specified for the `--substitution-model` flag, `ModelTest` will run to determine the most appropriate model. However, an error is produced: 

> augur tree: error: argument --substitution-model: invalid choice: 'none' (choose from 'HKY', 'GTR', 'HKY+G', 'GTR+G', 'GTR+R10')

The available choices do not include `none`.

**How to reproduce**  
The command I ran:

    augur tree -a input.fasta -o output.tree --method iqtree --substitution-model none --nthreads n

**Possible solution**  
Adding `"none"` in line 329 in tree.py as one of the choices fixes the issue:
https://github.com/nextstrain/augur/blob/efcc8be3bcf72ab4beb237afcc5b4b002bbaa806/augur/tree.py#L329

Should be:

    parser.add_argument('--substitution-model', default="GTR", choices=["HKY", "GTR", "HKY+G", "GTR+G", "GTR+R10", "none"],

**Environment:**
 - Operating system:  Linux Mint Cinnamon 4.6.7   
 - Version: augur 10.0.2

Thank you for creating and maintaining, it is fantastic. 

Ammar

**Comment by ammaraziz** [comment]
On a related issue, the output to the terminal for running `ModelTest` via `--substitution-model none`:

> Conducting a model test... see iqtree.log for the result. You can specify this with --substitution-model in future runs.

This isn't possible due to the above issue. (`argparse` doesn't seem to have any option to allow non-predefined arguments but a hack is possible using a function to capture and split the string). The solution I found (without modifying `tree.py`) was to use the existing `--tree-builder-args` argument to specify a non-default model. eg: 

    % augur tree -a input.fasta -o out.tree --tree-builder-args="-m GTR+G+I"
          Building a tree via:
          iqtree -ninit 2 -n 2 -me 0.05 -nt 1 -s input.fasta -m GTR -m GTR+G+I > input_aligned-delim.iqtree.log

`iq-tree` happily accepts two `-m` model arguments and runs fine.  That's a long winded way of saying the documentation might need updating.

I am happy to submit a pull request for these issues if you think they're worth it.

Thanks,

Ammar

**Comment by llk578496** [comment]
Hi, I have the same problem too! Also I could not specify the bootstrap value due to the uncompabtible argument -n
