### ISSUE TITLE
filter's priority argument is not clearly documented

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#622]
Our documentation (including the augur command line help itself) lacks examples of priorities file that could be used by `augur filter --priority`. At the least, we should communicate that:

  - the format of the priorities file is "sequencename<tab>priority"
  - higher numbers are higher priority
  - the numbers can be arbitrary and are only evaluated relative to each other

It would be nice if we should specific examples of how we use this feature, too. These examples might live in the "Running Bioinformatics Analyses" section of the main docs.

**Comment by emmahodcroft** [comment]
Thanks for making an issue on this @huddlej !
