### ISSUE TITLE
Conda installation error in miniconda Dockerfile

### ISSUE THREAD

**Issue by WhalleyT** [nextstrain/augur#624]
**Current Behavior**  
I am trying to build a Docker container [here](https://github.com/WhalleyT/augur_conda_error) and it will not build. It failed with initial frozen solve, then when it tries the flexible solve it times out (usually after 5-10 minutes) trying to find the shortest confict path.

**Expected behavior**  
The container to build!

**How to reproduce**  
Steps to reproduce the current behavior:  
- Either look at the Docker log files found here: https://hub.docker.com/repository/registry-1.docker.io/twhalley93/augur_conda_error/builds/69f1719c-d116-4b01-b3e5-4660469d9d2c
- ```git clone https://github.com/WhalleyT/augur_conda_error ; cd augur_conda_error ; docker build .```

**Possible solution**  
I suspect it would be a case of finding the conflicts and installing them manually, however attempt at ```conda install``` times out before it gives any specifics.

**Your environment: if running Nextstrain locally**  
 - Operating system: Windows 10  
 - Docker build: continuumio/anaconda3 
 - Version: augur v10.0.3

Thanks in advance for the help! Let me know if you need any other specifics/logfiles.

**Comment by jameshadfield** [comment]
Slightly tangential, but https://github.com/nextstrain/docker-base/ will build a docker image with Augur, Auspice and a bunch of other tools inside it!

**Comment by WhalleyT** [comment]
Brilliant, thank you! That definitely provides a workaround for me. Likewise, the pip installation seems to work okay within a Docker build.

**Comment by huddlej** [comment]
The Docker image that @jameshadfield recommends is the best way to get the latest version of Augur in a Docker image.

That said, I'm interested in the approach you're taking here. Two thoughts about how to fix this issue:

1. Swap the order of the "bioconda" and "conda-forge" channels in the environment file. [Bioconda expects conda-forge to be the highest priority channel](https://bioconda.github.io/user/install.html#set-up-channels). In the environment file this would look like:

```
name: augur_test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - augur
```

2. The conda solver struggles with the huge package list from the conda-forge channel and can either take a very long time to solve installation requirements or fail completely. The best workaround for this issue I've seen is to [use mamba as a drop-in replacement for conda](https://github.com/mamba-org/mamba). mamba implements a more efficient dependency solving algorithm and installs from conda-forge much more quickly.

You may also want to check out [the micromamba implementation](https://github.com/mamba-org/mamba#micromamba) that is specifically designed for bootstrapping environments like Docker images.

Would you be interested in trying these solutions and letting us now if they fix the problem?

**Comment by WhalleyT** [comment]
Hi @huddlej, 

I'll give those both a go and see how it goes. Will get back to you shortly. Thanks!

**Comment by WhalleyT** [comment]
Thanks, @huddlej, both attempts resolved the environment. Thank you for your help, especially for point me to micromamba, that's going to be very useful.

**Comment by huddlej** [comment]
That is excellent news, @WhalleyT. Thank you for testing out these approaches!
