### ISSUE TITLE
Travis CI environments for Python 3.x all use Python 3.6

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#626]
## Current Behavior

Our Travis CI runs one build for Python versions 3.6, 3.7, and 3.8 for each branch and PR. Even though [the global Python version for each build is the expected 3.x](https://travis-ci.com/github/nextstrain/augur/jobs/427822558#L174), the conda environment used to run the build [always installs Python 3.6](https://travis-ci.com/github/nextstrain/augur/jobs/427822558#L2244).

## Expected behavior

Specific Python version CI builds should be using the version of Python installed globally, so we know if Augur tests pass with all major Python versions.

## How to reproduce

See any recent Travis CI log ([for example](https://travis-ci.com/github/nextstrain/augur/jobs/427822558)).

## Possible solutions

1. Omit the specific Python version from the conda environment file and instead specify the version dynamically based on the global CI version as part of the environment creation.

2. Create a separate environment file for each Python version and use the corresponding file for each CI build.

I'm not familiar enough with Travis CI yet to know whether these solutions are reasonable, so other suggestions are welcome.

**Comment by Bost** [comment]
Try to specify the python versions at the top level. See https://docs.travis-ci.com/user/languages/python/#specifying-python-versions

And - if that's your case, try to disable parallel execution just to simplify the bug hunting. See https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
