### ISSUE TITLE
Augur refine multiple threads

### ISSUE THREAD

**Issue by mesti90** [nextstrain/augur#632]
Would it be possible to use multiple threads with augur refine?

**Comment by emmahodcroft** [comment]
Currently the code is not multithreaded so this isn't possible. `augur refine` uses [TreeTime](https://github.com/neherlab/treetime), and there are some efforts to help improve TreeTime, if you are able/interested to contribute!

**Comment by huddlej** [comment]
Closing this issue for now, since it is TreeTime-dependent and there are no plans to add multi-threading there at this point.
