### ISSUE TITLE
Find iqtree executable 

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#636]
**Context**  

IQ-TREE 2.1.2 offers some significance performance improvement specifically for SARS-CoV-2 (http://www.iqtree.org/). However, it slightly changes some of it's command line options and changes the name of the executable from `iqtree` to `iqtree2`. 
 
**Description**   

I'd like `augur tree` to use `iqtree2` when it's available but to fall back to `iqtree` when it's not. This should offer an upgrade path to existing users. Currently, FastTree and RAxML use a `find_executable` function to determine which binary to call (https://github.com/nextstrain/augur/blob/master/augur/tree.py#L90, https://github.com/nextstrain/augur/blob/master/augur/tree.py#L40). We should just add a similar lookup to IQ-TREE.

**Comment by trvrb** [comment]
I just elevated this to "Product backlog" with the thought that providing `iqtree2` to users will be a significant performance improvement for little effort.

**Comment by huddlej** [comment]
[IQ-TREE 2.1.2 is now in Bioconda, as of today](https://github.com/bioconda/bioconda-recipes/pull/27687). The Bioconda version renames the binary to `iqtree`, for backwards compatibility, and keeps the newer `iqtree2` binary, too.

We should still implement the change proposed in this issue, though, for consistency across our tree builders.

**Comment by huddlej** [comment]
@benjaminotter, can you add the call to `find_executable` that Trevor describes above for [the `build_iqtree` function](https://github.com/nextstrain/augur/blob/24baeaf1f8fa25beefb727bccf21199d33f6b152/augur/tree.py#L129)? This will work like [the existing call for the `build_raxml` function](https://github.com/nextstrain/augur/blob/24baeaf1f8fa25beefb727bccf21199d33f6b152/augur/tree.py#L40-L55).

You should be able to test that this function works by installing [the latest IQ-TREE 2 release](https://github.com/iqtree/iqtree2/releases/tag/v2.1.2) on your path as `iqtree2` first and then also as `iqtree`.
