### ISSUE TITLE
Add index subcommand to summarize sequence content

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#639]
**Context**

While discussing a new standardized interface for reading and writing sequences in augur, we realized that the only time we need random access to sequence inputs (e.g., through BioPython's `SeqIO.index`) is when `augur filter` needs to assess the nucleotide content of sequences.

Augur's filter steps could be substantially sped up if they only needed to  inspect metadata tables instead of parsing large sequence files. Specifically, if we could calculate sequence statistics ahead of time and merge than with existing metadata, we could filter by columns in a table without needing to read sequences at each filter step.

**Description**   

@tsibley recommended the addition of an `augur index` command (or something similarly named) that could calculate the sequence composition statistics we need one time.

**Examples**

```bash
# This should work with standard FASTA files.
augur index --sequences data/sequences.fasta --output results/sequence_composition.tsv

# This should also work with compressed FASTA files.
augur index --sequences data/sequences.fasta.gz --output results/sequence_composition.tsv
```

**Possible solution**

Similar existing tools include `samtools faidx` (provides a table of sequence lengths by name) or `seqtk comp` from [Heng Li's seqtk toolkit](https://github.com/lh3/seqtk). For example, the following command might provide exactly what we need:

```bash
seqtk comp data/sequences.fasta > results/sequence_composition.tsv
```

The output looks like this for ncov sequences where the output columns are `chr, length, #A, #C, #G, #T, #2, #3, #4, #CpG, #tv, #ts, #CpG-ts` (`#4` [may represent the number of N bases](https://github.com/lh3/seqtk/issues/47)):

```
Wuhan/IVDC-HB-01/2019   29891   8942    5492    5863    9594    0       0       0       878     0       0       0
Wuhan/IVDC-HB-04/2020   29896   8947    5490    5863    9596    0       0       0       878     0       0       0
Wuhan/IVDC-HB-05/2019   29891   8944    5492    5861    9594    0       0       0       874     0       0       0
```

seqtk comp takes ~1 minute to write out the composition of a 7.4 GB file and can also ingest compressed FASTA files. Augur could wrap these fast tools in its own interface to abstract the original program interface (e.g., to provide column headings with clearer names).

**Comment by dpark01** [comment]
Alternatively: I think there are only two functions in `augur filter` that need to read actual sequence content: `--non-nucleotide` and `--min-length`. Why not just break out those two into a separate augur command entirely?

That new command could purely operate on fastas and would not even require any metadata.tsv input. (As an aside, the size of epicov these days pushed me to implement my own [min-length filter in biopython](https://github.com/broadinstitute/viral-pipelines/blob/master/pipes/WDL/tasks/tasks_nextstrain.wdl#L285-L292) that runs in about 5 mins on 450k sequences compared to >1hr for `augur filter --min-length` -- breaking it out into a separate command can make such optimizations simpler).

And if those options were separated out, `augur filter` could operate purely on metadata tsv inputs and outputs, and not even touch any sequence files.

**Comment by huddlej** [comment]
Thank you for sharing your filter approach in the WDL workflow, @dpark01. We would definitely like to get to metadata-only filtering for the same reasons you describe.

The `augur index` approach should help us get there while still maintaining backwards-compatibility of `augur filter` for people's existing workflows. The way we have implemented [the augur index prototype]((https://github.com/nextstrain/augur/compare/add-index-command) will allow people to opt-in to the new index command when they are ready, but the original interface will still work as expected.
