### ISSUE TITLE
s3 script to remove data

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#65]
there should be a way to "remove" files - simple prefix matching (like with pull) should work well, e.g. `s3.py remove nextstrain-staging --prefix zika*`

**Comment by jameshadfield** [comment]
cc @tsibley for possible inclusion in `nextstrain deploy`

**Comment by tsibley** [comment]
Mmm, perhaps. Thanks for flagging this. What's the regular use case for deleting files matching a prefix?

**Comment by jameshadfield** [comment]
Superseded by https://github.com/nextstrain/cli/issues/36
