### ISSUE TITLE
Augur subcommands > augur traits > --confidence mugration. mistyped?

### ISSUE THREAD

**Issue by reyus2** [nextstrain/augur#650]
If it is mistyped. fix this please. 
mistyped words make people like me who is not an English native gets confused.

**Comment by emmahodcroft** [comment]
Thanks! This is actually correct - the name come from a mix between 'mutation' and 'migration' as a way of calculating discrete traits. It's a recognised name in the field, but I can see how it's confusing for non-native speakers!
