### ISSUE TITLE
S3 script standard out

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#66]
@huddlej ---

The S3 script is excellent. One small suggestion:

Enabling `--verbose` is great, but the current behavior where if `-v` is not flagged then you get absolutely nothing in the standard out is weird. I had no idea if the script worked or not. I'd think you'd want just one line: "pushing ... to ...".

**Comment by huddlej** [comment]
I was going for the UNIX standard command behavior of "no news is good news", but if I just set the default logging level to the same as the "verbose" mode that will print a "pushing ... to ..." message by default. Would that be an ok solution?

**Comment by trvrb** [comment]
Sounds like a good solution.
