### ISSUE TITLE
tip-frequencies.json format question

### ISSUE THREAD

**Issue by haslamdb** [nextstrain/augur#663]
First, thanks for an amazing suite of tools. 

Problem:
I'm generating tip-frequencies.json using 'augur frequencies'. When I try 'augur export v2' (or v1) and include tip-frequencies.json I get an error (pasted below) which suggests the .json file is an array rather than a dictionary. If I remove tip-frequencies during export it works fine, even though I have a ton of other .json specified parameters in there.

I'm using augur v 10.2.0 on my machine and get the same error when I run augur frequencies and augur export v2, both in nextstrain conda environment and in the wild. 

Here are the two commands:

        augur frequencies \
             --method kde \
             --metadata Parameters/GISAID_Metadata."$today".tsv \
             --tree AllData/refined_tree.nwk \
             --narrow-bandwidth 0.05 \
             --pivot-interval 1 \
             --proportion-wide 0.0  \
             --stiffness 20 \
             --inertia 0.2 \
             --output tip-frequencies.json 

 augur export v2 \
            --tree refined_tree.nwk \
            --metadata ~/ncov/data/Parameters/GISAID_Metadata."$today".tsv \
            --node-data clades.json branch_lengths.json traits.json aa_muts.json haplotype_status.json 
              Updated_pangolin_clade.json tip-frequencies.json  \
            --auspice-config ../Parameters/auspice_config_MGML_revised.json \
            --include-root-sequence \
            --colors ../Parameters/colors_ncov.tsv \
            --lat-longs ../Parameters/lat_longs_ncov.tsv \
            --output SARS_Cov2_GSAID_Genomes.json 

And here's the error message: 
(nextstrain) david@lambda-quad:~/SARSCov2/data/AllData$         augur export v2 \
>             --tree refined_tree.nwk \
>             --metadata ~/SARSCov2/dataParameters/GISAID_Metadata."$today".tsv \
>             --node-data clades.json branch_lengths.json traits.json aa_muts.json haplotype_status.json Updated_pangolin_clade.json tip-frequencies.json  \
>             --auspice-config ../Parameters/auspice_config_MGML_revised.json \
>             --include-root-sequence \
>             --colors ../Parameters/colors_ncov.tsv \
>             --lat-longs ../Parameters/lat_longs_ncov.tsv \
>             --output SARS_Cov2_GSAID_Genomes.json  
Validating schema of 'aa_muts.json'...
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/nextstrain/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/usr/local/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/usr/local/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/export.py", line 22, in run
    return run_v2(args)
  File "/usr/local/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/export_v2.py", line 882, in run_v2
    node_data, node_attrs, node_data_names, metadata_names = parse_node_data_and_metadata(T, args.node_data, args.metadata)
  File "/usr/local/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/export_v2.py", line 829, in parse_node_data_and_metadata
    node_data = read_node_data(node_data_files) # node_data_files is an array of multiple files (or a single file)
  File "/usr/local/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/utils.py", line 191, in read_node_data
    return NodeDataReader(fnames, tree).read()
  File "/usr/local/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/util_support/node_data_reader.py", line 26, in read
    node_data = self.build_node_data()
  File "/usr/local/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/util_support/node_data_reader.py", line 35, in build_node_data
    for node_data_file in self.node_data_files:
  File "/usr/local/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/util_support/node_data_reader.py", line 51, in <genexpr>
    return (NodeDataFile(fname) for fname in self.filenames)
  File "/usr/local/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/util_support/node_data_file.py", line 18, in __init__
    self.validate()
  File "/usr/local/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/util_support/node_data_file.py", line 69, in validate
    f"`nodes` value in {self.fname} is not a dictionary. Please check the formatting of this JSON!"
RuntimeError: `nodes` value in tip-frequencies.json is not a dictionary. Please check the formatting of this JSON!
(nextstrain) david@lambda-quad:~/SARSCov2/data/AllData$ augur --version
augur 10.2.0
(nextstrain) david@lambda-quad:~/SARSCov2/data/AllData$ conda deactivate
(base) david@lambda-quad:~/SARSCov2/data/AllData$ augur --version
augur 10.2.0

I'm wondering if this is an issue with .json compatibility or am I just doing something dumb? Here's the top of my tip-frequencies.json

Many thanks!
David

{
  "MN908947.3": {
    "frequencies": [
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      0.532907,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ]
  },
  "generated_by": {
    "program": "augur",
    "version": "10.2.0"
  },
  "hCoV-19_Canada_ON-S2017_2020_EPI_ISL_755803_2020-12-01": {
    "frequencies": [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.001254,
      0.00242,
      0.002128,
      0.001754,
      0.001366,
      0.000911,
      0.000372,
      8e-05,
      8e-06
    ]
  },
  "hCoV-19_Canada_ON-S2018_2020_EPI_ISL_755804_2020-12-17": {
    "frequencies": [
      0.0,
      0.0,

**Comment by huddlej** [comment]
Hi @haslamdb! It looks like you're very close to having a working build. Unlike the "node data" JSONs that we collect into an augur export command, the tip frequencies JSON is considered a "sidecar" file by our visualization tool, Auspice. This means that the frequencies data are stored in a separate file that Auspice fetches after it loads the main tree and metadata JSON.

You can tell Auspice to look for this extra file by requesting the "frequencies" panel during the `augur export` command. For example, you can request specific panels from the command line:

```
augur export v2 --tree [...snip...] --panels tree map entropy frequencies
```

Or you can [modify your auspice config JSON to include a list of `panels` as a top-level key with "frequencies" as one of the values](https://github.com/nextstrain/ncov/blob/a6de68d1ce26ea4770498abd7c3508e09c54e9aa/nextstrain_profiles/nextstrain/global_auspice_config.json#L126-L131). After you make this change, you can omit the "tip_frequencies.json" file from the `augur export v2` inputs.

Finally, your tip frequencies file need to be named to match the corresponding main auspice JSON file. For a real-world example, [check out the default outputs of our ncov workflow](https://github.com/nextstrain/ncov/blob/a6de68d1ce26ea4770498abd7c3508e09c54e9aa/Snakefile#L91-L92) which include a main auspice JSON (e.g., `ncov_global.json`) and a corresponding tip frequencies file (e.g., `ncov_global_tip-frequencies.json`). In your example above, your auspice JSON file is named `SARS_Cov2_GSAID_Genomes.json`, so Auspice will expect your tip frequencies to live in a file named `SARS_Cov2_GSAID_Genomes_tip-frequencies.json`.

Let me know if these changes don't fix the problem though and we can continue to troubleshoot. Good luck!

**Comment by haslamdb** [comment]
John, thank you so much for your clear and detailed reply. That solved my problem. I know how busy you all are there now. Like many places we're ramping up ncov sequencing, and nexstrain is making it so much easier to understand this #*@& virus.  Again, many thanks.
