### ISSUE TITLE
augur tools do not recognize purely numeric strain IDs

### ISSUE THREAD

**Issue by dpark01** [nextstrain/augur#667]
**Current Behavior**  
If you provide input to any `augur` command where the sample IDs are all purely numerical (and match properly between the fasta headers and the `strain` column of the metadata tsv files), `augur` will fail to see the match between the metadata tsv and fasta files. Current workaround is to ensure sample names contain alphabetic characters.

**Expected behavior**  
Numeric sample IDs should be accepted if otherwise consistent between fasta and metadata tsv.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Produce a minimal data set with 2-3 sequences named 2003040178, 2003050035, etc. The sample metadata can be as minimal as `strain`, `date`, `region`. Fasta sequence content can be anything.
2. `docker run -it --rm -v $(pwd):/mnt/data nextstrain/base:build-20201214T004216Z /bin/bash`
3. Run `cd /mnt/data; augur filter input.fasta --metadata metadata.tsv --output filtered.fasta` within the docker container.
4. Watch all sequences get dropped with the message "No meta data for XXX, excluding from all further analysis."

**Possible solution**  
I think the problem is that augur loads the metadata as a pandas data frame and automatically parses the `strain` column as integers instead of strings--so the [set membership search fails](https://github.com/nextstrain/augur/blob/master/augur/filter.py#L171) since python ints are not equal to strings. Perhaps always force the strain column to load as a string?

**Your environment: if running Nextstrain locally**  
 - Operating system:   nextstrain/base:build-20201214T004216Z

**Additional context**  
Discovered by Colorado DPHE, reporting on their behalf.

**Comment by emmahodcroft** [comment]
I ran into this at a pre-pandemic workshop, and can second that it seemed to be a problem that pandas loads `strain` as a number if all the characters are numbers, which then won't match the 'String' `strain`s from elsewhere.

**Comment by rneher** [comment]
@huddlej: would fixing this be as simple as making sure `strain` or `name` are parsed as `str` here

https://github.com/nextstrain/augur/blob/master/augur/util_support/metadata_file.py#L91

i.e. smth like

`return df.astype{('strain': str})

**Comment by tsibley** [comment]
`pandas.read_csv()` takes a `dtype` parameter you can use instead of calling `.astype()` later, which avoids ever converting to the wrong type.

You might also consider using the new `'string'` dtype instead the `'object'` dtype that you get by giving the `str` class.

**Comment by victorlin** [comment]
This is an active bug for `augur filter`. The fix was applied for metadata IDs back when sequence IDs were always read as strings. Now, sequence IDs will be read as numerical since they come from a sequence index DataFrame, which suffers from the same problem as before.

What's funny is that both the fix for metadata (b07aed47e7470074d4832bf4bc9965ee2db77d9c) and the switch to use sequence index (a2ee0344546b6f528e7481d1c4bd6b04242663a9) were released in the same version, so this bug was never fixed.

I'll make a PR.

**Comment by tsibley** [comment]
> What's funny is that both the fix for metadata (https://github.com/nextstrain/augur/commit/b07aed47e7470074d4832bf4bc9965ee2db77d9c) and the switch to use sequence index (https://github.com/nextstrain/augur/commit/a2ee0344546b6f528e7481d1c4bd6b04242663a9) were released in the same version, so this bug was never fixed in any released version.

Oh man, ain't that software. Ha.
