### ISSUE TITLE
Remove matplotlib and seaborn dependencies

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#672]
## Context

Augur supports [a "full" installation](https://github.com/nextstrain/augur/blob/8d69df645b2bfce8778861402ad5cf3a104d8fb3/setup.py#L59-L63) that installs optional dependencies including cvxopt, matplotlib, and seaborn. Although cvxopt is required for titer models to work (arguably a dependency that should be installed anyway), the plotting modules are only used in [an old titer model function](https://github.com/nextstrain/augur/blob/efcc8be3bcf72ab4beb237afcc5b4b002bbaa806/augur/titer_model.py#L508-L509) and two test functions in the frequency estimation module ([one](https://github.com/nextstrain/augur/blob/24e5d2940918b10e2be39d6e7a63dcceff792860/augur/frequency_estimators.py#L748) and [two](https://github.com/nextstrain/augur/blob/24e5d2940918b10e2be39d6e7a63dcceff792860/augur/frequency_estimators.py#L782)).

## Description and possible solution

We should remove the two plotting modules as dependencies, move the corresponding plotting code to documentation for the titer model and frequencies (respectively), move cvxopt to the main dependency list ([now that we use the latest version that has pre-built wheels](https://github.com/nextstrain/augur/pull/671)), and remove the "full" installation section of the project's setup module.

The related plotting code is effectively inaccessible to anyone who would want to use it from the command line and requires advanced knowledge of Augur's inner workings to get this code working from a Python shell/notebook. Moving the code to documentation would allow us to better document these Augur components and provide inline examples of what the plot outputs should look like.

Most of the hard work in addressing this issue would be the writing of documentation and testing of the old plotting code. The easier solution would be to delete the plotting code and associated dependencies completely.

**Comment by joverlee521** [comment]
Bumping this old issue because I had to exclude the "full" installation in [my branch to add `evofr` to the nextstrain/base](https://github.com/nextstrain/docker-base/commit/92cf58677adc0f3cebb750d2a94dd56393c9114d). `matplotlib` was causing [an error](https://github.com/nextstrain/docker-base/runs/7754062474?check_suite_focus=true#step:5:3114) in the image building process after I switched to Python 3.9

Should we just move `cvxopt` to the main dependency list and deal with `matplotlib` and `seaborn` later?

**Comment by tsibley** [comment]
[More context on the usage of these](https://github.com/nextstrain/docker-base/pull/50#discussion_r956227258), which I sifted thru before I knew about this issue :upside_down_face:

**Comment by huddlej** [comment]
@rneher may have a preference about my recommended solution to this issue, but I still stand by the plan to:

1. include cvxopt as a primary dependency
2. drop matplotlib and seaborn as dependencies along with the "full" installation option
3. move the plotting code from titers into documentation

Probably 1 and 2 would be fine.
