### ISSUE TITLE
ERROR: skyline optimization by TreeTime has failed.

### ISSUE THREAD

**Issue by Dimitralex** [nextstrain/augur#685]
**Current Behavior**  
I have been running a very large nextstrain build with the subsampled sequences being around 12,800.  I have been running these on a cluster and computation has taken days.  However, in the **augur refine** job of the process, I got the following error (Note: I could not get a traceback of the error as I was not running it on my machine):

ERROR: skyline optimization by TreeTime has failed.
augur refine is using TreeTime version 0.8.1

332.75	TreeTime.reroot: with method or node: ['Wuhan/Hu-1/2019',
      	'Wuhan/WH01/2019']

430.38	TreeTime.reroot: with method or node: ['Wuhan/Hu-1/2019',
      	'Wuhan/WH01/2019']
pruning leaf  Israel/CVL4659/2020
pruning leaf  Mozambique/INS-K007880/2020

528.25	WARNING: Previous versions of TreeTime (<0.7.0) RECONSTRUCTED sequences
      	of tips at positions with AMBIGUOUS bases. This resulted in unexpected
      	behavior is some cases and is no longer done by default. If you want to
      	replace those ambiguous sites with their most likely state, rerun with
      	`reconstruct_tip_states=True` or `--reconstruct-tip-states`.

2303.65	TreeTime.reroot: with method or node: ['Wuhan/Hu-1/2019',
       	'Wuhan/WH01/2019']

3267.23	###TreeTime.run: INITIAL ROUND

4393.03	TreeTime.reroot: with method or node: ['Wuhan/Hu-1/2019',
       	'Wuhan/WH01/2019']

4465.39	###TreeTime.run: rerunning timetree after rerooting

5970.06	###TreeTime.run: ITERATION 1 out of 2 iterations

13610.83	###TreeTime.run: ITERATION 2 out of 2 iterations

27119.17	Coalescent:optimize_skyline:...failed:     fun: -112679.84648171504
        	jac: array([ -21.9921875 ,  178.13671875, -100.42578125, 1174.08496094,
        	-145.85546875, -996.0703125 , -993.13867188, -763.4453125 ,
        	246.16015625, -948.61523438, -970.47460938,  -40.16796875,
        	-746.54394531,  945.55273438,  407.5546875 ,  605.66992188,
        	-169.640625  ,  479.41210938, -395.32421875,   90.87109375])  message:
        	'Iteration limit reached'     nfev: 2213      nit: 100     njev: 100
        	status: 9  success: False        x: array([-6.29040290e+00,
        	1.21826862e+00, -7.56480452e+00,  8.79191811e+00,
        	-1.51294004e+01, -2.80802700e+00, -3.37311919e+00, -2.69397067e+00,
        	-1.15375664e+00, -2.85036566e+00, -3.13810515e+00, -7.23357207e-01,
        	-9.32496758e+01,  8.60053917e-01,  9.06861664e-01,  2.06789257e+00,
        	-1.97791357e+01,  7.83913111e-01, -4.89824824e+01,  8.23297247e-02])

36170.25	###TreeTime.run: FINAL ROUND - confidence estimation via marginal
        	reconstruction

Inferred a time resolved phylogeny using TreeTime:
	Sagulenko et al. TreeTime: Maximum-likelihood phylodynamic analysis
	Virus Evolution, vol 4, https://academic.oup.com/ve/article/4/1/vex042/4794731

**Expected behavior**  
Everything should have worked as I have tested my setup on small datasets and there were no issues.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Sign into GISAID EpiCov, go to the Downloads tab and download the nextmeta and nextfasta
2. git clone https://github.com/nextstrain/ncov.git       in order to create an ncov folder
3. create a profile (my_new_build_name) in my_profiles that links to the data downloaded and is identical in all other respects to the getting_started profile that is included in the default tutorial
4. Run (on the cloud or in a cluster) that build using snakemake --cores 16 --profile ./my_profiles/my_new_build_name
5. After a long time, get the error message mentioned above in the augur refine job after the augur tree job has completed and created a tree_raw.nwk file.

**Possible solution**  
Not too sure, but this seems similar to #554 and https://github.com/nextstrain/ncov/issues/496 .  So, based on these the error is probably in line 221  of file refine.py:

if args.coalescent=='skyline':
            try:
                skyline, conf = tt.merger_model.skyline_inferred(gen=args.gen_per_year, confidence=2)
                node_data['skyline'] = [[float(x) for x in skyline.x], [float(y) for y in conf[0]],
                                        [float(y) for y in skyline.y], [float(y) for y in conf[1]]]
            except:
                print("ERROR: skyline optimization by TreeTime has failed.", file=sys.stderr)
                return 1

Hence, I believe I entered the except condition here.  I am not sure what to do now though

I have the newest versions of everything, as I downloaded all the files from github about a week or two ago.

**Your environment: if running Nextstrain locally**  
 - Operating system: Ubuntu 18.04.3 LTS
 - Version (e.g. `auspice 2.7.0`):  augur 11.0.0, Auspice version 2.23.0, nextstrain.cli 2.0.0.post1

**Additional context**  
The issue may be that I am simply feeding in files that are too large for the software to handle.  Hence, there may be a way for me to get around generating the entire build if this issue does not get resolved.  I basically want to download all sequences of SARS CoV-2 that have been sequenced so far, subsample them based on the augur subsampling and sequence selection model and then translate the subsampled sequences into separate protein files (proteins S, E, M, N, ORF1a, etc.).  I'd appreciate it if there is either a solution to this error, or a way to avoid the entire build, as I am not interested in creating any graphs or representing the data in any graphical way.  Thank you very much!

**Comment by Dimitralex** [comment]
One thing I tried for now is the following:

In _workflow/snakemake_rules/main_workflow.smk_   , I changed the parameters fed into the augur refine process and set --coalescent opt.  If this does not work I will try deleting the --coalescent command.  Not too sure if I am causing other problems though.

**Comment by rneher** [comment]
This error is due to failures to optimization the coalescent skyline in your very large analysis. The optimizer from scipy hits its default limit of the number of iterations. One could either go in and increase this limit, or work with `opt` as you suggest.

**Comment by Dimitralex** [comment]
Thank you!  Using opt ended up working for me.
