### ISSUE TITLE
Dealing with missing country region values

### ISSUE THREAD

**Issue by lasupernova** [nextstrain/augur#716]
Hi, I am currently trying to run nextstrain, however my dataset does not have complete information on the region/country. I have a few entries (15 out of 99) that do have NaN values for both region and country.

Could you please advise as to how to address this and still use nextstrain?

Thanks in advance :)

**Comment by rneher** [comment]
nextstrain should be able to deal with such missing data. we commonly use `?` to denote missing information.

**Comment by lasupernova** [comment]
Ok, thanks  a lot for your reply, I will replace NaN with `?`.
Could you tell me what it will do for the lat_longs info for this data? I imagine it will simply be left blank?
