### ISSUE TITLE
'No sequence data' although all data is there

### ISSUE THREAD

**Issue by lasupernova** [nextstrain/augur#717]
**Current Behavior**  
I get an error message saying that all samples were dropped because there is no sequence data, but the fasta file is fine and the metadata file also (and they have matching strain names). 
Nextstrain starts running just fine, but then I get the error (see log below)

**Expected behavior**  
I would have expected the workflow to just run

**How to reproduce**  
Steps to reproduce the current behavior:  
`nextstrain build --cpus 1 .`

**Your environment: if running Nextstrain locally**  
 - Operating system:  Red Hat
 - Browser:  n/a - error occurs during the Augur part

**Additional context**  
I attached the error log below, as well as the fasta and metadata file (both as .zip as .fasta ad .tsv extensions are not allowed)

[metadata_duplicates_dropped.zip](https://github.com/nextstrain/augur/files/6345215/metadata_duplicates_dropped.zip)
[2021-04-20T155941.272124.snakemake.log](https://github.com/nextstrain/augur/files/6345150/2021-04-20T155941.272124.snakemake.log)
[sequence2.zip](https://github.com/nextstrain/augur/files/6345196/sequence2.zip)

**Comment by huddlej** [comment]
Hi @lasupernova, thank you for providing such a clear description of the issue and the associated data. It looks like there are a couple of formatting issues with the sequence data that are causing Augur to only recognize one of your sequences.

The first issue is that [the FASTA format doesn’t allow spaces in the sequence identifier](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp) (the value immediately after the `>` symbol in the defline). Any text following the first space is considered a sequence description. This means your sequences with names like `Bovine coronavirus strain Quebec, complete genome` get interpreted as a sequence id of `Bovine` and a description of `coronavirus strain Quebec, complete genome`. As a result, all of your sequences that start with `Bovine` get treated as the same sample id (despite their different sequence contents). The solution here is to make sure your sequence ids in the FASTA file match the ids in the `strain` column of your metadata file.

Another issue is that some of your sequence deflines are missing line returns such that the first line of the sequence data gets included in the defline. For example, the following snippet shows the first two lines of the `4-17-25` record:

```
 >4-17-25 GATTGTGAGCGATTTGCGTGCGTGCATCCCGCTTCACTGATCTCTTGTTAGATCTTTTCATAATCTAAAC
TTTATAAAAACATCCACTCCCTGTAGTCTATGCCTGTGGGCGTAGATTTTTCATAGTGGTGTCTATATTC
```

This formatting will cause the first few characters of the associated sequences to get omitted from your analysis. The solution here would be to doublecheck your code/workflow for downloading and merging sequences from NCBI or other data sources to make sure deflines have the expected line returns at the end.

Within the Nextstrain/Augur ecosystem, we could also do a better job of providing tools to validate sequences and metadata. There are so many ways for FASTA files to be invalid, that we probably can't catch every case, but we could at least try to catch some of the obvious big issues like the ones you've encountered here.

I'm going to close this issue, but I'll write up a separate issue describing a potential interface to validate sequences and metadata and we'll discuss this in the Nextstrain group. If you have any follow up questions, we can still continue the conversation here.
