### ISSUE TITLE
Error in rule index_sequences

### ISSUE THREAD

**Issue by jsan4christ** [nextstrain/augur#718]
Dear Nextstrain team,

I have this error with augur,  there is no detailed log,

Please advise
---

Error in rule index_sequences:
    jobid: 20
    output: results/combined_sequence_index.tsv
    log: logs/index_sequences.txt (check log file(s) for error message)
    shell:
        
        augur index             --sequences results/filtered.fasta             --output results/combined_sequence_index.tsv
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile logs/index_sequences.txt not found.

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

I'm running augur 11.0.0,

**Comment by huddlej** [comment]
Hi @jsan4christ! First, I'm sorry about that missing log output from the index rule. I've updated the ncov workflow to make sure this log output gets created as expected. If you pull the latest version of the workflow's repository, you should get output written to this log.

Second, [we added the `augur index` command in version 11.1.0](https://github.com/nextstrain/augur/blob/master/CHANGES.md#1110-12-february-2021), so you'll need to upgrade Augur to fix the immediate issue. The easiest way to get the latest version of Augur when you run the ncov workflow is to run Snakemake with the `--use-conda` flag. For example, you can run the "getting started" version of the workflow like so:

```
snakemake --use-conda --profile my_profiles/getting_started/
```

Snakemake will use the workflow's Conda environment definition that we maintain and automatically create/update/use a Conda environment for each rule as needed. For more details, check out [Snakemake's documentation about integrated package management with Conda](https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#integrated-package-management).

**Comment by jsan4christ** [comment]
Thanks @huddlej,

You are right, I only realized a while later that reinstalling / upgrading without specifying the environment name was applying changes the the base installation. I had uninstall from base, then run install with the --name nextstrain option to install to the right environment and everything was fine after.
