### ISSUE TITLE
Mask nonsense sites

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#72]
Sometimes sequences come in with sites that RAxML doesn't know what to do with. For example,
```
>A/Ireland/61451/2017
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNIRLHAGGTTTTCGCTCAAAAAATTCCT
GGAAATGACAATAGCACGGCAACGCTGTGCCTTGGGCACCATGCAGTACCAAACGGAACG
```
This currently breaks the build with RAxML erroring out. These sites should be masked to to `N`. Here's a list of nucleotide ambiguity codes http://reverse-complement.com/ambiguity.html. These are all okay. Anything that's not on this list should be masked.

**Comment by danielsoneg** [comment]
I’ll take a look at this today.

Assuming this applies primarily to `augur tree` and assuming it should be done to input to all tree-ing commands, not just RAXML so we’re not creating spurious relationships based on bad characters.

**Comment by danielsoneg** [comment]
Alright, that was a bit interesting.

Code's up - a bit of refactoring, but not a huge amount of change all said and done.

Two things I noticed while working on this - 
1. Noted this in the pull as well, but in the example above, IRLH - R and H are valid codes by the link above, so the resulting mask is NRNH - I don't know how the treeing works, but this may still produce spurious variations.

2. The code to read VCF files produces Extremely truncated output - it basically compresses down the output to only the sites in which the included strains differ from the reference strain. In other words, if the reference and the sequences are ~1000 pair, but they only differ across 10 sites, the sequences written out to the fasta file are only those 10 sites for each strain. 

I'm absolutely new to this, so I'm wondering, would that produce a lineage tree that overemphasizes the differences?

**Comment by huddlej** [comment]
@danielsoneg I'm reviewing older issues and came back across this one. We had [talked way back in April about resolving this with an `--mask-invalid-sites` flag](https://github.com/nextstrain/augur/pull/459#issuecomment-605367604) for `augur mask` after the refactor you implemented.

Would you still be interested in adding support for this flag? I totally understand if you are burned out on augur masking and filtering these days. If that's the case, I'll move this back to the "To do" column, so we know it's open for someone else to grab.

**Comment by danielsoneg** [comment]
Hey @huddlej, sorry, I got distracted this week 😅 - just opened #592 that fixes this.
