### ISSUE TITLE
filter: Do not build a sequence index when the user hasn't requested sequence-based filters

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#732]
## Context

When the user does not provide a sequence index to augur filter, [filter will build an index on the fly](https://github.com/nextstrain/augur/blob/15dfc8bc5c5a570066ddd5601c9aa82e0c1d2b7d/augur/filter.py#L218). This process can take a long time when the input sequences are large, though, and the index is not necessary when the user hasn't requested any sequence-based filters.

## Description and possible solution

Check for whether the user has requested any sequence-based filters (based on [inputs from the sequence filters group](https://github.com/nextstrain/augur/blob/15dfc8bc5c5a570066ddd5601c9aa82e0c1d2b7d/augur/filter.py#L120-L122)) and skip building the sequence index if none have been requested.

## Examples

In the following example, the user only wants to extract metadata and sequences for specific strains without any additional sequence-based filters. The index step of this command takes 28 minutes for the current GISAID sequences even though the index is never used.

```bash
augur filter \
    --metadata data/metadata_gisaid.tsv.gz \
    --sequences data/sequences_gisaid.fasta.gz \
    --exclude-all \
    --include strains_washington.txt strains_north-america.txt strains_global.txt \
    --output-sequences data/subsampled_sequences_gisaid.fasta.gz \
    --output-metadata data/subsampled_metadata_gisaid.tsv.gz
```

**Comment by benjaminotter** [comment]
With this [possible solution](https://github.com/nextstrain/augur/blob/da01c2350652769e35d1b43f4aca4e7730aff28e/augur/filter.py#L210) the generation of an index file is skipped if both `--min-length` and `--non_nucleotide` were not specified.
However, when running the functional tests with cram the last test in `filter.t` fails:
```
@@ -253,14 +253,12 @@
   >  --query "country != 'Colombia'" \
   >  --include "$TMP/include.txt" \
   >  --output-strains "$TMP/filtered_strains.txt"
-  4 strains were dropped during filtering
-  \t1 had no sequence data (esc)
-  \t1 had no metadata (esc)
+  2 strains were dropped during filtering
   \t3 of these were filtered out by the query: (esc)
   \t\t"country != 'Colombia'" (esc)
    (esc)
   \t1 strains were added back because they were requested by include files (esc)
   \t1 strains from include files were not added because they lacked sequence or metadata (esc)
-  8 strains passed all filters
-
-  $ rm -f "$TMP/filtered_strains.txt"
+  9 strains passed all filters
+
+  $ rm -f "$TMP/filtered_strains.txt"
```
@huddlej I suppose this has something to do with the fact that the input files are in vcf format... Could you take a look at this?

**Comment by huddlej** [comment]
@benjaminotter Thank you for getting this started and testing it. The problem ended up being a little more complex in that we use the sequence index (and the sequences themselves) to filter data even if there are no explicit sequenced-based filters. When the user provides both metadata and sequence data, we shouldn't output strain names, metadata, or sequences for strains that are missing from any of the inputs.

I've pushed a commit that should fix the issue to [the build-index branch](https://github.com/nextstrain/augur/compare/build-index) and created [a PR for this](https://github.com/nextstrain/augur/pull/738). Would you mind looking over the code I added to see if you notice anything especially strange or incorrect?
