### ISSUE TITLE
Remove Snakemake as a dependency

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#753]
**Context**  

Snakemake is not required to use Augur, but we still use it for some functional tests in Travis CI. These tests can be easily run with cram and this additional dependency of Snakemake adds unnecessary complexity to the project. It also causes recent versions of Snakemake from a Conda installation to get overwritten by an older, pip-installed, and less complete version of Snakemake which complicates the dev environment.

**Description**   
Replace Snakemake tests in CI with cram tests and remove Snakemake as a dev dependency.

**Comment by victorlin** [comment]
@huddlej added [this comment](https://github.com/nextstrain/augur/pull/1289#pullrequestreview-1603332297) describing a good path forward:

> Even though the dependencies issue that arose is separate from the goal of this PR, we should really plan to remove Snakemake as a dev dependency in a separate PR. My original hope was that cram tests would replace the original Snakemake build tests, but the newer pathogen-repo-ci checks seem to fill the original goal of those Snakemake tests instead. We could probably add a pathogen-repo-ci for TB, port [the remaining builds tests](https://github.com/nextstrain/augur/tree/master/tests/builds) to cram, and then drop the Snakemake dep.

**Comment by jameshadfield** [comment]
Those tests (`./tests/builds`) are very old, from memory I implemented them as the first form of testing in Augur, and I think they have been more than superseded by subsequent additions over the years.
