### ISSUE TITLE
Question: Scope to improve scalability

### ISSUE THREAD

**Issue by cjain7** [nextstrain/augur#755]
Dear Augur/Nextstrain authors,

I'm a bioinformatician/algorithms/HPC researcher. I've been following up the documentation of the Augur pipeline to check if there are any scalability bottlenecks which may need to be resolved in future for analysis of genomes. As count of genomes being sequenced continues to grow exponentially, certain components may need to accelerated with faster algorithmic alternatives. In your experience, are there any particular steps in the pipeline which we can help improve and contribute to this awesome work.

Thanks!
Chirag ([www](https://at-cg.github.io))

**Comment by huddlej** [comment]
Hi @cjain7, thank you for the offer to help out! We have just resolved [one of our biggest issues with scalability](https://github.com/nextstrain/augur/issues/699) and will likely continue to face issues with the run-time of commands like `augur index` and the `read_sequences` functionality of our `io.py` module, as the GISAID SARS-CoV-2 database grows.

We don't have any specific issues open now that I could refer you to, but if you'd like to keep up with this topic more generally, [the Nextstrain discussion board](https://discussion.nextstrain.org/) is a good place to start.
