### ISSUE TITLE
[filter]: Probalistic sampling doesn't use the given RNG seed

### ISSUE THREAD

**Issue by tsibley** [nextstrain/augur#770]
**Current Behavior**  
`augur filter`'s probabilistic sampling (`--probabilistic-sampling`) doesn't seed the RNG it uses, which I believe will lead to unstable output even when `--subsample-seed` is given. `--probabilistic-sampling` is enabled by default, but only used when there are more groups than the requested number of sequences (`--subsample-max-sequences`).

**Expected behavior**  
All RNGs are seeded with `--subsample-seed`, leading to stable output.

**How to reproduce**  
<mark>TKTK</mark>

**Possible solution**  
Pass the given `--subsample-seed` into the RNG used for probabilistic sampling: https://github.com/nextstrain/augur/blob/e7728559417cd98a426bf5cb99a257b63fdc705f/augur/filter.py#L1079-L1080

**Your environment: if running Nextstrain locally**  
 - augur e772855  

**Additional context**  
Found this by inspection when digging into behaviour reported by a user on our [discussion forums](https://discussion.nextstrain.org/t/augur-filter-subsample-seed-reproducible-example/723). However, I don't think the user's issue is related to this apparent bug.

**Comment by tsibley** [comment]
Hmm, maybe not a bug given 87ca73c's message:

> We do not pass a seed value to numpy random generator prior to Poisson sampling or the generator will always sample the same values for a given mean (i.e., all queues will have the same size). Use the random seed for generating random priorities when none are provided by the user.

but could be better commented and documented?

**Comment by huddlej** [comment]
The commit 87ca73c has been superseded by [a different approach generating priority queues](https://github.com/nextstrain/augur/blob/e7728559417cd98a426bf5cb99a257b63fdc705f/augur/filter.py#L1080) and the issue described in that commit is no longer actually an issue.

#772 resolves the issue with probabilistic subsampling not using the random seed.
