### ISSUE TITLE
ValueError: Rerooting failed!

### ISSUE THREAD

**Issue by lasupernova** [nextstrain/augur#775]
I ran the following line: and got the valueError below. Could you please advise on what to do?
I have used NextStrain several times in the past and have never encountered this error before. My input files are also in the same form as files during my previous NextStrain analyses.
Running this on a Linux server.
Thanks in advance for any help :)

`augur refine --tree results/tree_raw.nwk --alignment results/aligned.fasta --metadata data/metadata.csv --output-tree results/tree.nwk --output-node-data results/branch_lengths.json --timetree --coalescent skyline  --date-confidence --date-inference marginal --clock-filter-iqd 4`

and got the following error:
```
augur refine is using TreeTime version 0.8.1

4.06    TreeTime.reroot: with method or node: least-squares

4.09    TreeTime.reroot: rerooting will ignore covariance and shared ancestry.

11.02   TreeTime.reroot: with method or node: least-squares

11.05   TreeTime.reroot: rerooting will ignore covariance and shared ancestry.
pruning leaf  FJ839877.1

17.72   WARNING: Previous versions of TreeTime (<0.7.0) RECONSTRUCTED sequences of
        tips at positions with AMBIGUOUS bases. This resulted in unexpected
        behavior is some cases and is no longer done by default. If you want to
        replace those ambiguous sites with their most likely state, rerun with
        `reconstruct_tip_states=True` or `--reconstruct-tip-states`.

30.17   TreeTime.reroot: with method or node: least-squares

30.18   TreeTime.reroot: rerooting will account for covariance and shared
        ancestry.
TreeRegression.find_best_root: No valid root found! True
Traceback (most recent call last):
  File "/usr/bin/anaconda3/envs/nextstrain/bin/augur", line 10, in <module>
    sys.exit(main())
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/augur/refine.py", line 206, in run
    tt = refine(tree=T, aln=aln, ref=ref, dates=dates, confidence=args.date_confidence,
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/augur/refine.py", line 67, in refine
    tt.run(infer_gtr=infer_gtr, root=reroot, Tc=Tc, time_marginal=marginal,
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/treetime/treetime.py", line 168, in run
    self.reroot(root=root, clock_rate=fixed_clock_rate)
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/treetime/treetime.py", line 438, in reroot
    new_root = self._find_best_root(covariation=use_cov,
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/treetime/treetime.py", line 803, in _find_best_root
    return Treg.optimal_reroot(force_positive=force_positive, slope=slope)['node']
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/treetime/treeregression.py", line 435, in optimal_reroot
    raise ValueError("Rerooting failed!")
ValueError: Rerooting failed!
```

**Comment by huddlej** [comment]
Hi @lasupernova, this is a data-specific error that can occur when TreeTime can't fit a regression model for the given inputs. This error could indicate a problem with the input data, so you may want to review the topology of your input tree and the quality of your multiple sequence alignment before proceeding.

If your inputs look reasonable, you can workaround this error with two different approaches:

 1. You can provide the names of one or two specific input sequences to use for rooting the tree. For example, [we specify the Wuhan/Hu-1/2019 strain as the root for our time trees in our SARS-CoV-2 workflow](https://github.com/nextstrain/ncov/blob/71508e0a31935c0682f2ad4b17ce862f2328c229/defaults/parameters.yaml#L107). 

 2. You can tell TreeTime to not reroot the input tree by passing the `--keep-root` flag. This flag overrides any other inputs to `--root`.

The correct approach will strongly depend on your input data. Let us know if any of the above end up addressing your issue. For now, I'm going to close this Augur issue. If you'd like to continue this discussion, reach out through [our Nextstrain discussion board](https://discussion.nextstrain.org/) where you'll also be able to get feedback from the broader community of Nextstrain users (many of whom probably have encountered the same issues you're experiencing!).
