### ISSUE TITLE
Unable to conda/mamba install on Windows 10

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#785]
[Current installation docs](https://docs.nextstrain.org/projects/augur/en/13.0.2/installation/installation.html) point to `conda`/`mamba` for installing augur. It works fine on M1 Mac, but fails on Windows 10.

`conda`:

```
> conda install -c conda-forge -c bioconda augur -y
...
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:
```

The error above is strange as it doesn't output anything else. However, with `mamba` the error is obvious:

```
> mamba install -c conda-forge -c bioconda augur
...
Encountered problems while solving:
  - nothing provides mafft needed by augur-10.0.0-py_0
```

I also saw the same message for `fasttree` a different time, probably due to dependency solving order differences if it fails on the first encountered error.

These errors make sense because [fasttree](https://anaconda.org/bioconda/fasttree) and [mafft](https://anaconda.org/bioconda/mafft) aren't `noarch` unlike [augur](https://anaconda.org/bioconda/augur) for example.

Since these are external dependencies, I don't think there's an easy way to support running augur on Windows 10 natively without WSL. It looks like this has been already figured out with the [ncov setup docs](https://docs.nextstrain.org/projects/ncov/en/latest/analysis/setup.html). If so, we just need to add a note in the augur installation docs to use WSL if on Windows.

**Comment by huddlej** [comment]
@victorlin This issue is caused by lack of Windows support for multiple Augur dependencies that are not likely to support Windows soon. Your note about lack of "native" support for Windows in the new installation docs is the best we can do to address this issue for now.
