### ISSUE TITLE
tree: excluded sites logic relies on deprecated BioPython interface for mutable sequences

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#787]
**Current Behavior**  
[The logic for excluding specific sites from tree building relies on a call to `tomutable`](https://github.com/nextstrain/augur/blob/8b9276f2ab41c5118df9387d8abfb5dc56ac0fda/augur/tree.py#L327), a function that has been deprecated by BioPython. As a result, users see a warning like this when they run augur tree with excluded sites (e.g., the ncov workflow):

```
BiopythonDeprecationWarning: myseq.tomutable() is deprecated; please use MutableSeq(myseq) instead.
```

**Possible solution**  
Replace [all instances of `seq.tomutable()`](https://github.com/nextstrain/augur/search?q=tomutable) with `MutableSeq(seq)`.

**Additional context**  
[Issue raised by Grant Vestal via the discussion forum](https://discussion.nextstrain.org/t/biopython-deprecation-warning/856).

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this. Is there anyone working on it already?

**Comment by huddlej** [comment]
It's all yours, @Carlosbogo! You can open a draft PR with a fix or comment on this issue if you run into any issues with the development environment prior to opening a PR. Thank you!
