### ISSUE TITLE
Some questions about the frequencies

### ISSUE THREAD

**Issue by Eudora32** [nextstrain/augur#800]
I am writing to enquire some questions about the frequencies of some COVID-19 mutations on Nextstrain. 
There are two questions troubled me. One is the data of frequencies about Delta mutation, which containing 21A, 21I, 21J. During November 30 to December 3, 2021, I found that the frequencies of 20J above 90% (Fig.1), 21A only 2%. However, it decrease to less than 1% on December 6, 2021, and 21A accounted for 87% (Fig.2). What made it such huge change? Another is the frequencies about Omicron mutation, I found it reached 1% on December 2, 2021, and the time point is November 21 (Fig.3). According to GISAID, the first omicron genetic sequence submitted by Hong Kang on November 22, and the number of Omicron genomic sequenses less than 100 on November 25. Until December 6, 2021, the number of omicron genetic sequence submitted was 577, there showed the frequencies of micron was 4% (Fig.3) on the nexstrain. So, it made me confused. How is it calculate? I am hoping your helping.

![image](https://user-images.githubusercontent.com/83941084/144800715-fcfdf9a7-db93-4fe8-a7f7-4d5f35c52af5.png)
![image](https://user-images.githubusercontent.com/83941084/144800807-f2437941-d785-4067-ac7d-f2ba515d3c90.png)
![image](https://user-images.githubusercontent.com/83941084/144800841-d289d8c1-46aa-40b6-8550-4da995b98749.png)
![image](https://user-images.githubusercontent.com/83941084/144800888-4a945f2f-88a4-47d9-94c6-d1822c369e80.png)

**Comment by emmahodcroft** [comment]
Dear @Eudora32 -- I'm so sorry this has caused confusion. We had some kind of issue in our pipeline yesterday, where the assignments for 21A (Delta) did not end up in the right place in the tree. Normally [(as you can see on 3rd Dec](https://nextstrain.org/ncov/gisaid/global/2021-12-03)) it should be a 'parent' to 21I and 21K:
![image](https://user-images.githubusercontent.com/14290674/144825281-c7d10268-618f-4378-a12e-cd62aa1b969c.png)

Instead, on the [5th](https://nextstrain.org/ncov/gisaid/global/2021-12-05), the assignment for 21A ended up 'inside' of 21J:
![image](https://user-images.githubusercontent.com/14290674/144825414-aec8e99b-1abb-47f3-a14c-c328d368adde.png)

This, in turn, then impacts how the frequencies show up in the graphs.

I'm very hopeful this issue should be corrected with the new runs that will happen today, but I'm also going to investigate to see if there are some bad sequences which are causing this. Thank you for alerting us to the problem!

**Comment by Eudora32** [comment]
@emmahodcroft Thank you very much for your reply and detailed explanation. I also want to know something about the frequencies. For the frequencies of omicron, today I saw it increased to 14% on Nextstrain, and the number of genomic sequence for omicron was 688. According the number of genomic sequences of omicron submmited on GISAD, the frequencies of omicron must be less than 14%. So, i want to know how the frequencies calculated out is, or what date referenced when calculating. Could you please help me？Thank you for your time again.

**Comment by emmahodcroft** [comment]
@Eudora32 I'm not sure if there may have been a transient issue in the frequencies, but currently Omicron is showing at 3%. However, this is likely an overestimate of the global frequency due to preferential sequencing, and those sequences coming faster. It's also important to keep in mind that the frequencies displayed are smoothed in order to not have jaggedness to the display from data being different from week to week, and that the frequencies show 1 week intervals. I hope that helps!
