### ISSUE TITLE
Replace utils.read_metadata with io.read_metadata throughout Augur

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#813]
### Context

`utils.read_metadata` and `io.read_metadata` have similar functionality in reading the metadata file.

1. `utils.read_metadata` reads the file in entirety and has an option to return as dictionary.
2. `io.read_metadata` reads the file in chunks.

`io.read_metadata` is a more recent version of `utils.read_metadata` created to address performance issues on large datasets. However, this has only been used by `augur.filter` where it was necessary for [nextstrain/ncov](https://github.com/nextstrain/ncov).

### Proposal

1. Update `io.read_metadata` for parity with `utils.read_metadata`, and use it as the single function for reading metadata in all Augur subcommands.
2. Replace `utils.read_metadata` with an import redirect (i.e. in utils.py, `import read_metadata from .io`) and add a `DeprecationWarning`.
3. Remove redirect in a major version bump.

**Comment by victorlin** [comment]
@huddlej do we want to add the duplicated check to `io`? Or more generally, is there any feature not worth migrating from `utils.read_metadata` to `io` (besides reading whole file vs. chunks)?

**Comment by huddlej** [comment]
@victorlin This proposal sounds great. I don't think we should add the duplicated check to `io`. We do need to handle duplicated data better in augur, but this internal function is probably not the place to do it.

Just to clarify, the new `read_metadata` does not read data in chunks by default, but it supports passing the `chunk_size` argument through to pandas.
