### ISSUE TITLE
Unclear which version is referred to by `stable`: add `stable` version number visibly

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#817]
Our documentation default seems to be `stable`, at least when I google.

However, I can't figure out which version `stable` corresponds to. It'd be good if we added that information somewhere.

Then people using Augur could also immediately see if they're not using the latest version.

![image](https://user-images.githubusercontent.com/25161793/146408089-4a3668db-d423-4885-b635-c6c046f0c8cf.png)

**Comment by huddlej** [comment]
I can see the potential for confusion here, but this seems to be a RTD UI issue. The "stable" label depends on [RTD's parsing of versioned documentation](https://docs.readthedocs.io/en/stable/versions.html) where they assume we use semantic versioning and assign the "stable" label to the latest release.

We could explicitly state somewhere in the docs that "stable" is always the latest release, but I'm not sure where to put that where it would be consistently seen. Maybe in the footer?

**Comment by corneliusroemer** [comment]
There's already an issue upstream in RTD issue tracker, but it seems stale and the problem unresolved - quite surprisingly really, this does seem like quite a problem to me as a user.

SciTools/iris figured out a workaround. Not sure whether this is important enough for us to apply - or maybe we just tag it blocked and wait for upstream to fix it at some point?

https://github.com/readthedocs/readthedocs.org/issues/4529#issuecomment-1000000715
