### ISSUE TITLE
Inherited clade definitions

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#823]
Currently clades are defined independently of one another in the provided TSV, but we often duplicate the mutations of a parent clade. For example, 21L is a descendant of 21M so we have the following:

```
21M (Omicron) 	nuc 	23525 	T
21M (Omicron) 	nuc 	23599 	G
21L (Omicron) 	nuc 	23525 	T  ## mutation actually defines 21M
21L (Omicron) 	nuc 	23599 	G  ## mutation actually defines 21M
21L (Omicron) 	nuc 	24424 	T
```

We should allow clades to be inherited, e.g.:

```
21M (Omicron) 	nuc 	23525 	T
21M (Omicron) 	nuc 	23599 	G
21L (Omicron) 	clade 	21M (Omicron)
21L (Omicron) 	nuc 	24424 	T
```

There are a few considerations here:
* This introduces the potential for circular dependencies (A descended from B descended from A) which should be fatal errors.
* When both a parent and descendant clade are annotated on the same branch, the branch label should represent the descendant clade.
* Should multiple parent clades be allowed? Probably easiest to limit the current implementation to a single parent lineage.

**Related**

* [Slack conversation](https://bedfordlab.slack.com/archives/C01UN8SALPM/p1640727022006200)
* [List of `augur clade` oddities, including some bugs related to parsing the TSV file, which should be addressed before / as part of this issue](https://github.com/nextstrain/augur/issues/735)

**Possible solution**   

There seem to be two implementations available:
1. Expand the TSV upon parsing to replace the parent clade with the mutations of the parent clade
2. Only consider the subtree defined by the parent clade and then find the clade defined by the extra mutations (e.g. 24424T in the example above). 

I prefer solution 2, but I don't think the results will be different.

**Comment by corneliusroemer** [comment]
I will implement solution 1 since it's straightforward and simplifies the clade.tsv

We can always switch to solution 2 later.
