### ISSUE TITLE
Json schema validation too stringent for accession numbers 

### ISSUE THREAD

**Issue by ammaraziz** [nextstrain/augur#831]
**Current Behavior**  
When exporting to `auspice` using `augur export v2`, the json is validated against `/data/schema-export-v2.json` which contains the following regex pattern for accession id: `^[0-9A-Za-z-_]+$`.

This validation step will fail if the accession numbers have `.` (dots). However, accession numbers can and commonly do have dots. For example ncbi accession numbers commonly contain a dot to indicate record version, for example: `OF023914.1`.

To make matters worse, the validation step produces an error, which will result in the exported json file beind deleted by snakemake. Otherwise, the file is exported but with an error and a warning.

> ERROR: 'XXXXX.1' does not match '^[0-9A-Za-z-_]+$'. Trace: ... - properties - node_attrs - properties - accession - pattern
> ....
> Validation of 'results/tc2_h3.json' failed.

**Expected behavior**  
Accession numbers in the augur pipeline should be able to contain `.`. The json schema validation file contains url that have `.`, so I think it's safe to have accession IDs with dots. Please correct me if I am wrong.

To fix this issue, the regex pattern can be changed to `^[0-9A-Za-z-_\.]+$`. 

Alternatively, the validation step can return a warning instead of an error.

I am using augur version 13.1.0.

Thanks,

Ammar

**Comment by tsibley** [comment]
@ammaraziz Thanks for reporting this oversight! I've opened a PR to fix this and it should get reviewed by the team and merged soon.

**Comment by ammaraziz** [comment]
Thanks @tsibley for the super quick fix!
