### ISSUE TITLE
Filter does not create parent directories for `--output-strains` file

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#838]
**Current Behavior**  
When giving providing a path to _augur filter_'s `--output-strains` arg that includes a folder that doesn't (yet) exist, filter crashes with `FileNotFoundError: [Errno 2] No such file or directory '...'

**Expected behavior**  
I expect augur to create parent directories of output files as necessary. Maybe this is just a DX thing, not a bug per se, depends on the expectations one has. I've just never encountered this problem before despite using augur filter extensively, presumably because the directory in question had always been created for me by another command in the snakemake workflow.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Run `augur filter` with `--output-strains builds/doesntexist/strains.txt` where `doesntexist` doesn't yet exist
2. See error  

**Possible solution**  
Add `pathlib.Path('output_path').mkdir(parents=True, exist_ok=True)`

**Your environment: if running Nextstrain locally**  
 - Operating system:  macOS
 - Version (e.g. `auspice 2.7.0`):  13.1.2

**Comment by tsibley** [comment]
I understand the desire to automatically create parent dirs, but it does go against the convention that many other Unix-ish commands follow. Granted, workflow engines tend to take the opposite convention (with notable exception of `make`), but Augur is not a workflow engine. One typical reason is that not automatically creating parent dirs means that the path is as intended by the user and doesn't contain a typo which may cause confusion several steps later and be non-obvious.

**Comment by corneliusroemer** [comment]
Fair enough, I guess it's mostly my expectations that are wrong.

They expectation came from having seen this code, and thinking it was the convention augur generally used, combined with me not encountering this error hitherto within ncov-simple:
https://github.com/nextstrain/augur/blob/3931d5d9334ee2c3033fa151abfc0b41baaf4b80/augur/utils.py#L257-L261

**Comment by tsibley** [comment]
Ah! Well, if it's already Augur's convention for output file handling, then yeah, I'd say `augur filter` should match other `augur` commands. :-)

Generally I think it's important to follow common Unix-ish conventions, but I also think it's ok to deviate from them if we have good reason (e.g. if most of our users expect paths to be automatically created for them).

**Comment by corneliusroemer** [comment]
This may be the only output file (`auspice.json`) for which the directory is created, though. Couldn't find it anywhere else with a quick search.

**Comment by tsibley** [comment]
When I grepped, I saw that `write_json()` is used for ~all JSON files Augur outputs, not just the Auspice export. This includes the various node data files.

**Comment by huddlej** [comment]
There isn't an explicit convention in Augur, but if I were reviewing the `write_json` function in a new PR today, I would ask for that code that creates directories to be removed for the reasons @tsibley [describes above](https://github.com/nextstrain/augur/issues/838#issuecomment-1027127261).
