### ISSUE TITLE
Update dataset schema

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#848]
As part of the multi-tree / exploded-tree functionality introduced in https://github.com/nextstrain/auspice/pull/1442 the next auspice release will allow an array of trees and [the schema](https://github.com/nextstrain/augur/blob/master/augur/data/schema-export-v2.json) needs to be updated accordingly. 

Current schema (abridged):
```json
"tree": {
    "type" : "object",
    "$comment": "The phylogeny in a nested JSON structure",
    "properties": {
        "children": {
            "type": "array",
            "minItems": 1,
            "items": {"$ref": "#/properties/tree"}
        }
    }
}
```

The new schema is similar, except that the `tree` property can now be an object (as currently) or an array of objects. In the latter, each object is the same as the current `"$ref": "#/properties/tree"`.

It is fully backwards compatible and doesn't need a version bump. 

An example dataset is included (which currently fails validation)

[tree-array-example.json.gz](https://github.com/nextstrain/augur/files/8058032/tree-array-example.json.gz)

**Comment by tsibley** [comment]
I was already looking at the schemas this morning when I saw this issue, so I drafted a change for this in #851.
