### ISSUE TITLE
filter: behavior with invalid date values and scalability

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#855]
A date value of `?` is ignored, while `2022-XX-01` actually results in an error. I see how this could be useful to prevent unintended inputs, but have a few concerns:

1. Is this feature worth the additional complexity in date parsing? (i.e. as data scale increases, is it worth the burden of running this check on every row?)
2. If so, is it ok that values such as `2022-xx-01` are ignored instead of raising the same error?

### Example: `?`

```
echo 'strain\tcountry\tdate
SEQ1\tA\t?
SEQ2\tB\t2022-02-17' > metadata.tsv

augur filter \
  --metadata metadata.tsv \
  --min-date 2022-01-01 \
  --output-strains out.txt
```

Output:

```
1 strains were dropped during filtering
	1 of these were dropped because of their date (or lack of date)
1 strains passed all filters
```

### Example: `2022-XX-01`

```
echo 'strain\tcountry\tdate
SEQ1\tA\t2022-XX-01
SEQ2\tB\t2022-02-17' > metadata.tsv

augur filter \
  --metadata metadata.tsv \
  --min-date 2022-01-01 \
  --output-strains out.txt
```

Output:

```
...
ValueError: Invalid date: Month contains uncertainty, so day must also be uncertain.
```

**Comment by victorlin** [comment]
After digging deeper into profiling results, I realized that my suspicion of [date_disambiguator.py](https://github.com/nextstrain/augur/blob/15dfc8bc5c5a570066ddd5601c9aa82e0c1d2b7d/augur/util_support/date_disambiguator.py) being a bottleneck isn't actually the case, at least at the moment for GISAID SC2 data where there aren't a lot of ambiguous dates to prompt this check. It is still a potential issue for scalability in other analyses though.

**Comment by ammaraziz** [comment]
HI @victorlin,

I think your first example should be:
```
echo 'strain\tcountry\tdate
SEQ1\tA\t2022-?-01
SEQ2\tB\t2022-02-17' > metadata.tsv
```

Also on macos I need to add the `-e` flag to interpret escaped characters.

I didn't know the filter command had this property. It's surprising that `2022-XX-01` isn't treated as `2022-XX-XX` when filtering, for example when selecting any sample with a date > 2020-01-01.  I'd hate to have samples dropped that were sampled in the years I wanted but which had a day entered.

I do agree that `2022-XX-01` can be treated as an error for the day field but the year field could still be valid.

**Comment by emmahodcroft** [comment]
I think having this stay in is probably a good idea - the thinking here is that `?` clearly means an unknown date (and so up to the user to ensure they've added this correctly) but "2022-XX-01" really makes no sense at all, and is very likely due to some adulteration of data or misunderstanding of ISO format (thinking it's YYYY-DD-MM for example). I think alerting users to this is a good idea. Though this slows down really huge analyses like for SARS-CoV-2, for most use cases people are working with smaller datasets and ones where data is less likely to be so uniformly prepared (as a GISAID or Genbank download), so alerts like these can be pretty valuable to prevent unintended outcomes that can be really hard to trace back.

**Comment by victorlin** [comment]
@ammaraziz

> I think your first example should be:

Good catch, bad copy-pasting job on my end 😅. Updated comment.

> Also on macos I need to add the `-e` flag to interpret escaped characters.

Oh, you are probably using `bash` then. I'm using `zsh` (default with latest macOS) which doesn't require `-e`. More info on [this SO answer](https://stackoverflow.com/a/56416253).

**Comment by victorlin** [comment]
@ammaraziz @emmahodcroft thanks for the comments here! I think best to keep this then, plus it's actually not much of a time sink as I realized after writing up this issue. Closing.
