### ISSUE TITLE
NA flu display

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#86]
Currently, there are a couple issues with NA flu display. With updated `manifest_guest.json` in place in auspice you can see that:

1. Clade coloring does not work because of changes to augur.

Current auspice:

<img width="1015" alt="clade" src="https://user-images.githubusercontent.com/1176109/36800557-a7180878-1c64-11e8-83f4-52a734c9ea53.png">

It should look something like:

<img width="856" alt="clade-na" src="https://user-images.githubusercontent.com/1176109/36802624-501303f6-1c6a-11e8-9d0c-fac2bca58c4f.png">

Need to infer `clade_membership` for HA and then take these attrs and import them over to the same strain in NA.

2. ColorBys `ep`, `ne`, `rb` and `glyc` shouldn't be exported for NA. These only make sense for HA. This is also done in augur.

Threading this here because although it manifests in auspice, the fixes lie in augur.

**Comment by rneher** [comment]
`glyc` is potentially useful for NA. I'll see Sebastian Maurer Stroh next week. He already sent me glyco masks, will discuss with him and make this more biologically sane.
