### ISSUE TITLE
`augur export` complains about presence of `extensions` field in `auspice_config.json`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#861]
### Current Behavior
Back in November, we agreed to extend the Auspice JSON v2 schema with `extensions` (see https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1637783226217000) and https://github.com/nextstrain/nextclade/pull/615)

It looks like we never implemented this into `augur export`.

I added the following to `auspice_config.json`:

```
    "extensions": {
      "nextclade": {
        "clade_node_attrs": [
          {
            "name": "Nextclade_pango",
            "displayName": "Pango lineage (Nextclade)",
            "description": "Pango lineage as inferred by Nextclade from the nearest neighbour in the reference tree. 98% accurate for recent sequences, for higher accuracy use dedicated pangolin software in UShER or pangoLEARN mode"

          }
        ]
      }
    },
```

and got the following error `ERROR: Additional properties are not allowed ('extensions' was unexpected). Trace: additionalProperties`

<img width="2543" alt="image" src="https://user-images.githubusercontent.com/25161793/157753503-1f7455ae-224a-4371-9251-8bd7d26ae5ee.png">

### Expected behavior
No error, `extensions` field is accepted

### Possible solution
Edit auspice schema to allow `extensions` or otherwise make `augur export` not complain.

### Workaround
For now I can copy it in manually, but in the midterm, it would be nice if I could have the auspice_config.json accepted.

**Comment by jameshadfield** [comment]
Steps needed to implement:
1. add `extensions` property to https://github.com/nextstrain/augur/blob/master/augur/data/schema-auspice-config-v2.json
2. add `extensions` property to https://github.com/nextstrain/augur/blob/master/augur/data/schema-export-v2.json
3. modify https://github.com/nextstrain/augur/blob/master/augur/export_v2.py to pass through the property from the config to the exported (main) dataset JSON.

We may also consider a `--ignore-validation` flag to `augur export v2`, but in this case that wouldn't be enough as step 3 is needed.

**Comment by corneliusroemer** [comment]
Thanks @jameshadfield for coming up with a plan. I also thought `--ignore-validation` could be a useful addition for similar situations in the future, doesn't harm much and is easy to do.
