### ISSUE TITLE
dataset schema (v2) is out of date

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#867]
The schema has entries which were never actually used (neither exported from `augur export v2` nor consumed by auspice):

* `meta → tree_name`
* `meta → frequencies` (we use the sidecar instead)

https://github.com/nextstrain/augur/blob/master/augur/data/schema-export-v2.json#L266-L277

**Comment by tsibley** [comment]
Since these were never used, we can drop these from the schema without any worry about a new version or anything.
