### ISSUE TITLE
ENH: Augur export should fail with exit code != 0 when validation fails

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#870]
### Context
I thought validation was correct because Snakemake didn't abort, yet when I inspected the logs, I saw that validation had failed.

It appears that failure of validation doesn't cause `augur export` to exit with exit code `!= 0` as one would expect.

**Comment by joverlee521** [comment]
Hmm. Can you give more details here? Currently, if validation fails in `augur export v2` it [exits with `sys.exit(2)`](https://github.com/nextstrain/augur/blob/master/augur/export_v2.py#L531)

**Comment by jameshadfield** [comment]
Posting here for posterity:

The `augur export` command will produce the dataset JSON, then exit with code 2 if validation fails, and thus the dataset JSON will still exist. If you are using Snakemake, then that is what will perform clean up and remove the JSON.
