### ISSUE TITLE
BUG: extensions are placed at top level and not under `meta` as Nextclade expects

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#885]
#865 allows an `extensions` JSON object to be defined in auspice_config.json and passed through.

Unfortunately, I didn't realize that the current implementation places `extensions` at the top level and not under `meta` as Nextclade expects.

I had thought the discussion on Slack and my issue was clear about this expectation. But unfortunately it was nowhere mentioned that we had settled on `meta.extensions`.

Given that Nextclade is the only user of this feature so far and we have just released Augur 14.1, would it be possible to make a change from `extensions` to `meta.extensions`? @jameshadfield 

Maybe we can squeeze this in with the next release? The change would be quite trivial I think.

Alternatively we could accept both - but that would be asking for trouble. Changing what Nextclade expects would be troublesome.

Given that we were undecided about `extensions` or `meta.extensions` I feel we should just stick with whatever convention Nextclade has adopted.

I'm sorry this slipped through - I should have checked the PR better 😬

**Comment by tsibley** [comment]
To clarify, `extensions` remains top-level in the Auspice config schema but would change to be within `meta` in the dataset schema?

**Comment by corneliusroemer** [comment]
Yes correct. I think this may also be what one naively expects, since all the other auspice config properties get moved into meta anyways.
