### ISSUE TITLE
S3 deployment with pseudo-API

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#9]
Create data.nextstrain.org, which is a S3 instance to hold augur data for consumption in auspice

The pseudo-API is a file structure along the line of:

`/zika/dataHex/augurVersionId/*.json`

where dataHex is related to the time when the analysis was run - i.e. the amount of data available at that point in time (it could be YYMMDD). This should also be added to the metadata / tree - i.e. each sequence should detail when it was first available for analysis (different from when it was sampled). 

This way auspice can access a specific data build.

**Comment by trvrb** [comment]
We should revisit versioning in the context of per-pathogen repos. I'd like to be doing something like this with S3.

**Comment by huddlej** [comment]
@trvrb Has this S3 versioning of per-pathogen data been sufficiently resolved by the YYYY-MM-DD naming approach adopted for https://github.com/nextstrain/ncov or do you hope for more future development here?

**Comment by trvrb** [comment]
I think that the the YYYY-MM-DD "versioning" is going to be sufficient for most of our purposes here. For this issue, it may relate to how we were discussing persistent links to particular branches. However, at this point, I think that we could instead rely on planned work for mutation filtering to be able to have persistent links to particular sets of genomes.

I believe this issue can be closed.

**Comment by trvrb** [comment]
I think that the
