### ISSUE TITLE
Handle unexpected exceptions gracefully

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#903]
## Current Behavior

Most unexpected exceptions that occur when running Augur result in a Traceback printed to the command line and no other information for the user.

## Expected behavior

Augur should more gracefully handle unexpected exceptions by catching them at the top level of the `run` logic (as @jameshadfield has already [configured for recursion errors](https://github.com/nextstrain/augur/blob/002c44f94459ee5bf9111e5ece659c9e429fb1e5/augur/__init__.py#L74-L78)).

## Possible solution

When Augur encounters an unexpected exception, it should catch the exception at [the `run` level](https://github.com/nextstrain/augur/blob/002c44f94459ee5bf9111e5ece659c9e429fb1e5/augur/__init__.py#L75), print a friendly error message to the user that includes instructions on how to submit a bug report on GitHub, and then print a helpful version of the traceback for the GitHub report (this may not be the full traceback; [an abbreviated traceback may be more helpful](https://pypi.org/project/pretty-traceback/)). We could even go so far as to generate the bug report syntax for the user to copy and paste, if we wanted to be fancy about it.

## Additional context

This issue is related to [another general problem in Augur where we do not catch _expected_ exceptions](https://github.com/nextstrain/augur/issues/642) and print helpful error messages for users.

**Comment by victorlin** [comment]
Suggestion: print link to create a new GitHub issue (@tsibley says CLI does something similar already)

**Comment by huddlej** [comment]
[The CLI checks for unexpected errors that appear as AssertionErrors](https://github.com/nextstrain/cli/blob/8ec779b489254c3abb7bbbf4a8f3694c4ade854e/nextstrain/cli/__init__.py#L35-L49)
