### ISSUE TITLE
Augur export v2 JSON schema validation fails on Auspice config file that uses display_defaults.language

### ISSUE THREAD

**Issue by sacundim** [nextstrain/augur#911]
Auspice JSON configuration files support a `display_defaults.language` property to set the default language for the UI, [as documented here under the "Dataset (JSON) configurable defaults" section](https://github.com/nextstrain/auspice/blob/a0e9080dcd61249f24f6c822dfcf6478e4e07ac2/docs/advanced-functionality/view-settings.md).  I tried it in my ncov build, however, and the `augur export v2` command fails because [the JSON schema that it uses to validate it](https://github.com/nextstrain/augur/blob/784cdb898aefa67760323b0eec3f492fe1b7cbf3/augur/data/schema-auspice-config-v2.json) doesn't allow it. (Log messages below.)

I'm using a Docker image built off `nextstrain/base:latest` as of yesterday, and I checked that the the master branch version of the `schema-auspice-config-v2.json` doesn't list the `language` property, and that [the master version of auspice is using that property](https://github.com/nextstrain/auspice/blob/b8124eca8d3d8aee4cce67b19a0e8bedbcd41bc7/src/reducers/general.js#L50).

```
[Thu May  5 06:56:37 2022]
--
Error in rule export:
jobid: 6
output: results/puerto-rico/ncov_with_accessions.json, results/puerto-rico/ncov_with_accessions_root-sequence.json
log: logs/export_puerto-rico.txt (check log file(s) for error message)
shell:
 
augur export v2             --tree results/puerto-rico/tree.nwk             --metadata results/puerto-rico/metadata_adjusted.tsv.xz             --node-data results/puerto-rico/branch_lengths.json results/puerto-rico/nt_muts.json results/puerto-rico/aa_muts.json results/puerto-rico/emerging_lineages.json results/puerto-rico/clades.json results/puerto-rico/recency.json results/puerto-rico/traits.json results/puerto-rico/logistic_growth.json results/puerto-rico/mutational_fitness.json results/puerto-rico/distances.json results/puerto-rico/epiweeks.json             --auspice-config puerto-rico_profiles/puerto-rico_open/puerto-rico_auspice_config.json             --include-root-sequence             --colors results/puerto-rico/colors.tsv             --lat-longs defaults/lat_longs.tsv             --title 'SARS-CoV-2 en Puerto Rico, enfoque en últimos 6 meses'             --description results/puerto-rico/description.md             --output results/puerto-rico/ncov_with_accessions.json 2>&1 \| tee logs/export_puerto-rico.txt
 
(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile logs/export_puerto-rico.txt:
ERROR: Additional properties are not allowed ('language' was unexpected). Trace: properties - display_defaults - additionalProperties
Validating schema of 'results/puerto-rico/aa_muts.json'...
Validating config file puerto-rico_profiles/puerto-rico_open/puerto-rico_auspice_config.json against the JSON schema
Validating schema of 'puerto-rico_profiles/puerto-rico_open/puerto-rico_auspice_config.json'...
Validation of puerto-rico_profiles/puerto-rico_open/puerto-rico_auspice_config.json failed. Please check the formatting of this file & refer to the augur documentation for further help.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by tsibley** [comment]
@sacundim Thanks for this bug report. I can confirm that this is a bug in the schema. Will file a PR shortly to add `language` and two other missing keys. In the meantime, I think you could use `augur export v2`'s `--skip-validation` option to work around this error.

**Comment by tsibley** [comment]
Draft PR is https://github.com/nextstrain/augur/pull/916.

**Comment by sacundim** [comment]
> In the meantime, I think you could use `augur export v2`'s `--skip-validation` option to work around this error.

I tried this and it works. Thanks!
