### ISSUE TITLE
Zika reference sequence is not always pulled from metadata genbank file.

### ISSUE THREAD

**Issue by alliblk** [nextstrain/augur#96]
Currently, Augur looks for whether the reference strain is present in your fasta file or not. If it is not present, then the reference strain is pulled in from the genbank file in metadata. However, if your fasta already contains the reference sequence, augur does not overwrite this record with the genbank file sequence, but rather keeps the reference strain sequence in your fasta file. 

This is problematic for Zika builds specifically because the current reference strain that is used for alignment and trimming, PF13/251013_18, has two associated sequences in Fauna, one of which is wrong. If you pull data from Fauna without specifying `--resolve_method choose_genbank` you will download the incorrect sequence for PF13/251013_18 (wrong sequence is 11555 nts long, correct one is 10769 nts long, and sequenced by Troesemeier et al). Then the wrong reference does not get overwritten, and the multiple sequence alignment is mapped and trimmed to an incorrect sequence.

**Comment by trvrb** [comment]
Thanks for note @alliblk. I just checked this on modular augur and the issue there is resolved. In this case, when aligning, you explicitly specify a Genbank reference to align to: https://github.com/nextstrain/augur/blob/13f36fbc0883d72fdf07e9ff7c1d21917073b286/builds/zika/Snakefile#L52. This results in the Genbank version overwriting the version passed in through the FASTA.

**Comment by trvrb** [comment]
@tsibley ---

Thanks for digging into this. I was assuming that it overwrote given that the resulting `aligned.fasta` just contained a single version of `PF13/251013_18` and that this version was the right length. `PF13/251013_18` was in the input `sequences.fasta`.

Perhaps the help for `--reference-sequence` could make it clearer that this expects a file (Genbank or FASTA).

**Comment by alliblk** [comment]
I haven't poked around modular augur yet, but glad to hear that it might fix this issue. That said, I'm wondering if it might be a good idea to also hardcode removal of the non-Troesemeier et al version of `PF13/251013_18` during the prepare step, since this sequence seems so off.

**Comment by huddlej** [comment]
This issue seems to be resolved in the latest modular augur builds. The current Zika build uses `choose_genbank` for the [download rule](https://github.com/nextstrain/zika/blob/9e50fe2/Snakefile#L29) and uses the explicit `--reference-sequence` flag for the [alignment rule](https://github.com/nextstrain/zika/blob/9e50fe2/Snakefile#L85-L103). This results in the correct `PF13/251013_18` sequence passing through the alignment stage and into the tree building stage.
