### ISSUE TITLE
Document how to upgrade read_metadata

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#970]
Many scripts (inclucing our own) still use augur's `augur.utils.read_metadata` which [has been removed](https://github.com/nextstrain/augur/commit/040822c4c20daf596ee31c1a02a1d8294d785573) in favour of `augur.io.read_metadata`. The latter has a different interface than the former. We should provide a small vignette of how to update code, e.g. [from a previous issue](https://github.com/nextstrain/augur/pull/909#pullrequestreview-962755757)

```py
# untested
metadata_df = read_metadata(args.metadata)
columns = metadata_df.columns
meta_tsv = metadata_df.to_dict(orient="index")
for strain in meta_tsv.keys():
    meta_tsv[strain]["strain"] = strain
```

As far as I can tell, the changelog doesn't mention that this function has been removed. It should, and this would be a good place to cross-link to docs explaining how to update calling code.

**Comment by victorlin** [comment]
Thanks for catching this @jameshadfield, you're right this is used in at least our seasonal-flu and ncov repos. @huddlej @joverlee521 and I just met to discuss, and the plan is:

1. Revert 040822c4c20daf596ee31c1a02a1d8294d785573
2. Do release, without breaking change of `utils.read_metadata`
3. Make necessary changes to replace `utils.read_metadata` with `io.read_metadata` in our own repos
4. Add 040822c4c20daf596ee31c1a02a1d8294d785573 as a breaking change for the next release

**Comment by huddlej** [comment]
Thank you for pointing this out, @jameshadfield! The only change I would make to the code sample above is to make sure "strain" is added to a `list` of columns:

```
metadata_df = read_metadata(args.metadata)
columns = ["strain"] + metadata_df.columns.tolist()
meta_tsv = metadata_df.to_dict(orient="index")
for strain in meta_tsv.keys():
    meta_tsv[strain]["strain"] = strain
```

We should also point out that `io.read_metadata` returns a pandas DataFrame which can be much more efficient to keep in memory and interact with than a dictionary. This means users should not blindly use the code above to "upgrade", but should use the appropriate code to interact with pandas DataFrames.

For example, when iterating through each key and record, users can make the following change:

```diff
-    meta, columns = read_metadata(args.metadata)
-    for strain, d in meta.items():
+    meta = read_metadata(args.metadata)
+    for strain, d in meta.iterrows():
```

Users who are indexing specific strain names and fields per record can replace the dictionary lookup with the corresponding pandas lookup:

```diff
- count_by_group[metadata[child.name][group_by]] += 1
+ count_by_group[metadata.loc[child.name, group_by]] += 1
```

**Comment by victorlin** [comment]
A summary from the internal migration done in 99c4d05e607e1017e37f07cb0aa203cd1fd316d0...99ee33f898119a5573629e9ea4b14fe85817dd8a:

- Iterate through strains: `metadata.items()` -> `metadata.iterrows()`
- Check strain presence: `strain in metadata` -> `strain in metadata.index`
- Check field presence: `field in metadata[strain]` -> `field in metadata.columns`
- Get metadata for a strain: `metadata[strain]` -> `metadata.loc[strain]`
- Get field for a strain: `metadata[strain][field]` -> `metadata.loc[strain][field]`

**Comment by huddlej** [comment]
The alternate approach to the code block in the issue description above that @victorlin [inspired over in ncov would be](https://github.com/nextstrain/ncov/pull/962#discussion_r899655497):

```python
metadata = read_metadata(args.metadata)
metadata.insert(0, "strain", metadata.index.values)
columns = metadata.columns
metadata = metadata.to_dict(orient="index")
```

**Comment by victorlin** [comment]
I summarized the recommendations in #978 ([preview CHANGES.md](https://github.com/victorlin/augur/blob/0ff274fdeca096b8abc8fefe0c372960ecaaf4dc/CHANGES.md#next))

**Comment by jameshadfield** [comment]
Closing this now as it's in the changelog (for the next release), however please re-open if there are still steps to take.

**Comment by victorlin** [comment]
Actually, the PR isn't reviewed/merged yet. I'll re-open and set to auto-close by keyword in #978
